const quizArray_level6 = [
  {
    id: "0",
    question: "ત",
    options: ['ta', 'La', 'tha', 'ha'],
    correct: "ta",
  },
  {
    id: "1",
    question: "થ",
    options: ['tha', 'ta', 'La', 'ha'],
    correct: "tha",
  },
  {
    id: "2",
    question: "હ",
    options: ['ha', 'tha', 'ta', 'La'],
    correct: "ha",
  },
  {
    id: "3",
    question: "ળ",
    options: ['La', 'ha', 'tha', 'ta'],
    correct: "La",
  },
  {
    id: "4",
    question: "ત",
    options: ['ta', 'ha', 'tha', 'La'],
    correct: "ta",
  },
  {
    id: "5",
    question: "થ",
    options: ['tha', 'La', 'ta', 'ha'],
    correct: "tha",
  },
  {
    id: "6",
    question: "હ",
    options: ['ha', 'ta', 'La', 'tha'],
    correct: "ha",
  },
  {
    id: "7",
    question: "ળ",
    options: ['La', 'ha', 'ta', 'tha'],
    correct: "La",
  },
  {
    id: "8",
    question: "ત",
    options: ['ta', 'ha', 'La', 'tha'],
    correct: "ta",
  },
  {
    id: "9",
    question: "થ",
    options: ['tha', 'ha', 'La', 'ta'],
    correct: "tha",
  },
  {
    id: "10",
    question: "હ",
    options: ['ha', 'La', 'ta', 'tha'],
    correct: "ha",
  },
  {
    id: "11",
    question: "ળ",
    options: ['La', 'tha', 'ha', 'ta'],
    correct: "La",
  },
  {
    id: "12",
    question: "ત",
    options: ['ta', 'tha', 'ha', 'La'],
    correct: "ta",
  },
  {
    id: "13",
    question: "થ",
    options: ['tha', 'ta', 'La', 'ha'],
    correct: "tha",
  },
  {
    id: "14",
    question: "હ",
    options: ['ha', 'tha', 'La', 'ta'],
    correct: "ha",
  },
  {
    id: "15",
    question: "ળ",
    options: ['La', 'ha', 'ta', 'tha'],
    correct: "La",
  },
  {
    id: "16",
    question: "ત",
    options: ['ta', 'ha', 'tha', 'La'],
    correct: "ta",
  },
  {
    id: "17",
    question: "થ",
    options: ['tha', 'ta', 'ha', 'La'],
    correct: "tha",
  },
  {
    id: "18",
    question: "હ",
    options: ['ha', 'ta', 'tha', 'La'],
    correct: "ha",
  },
  {
    id: "19",
    question: "ળ",
    options: ['La', 'ha', 'tha', 'ta'],
    correct: "La",
  },
  {
    id: "20",
    question: "ત",
    options: ['ta', 'ha', 'La', 'tha'],
    correct: "ta",
  },
  {
    id: "21",
    question: "થ",
    options: ['tha', 'La', 'ha', 'ta'],
    correct: "tha",
  },
  {
    id: "22",
    question: "હ",
    options: ['ha', 'ta', 'La', 'tha'],
    correct: "ha",
  },
  {
    id: "23",
    question: "ળ",
    options: ['La', 'ta', 'tha', 'ha'],
    correct: "La",
  },
  {
    id: "24",
    question: "ત",
    options: ['ta', 'La', 'ha', 'tha'],
    correct: "ta",
  },
  {
    id: "25",
    question: "થ",
    options: ['tha', 'ha', 'ta', 'La'],
    correct: "tha",
  },
  {
    id: "26",
    question: "હ",
    options: ['ha', 'La', 'tha', 'ta'],
    correct: "ha",
  },
  {
    id: "27",
    question: "ળ",
    options: ['La', 'ta', 'ha', 'tha'],
    correct: "La",
  },
  {
    id: "28",
    question: "ત",
    options: ['ta', 'La', 'tha', 'ha'],
    correct: "ta",
  },
  {
    id: "29",
    question: "થ",
    options: ['tha', 'ha', 'ta', 'La'],
    correct: "tha",
  },
  {
    id: "30",
    question: "હ",
    options: ['ha', 'tha', 'La', 'ta'],
    correct: "ha",
  },
  {
    id: "31",
    question: "ળ",
    options: ['La', 'tha', 'ha', 'ta'],
    correct: "La",
  },
  {
    id: "32",
    question: "ત",
    options: ['ta', 'tha', 'La', 'ha'],
    correct: "ta",
  },
  {
    id: "33",
    question: "થ",
    options: ['tha', 'La', 'ta', 'ha'],
    correct: "tha",
  },
  {
    id: "34",
    question: "હ",
    options: ['ha', 'tha', 'ta', 'La'],
    correct: "ha",
  },
  {
    id: "35",
    question: "ળ",
    options: ['La', 'ha', 'ta', 'tha'],
    correct: "La",
  },
  {
    id: "36",
    question: "ત",
    options: ['ta', 'tha', 'La', 'ha'],
    correct: "ta",
  },
  {
    id: "37",
    question: "થ",
    options: ['tha', 'La', 'ta', 'ha'],
    correct: "tha",
  },
  {
    id: "38",
    question: "હ",
    options: ['ha', 'tha', 'ta', 'La'],
    correct: "ha",
  },
  {
    id: "39",
    question: "ળ",
    options: ['La', 'tha', 'ha', 'ta'],
    correct: "La",
  },
  {
    id: "40",
    question: "ત",
    options: ['ta', 'ha', 'La', 'tha'],
    correct: "ta",
  },
  {
    id: "41",
    question: "થ",
    options: ['tha', 'ha', 'La', 'ta'],
    correct: "tha",
  },
  {
    id: "42",
    question: "હ",
    options: ['ha', 'La', 'tha', 'ta'],
    correct: "ha",
  },
  {
    id: "43",
    question: "ળ",
    options: ['La', 'ha', 'ta', 'tha'],
    correct: "La",
  },
  {
    id: "44",
    question: "ત",
    options: ['ta', 'tha', 'ha', 'La'],
    correct: "ta",
  },
  {
    id: "45",
    question: "થ",
    options: ['tha', 'La', 'ta', 'ha'],
    correct: "tha",
  },
  {
    id: "46",
    question: "હ",
    options: ['ha', 'La', 'ta', 'tha'],
    correct: "ha",
  },
  {
    id: "47",
    question: "ળ",
    options: ['La', 'ta', 'ha', 'tha'],
    correct: "La",
  },
  {
    id: "48",
    question: "ત",
    options: ['ta', 'ha', 'La', 'tha'],
    correct: "ta",
  },
  {
    id: "49",
    question: "થ",
    options: ['tha', 'ha', 'La', 'ta'],
    correct: "tha",
  },
  {
    id: "50",
    question: "હ",
    options: ['ha', 'ta', 'tha', 'La'],
    correct: "ha",
  },
  {
    id: "51",
    question: "ળ",
    options: ['La', 'ha', 'ta', 'tha'],
    correct: "La",
  },
  {
    id: "52",
    question: "ત",
    options: ['ta', 'tha', 'ha', 'La'],
    correct: "ta",
  },
  {
    id: "53",
    question: "થ",
    options: ['tha', 'ha', 'ta', 'La'],
    correct: "tha",
  },
  {
    id: "54",
    question: "હ",
    options: ['ha', 'tha', 'La', 'ta'],
    correct: "ha",
  },
  {
    id: "55",
    question: "ળ",
    options: ['La', 'ha', 'ta', 'tha'],
    correct: "La",
  },
  {
    id: "56",
    question: "ત",
    options: ['ta', 'tha', 'La', 'ha'],
    correct: "ta",
  },
  {
    id: "57",
    question: "થ",
    options: ['tha', 'La', 'ha', 'ta'],
    correct: "tha",
  },
  {
    id: "58",
    question: "હ",
    options: ['ha', 'ta', 'tha', 'La'],
    correct: "ha",
  },
  {
    id: "59",
    question: "ળ",
    options: ['La', 'tha', 'ha', 'ta'],
    correct: "La",
  },
  {
    id: "60",
    question: "ત",
    options: ['ta', 'ha', 'tha', 'La'],
    correct: "ta",
  },
  {
    id: "61",
    question: "થ",
    options: ['tha', 'La', 'ha', 'ta'],
    correct: "tha",
  },
  {
    id: "62",
    question: "હ",
    options: ['ha', 'ta', 'tha', 'La'],
    correct: "ha",
  },
  {
    id: "63",
    question: "ળ",
    options: ['La', 'tha', 'ha', 'ta'],
    correct: "La",
  },
  {
    id: "64",
    question: "ત",
    options: ['ta', 'ha', 'La', 'tha'],
    correct: "ta",
  },
  {
    id: "65",
    question: "થ",
    options: ['tha', 'ha', 'ta', 'La'],
    correct: "tha",
  },
  {
    id: "66",
    question: "હ",
    options: ['ha', 'tha', 'ta', 'La'],
    correct: "ha",
  },
  {
    id: "67",
    question: "ળ",
    options: ['La', 'ta', 'tha', 'ha'],
    correct: "La",
  },
  {
    id: "68",
    question: "ત",
    options: ['ta', 'La', 'ha', 'tha'],
    correct: "ta",
  },
  {
    id: "69",
    question: "થ",
    options: ['tha', 'La', 'ha', 'ta'],
    correct: "tha",
  },
  {
    id: "70",
    question: "હ",
    options: ['ha', 'tha', 'ta', 'La'],
    correct: "ha",
  },
  {
    id: "71",
    question: "ળ",
    options: ['La', 'tha', 'ha', 'ta'],
    correct: "La",
  },
  {
    id: "72",
    question: "ત",
    options: ['ta', 'tha', 'La', 'ha'],
    correct: "ta",
  },
  {
    id: "73",
    question: "થ",
    options: ['tha', 'La', 'ta', 'ha'],
    correct: "tha",
  },
  {
    id: "74",
    question: "હ",
    options: ['ha', 'ta', 'La', 'tha'],
    correct: "ha",
  },
  {
    id: "75",
    question: "ળ",
    options: ['La', 'tha', 'ta', 'ha'],
    correct: "La",
  },
  {
    id: "76",
    question: "ત",
    options: ['ta', 'La', 'ha', 'tha'],
    correct: "ta",
  },
  {
    id: "77",
    question: "થ",
    options: ['tha', 'ha', 'ta', 'La'],
    correct: "tha",
  },
  {
    id: "78",
    question: "હ",
    options: ['ha', 'ta', 'La', 'tha'],
    correct: "ha",
  },
  {
    id: "79",
    question: "ળ",
    options: ['La', 'ha', 'tha', 'ta'],
    correct: "La",
  },
  {
    id: "80",
    question: "ત",
    options: ['ta', 'tha', 'ha', 'La'],
    correct: "ta",
  },
  {
    id: "81",
    question: "થ",
    options: ['tha', 'La', 'ha', 'ta'],
    correct: "tha",
  },
  {
    id: "82",
    question: "હ",
    options: ['ha', 'La', 'tha', 'ta'],
    correct: "ha",
  },
  {
    id: "83",
    question: "ળ",
    options: ['La', 'ta', 'ha', 'tha'],
    correct: "La",
  },
  {
    id: "84",
    question: "ત",
    options: ['ta', 'tha', 'ha', 'La'],
    correct: "ta",
  },
  {
    id: "85",
    question: "થ",
    options: ['tha', 'La', 'ta', 'ha'],
    correct: "tha",
  },
  {
    id: "86",
    question: "હ",
    options: ['ha', 'La', 'ta', 'tha'],
    correct: "ha",
  },
  {
    id: "87",
    question: "ળ",
    options: ['La', 'ha', 'ta', 'tha'],
    correct: "La",
  },
  {
    id: "88",
    question: "ત",
    options: ['ta', 'La', 'tha', 'ha'],
    correct: "ta",
  },
  {
    id: "89",
    question: "થ",
    options: ['tha', 'ta', 'ha', 'La'],
    correct: "tha",
  },
  {
    id: "90",
    question: "હ",
    options: ['ha', 'La', 'tha', 'ta'],
    correct: "ha",
  },
  {
    id: "91",
    question: "ળ",
    options: ['La', 'ha', 'ta', 'tha'],
    correct: "La",
  },
  {
    id: "92",
    question: "ત",
    options: ['ta', 'La', 'tha', 'ha'],
    correct: "ta",
  },
  {
    id: "93",
    question: "થ",
    options: ['tha', 'ha', 'La', 'ta'],
    correct: "tha",
  },
  {
    id: "94",
    question: "હ",
    options: ['ha', 'La', 'tha', 'ta'],
    correct: "ha",
  },
  {
    id: "95",
    question: "ળ",
    options: ['La', 'ha', 'ta', 'tha'],
    correct: "La",
  },
  {
    id: "96",
    question: "ત",
    options: ['ta', 'La', 'ha', 'tha'],
    correct: "ta",
  },
  {
    id: "97",
    question: "થ",
    options: ['tha', 'La', 'ta', 'ha'],
    correct: "tha",
  },
  {
    id: "98",
    question: "હ",
    options: ['ha', 'La', 'tha', 'ta'],
    correct: "ha",
  },
  {
    id: "99",
    question: "ળ",
    options: ['La', 'tha', 'ha', 'ta'],
    correct: "La",
  },
  {
    id: "100",
    question: "ત",
    options: ['ta', 'La', 'ha', 'tha'],
    correct: "ta",
  },
  {
    id: "101",
    question: "થ",
    options: ['tha', 'ta', 'La', 'ha'],
    correct: "tha",
  },
  {
    id: "102",
    question: "હ",
    options: ['ha', 'La', 'tha', 'ta'],
    correct: "ha",
  },
  {
    id: "103",
    question: "ળ",
    options: ['La', 'tha', 'ta', 'ha'],
    correct: "La",
  },
  {
    id: "104",
    question: "ત",
    options: ['ta', 'tha', 'La', 'ha'],
    correct: "ta",
  },
  {
    id: "105",
    question: "થ",
    options: ['tha', 'La', 'ha', 'ta'],
    correct: "tha",
  },
  {
    id: "106",
    question: "હ",
    options: ['ha', 'La', 'ta', 'tha'],
    correct: "ha",
  },
  {
    id: "107",
    question: "ળ",
    options: ['La', 'tha', 'ha', 'ta'],
    correct: "La",
  },
  {
    id: "108",
    question: "ત",
    options: ['ta', 'tha', 'La', 'ha'],
    correct: "ta",
  },
  {
    id: "109",
    question: "થ",
    options: ['tha', 'ha', 'ta', 'La'],
    correct: "tha",
  },
  {
    id: "110",
    question: "હ",
    options: ['ha', 'tha', 'La', 'ta'],
    correct: "ha",
  },
  {
    id: "111",
    question: "ળ",
    options: ['La', 'tha', 'ha', 'ta'],
    correct: "La",
  },
  {
    id: "112",
    question: "ત",
    options: ['ta', 'ha', 'La', 'tha'],
    correct: "ta",
  },
  {
    id: "113",
    question: "થ",
    options: ['tha', 'La', 'ta', 'ha'],
    correct: "tha",
  },
  {
    id: "114",
    question: "હ",
    options: ['ha', 'tha', 'ta', 'La'],
    correct: "ha",
  },
  {
    id: "115",
    question: "ળ",
    options: ['La', 'ha', 'ta', 'tha'],
    correct: "La",
  },
  {
    id: "116",
    question: "ત",
    options: ['ta', 'tha', 'ha', 'La'],
    correct: "ta",
  },
  {
    id: "117",
    question: "થ",
    options: ['tha', 'La', 'ha', 'ta'],
    correct: "tha",
  },
  {
    id: "118",
    question: "હ",
    options: ['ha', 'tha', 'La', 'ta'],
    correct: "ha",
  },
  {
    id: "119",
    question: "ળ",
    options: ['La', 'ha', 'ta', 'tha'],
    correct: "La",
  },
  {
    id: "120",
    question: "ત",
    options: ['ta', 'La', 'tha', 'ha'],
    correct: "ta",
  },
  {
    id: "121",
    question: "થ",
    options: ['tha', 'ha', 'La', 'ta'],
    correct: "tha",
  },
  {
    id: "122",
    question: "હ",
    options: ['ha', 'La', 'tha', 'ta'],
    correct: "ha",
  },
  {
    id: "123",
    question: "ળ",
    options: ['La', 'ta', 'ha', 'tha'],
    correct: "La",
  },
  {
    id: "124",
    question: "ત",
    options: ['ta', 'ha', 'La', 'tha'],
    correct: "ta",
  },
  {
    id: "125",
    question: "થ",
    options: ['tha', 'ta', 'ha', 'La'],
    correct: "tha",
  },
  {
    id: "126",
    question: "હ",
    options: ['ha', 'La', 'tha', 'ta'],
    correct: "ha",
  },
  {
    id: "127",
    question: "ળ",
    options: ['La', 'tha', 'ta', 'ha'],
    correct: "La",
  },
  {
    id: "128",
    question: "ત",
    options: ['ta', 'ha', 'tha', 'La'],
    correct: "ta",
  },
  {
    id: "129",
    question: "થ",
    options: ['tha', 'ta', 'La', 'ha'],
    correct: "tha",
  },
  {
    id: "130",
    question: "હ",
    options: ['ha', 'ta', 'tha', 'La'],
    correct: "ha",
  },
  {
    id: "131",
    question: "ળ",
    options: ['La', 'ta', 'ha', 'tha'],
    correct: "La",
  },
  {
    id: "132",
    question: "ત",
    options: ['ta', 'tha', 'La', 'ha'],
    correct: "ta",
  },
  {
    id: "133",
    question: "થ",
    options: ['tha', 'ta', 'ha', 'La'],
    correct: "tha",
  },
  {
    id: "134",
    question: "હ",
    options: ['ha', 'La', 'ta', 'tha'],
    correct: "ha",
  },
  {
    id: "135",
    question: "ળ",
    options: ['La', 'tha', 'ta', 'ha'],
    correct: "La",
  },
  {
    id: "136",
    question: "ત",
    options: ['ta', 'La', 'ha', 'tha'],
    correct: "ta",
  },
  {
    id: "137",
    question: "થ",
    options: ['tha', 'La', 'ta', 'ha'],
    correct: "tha",
  },
  {
    id: "138",
    question: "હ",
    options: ['ha', 'ta', 'La', 'tha'],
    correct: "ha",
  },
  {
    id: "139",
    question: "ળ",
    options: ['La', 'tha', 'ha', 'ta'],
    correct: "La",
  },
  {
    id: "140",
    question: "ત",
    options: ['ta', 'tha', 'ha', 'La'],
    correct: "ta",
  },
  {
    id: "141",
    question: "થ",
    options: ['tha', 'ta', 'La', 'ha'],
    correct: "tha",
  },
  {
    id: "142",
    question: "હ",
    options: ['ha', 'tha', 'La', 'ta'],
    correct: "ha",
  },
  {
    id: "143",
    question: "ળ",
    options: ['La', 'tha', 'ha', 'ta'],
    correct: "La",
  },
  {
    id: "144",
    question: "ત",
    options: ['ta', 'La', 'tha', 'ha'],
    correct: "ta",
  },
  {
    id: "145",
    question: "થ",
    options: ['tha', 'ha', 'La', 'ta'],
    correct: "tha",
  },
  {
    id: "146",
    question: "હ",
    options: ['ha', 'ta', 'La', 'tha'],
    correct: "ha",
  },
  {
    id: "147",
    question: "ળ",
    options: ['La', 'tha', 'ta', 'ha'],
    correct: "La",
  },
  {
    id: "148",
    question: "ત",
    options: ['ta', 'La', 'ha', 'tha'],
    correct: "ta",
  },
  {
    id: "149",
    question: "થ",
    options: ['tha', 'ta', 'La', 'ha'],
    correct: "tha",
  },
  {
    id: "150",
    question: "હ",
    options: ['ha', 'tha', 'ta', 'La'],
    correct: "ha",
  },
  {
    id: "151",
    question: "ળ",
    options: ['La', 'tha', 'ha', 'ta'],
    correct: "La",
  },
  {
    id: "152",
    question: "ત",
    options: ['ta', 'ha', 'tha', 'La'],
    correct: "ta",
  },
  {
    id: "153",
    question: "થ",
    options: ['tha', 'La', 'ha', 'ta'],
    correct: "tha",
  },
  {
    id: "154",
    question: "હ",
    options: ['ha', 'tha', 'ta', 'La'],
    correct: "ha",
  },
  {
    id: "155",
    question: "ળ",
    options: ['La', 'tha', 'ta', 'ha'],
    correct: "La",
  },
  {
    id: "156",
    question: "ત",
    options: ['ta', 'tha', 'La', 'ha'],
    correct: "ta",
  },
  {
    id: "157",
    question: "થ",
    options: ['tha', 'ha', 'La', 'ta'],
    correct: "tha",
  },
  {
    id: "158",
    question: "હ",
    options: ['ha', 'ta', 'tha', 'La'],
    correct: "ha",
  },
  {
    id: "159",
    question: "ળ",
    options: ['La', 'ta', 'ha', 'tha'],
    correct: "La",
  },
  {
    id: "160",
    question: "ત",
    options: ['ta', 'ha', 'La', 'tha'],
    correct: "ta",
  },
  {
    id: "161",
    question: "થ",
    options: ['tha', 'ta', 'ha', 'La'],
    correct: "tha",
  },
  {
    id: "162",
    question: "હ",
    options: ['ha', 'La', 'tha', 'ta'],
    correct: "ha",
  },
  {
    id: "163",
    question: "ળ",
    options: ['La', 'ta', 'ha', 'tha'],
    correct: "La",
  },
  {
    id: "164",
    question: "ત",
    options: ['ta', 'ha', 'tha', 'La'],
    correct: "ta",
  },
  {
    id: "165",
    question: "થ",
    options: ['tha', 'ta', 'ha', 'La'],
    correct: "tha",
  },
  {
    id: "166",
    question: "હ",
    options: ['ha', 'ta', 'La', 'tha'],
    correct: "ha",
  },
  {
    id: "167",
    question: "ળ",
    options: ['La', 'ta', 'tha', 'ha'],
    correct: "La",
  },
  {
    id: "168",
    question: "ત",
    options: ['ta', 'La', 'tha', 'ha'],
    correct: "ta",
  },
  {
    id: "169",
    question: "થ",
    options: ['tha', 'ha', 'La', 'ta'],
    correct: "tha",
  },
  {
    id: "170",
    question: "હ",
    options: ['ha', 'tha', 'ta', 'La'],
    correct: "ha",
  },
  {
    id: "171",
    question: "ળ",
    options: ['La', 'ha', 'ta', 'tha'],
    correct: "La",
  },
  {
    id: "172",
    question: "ત",
    options: ['ta', 'La', 'ha', 'tha'],
    correct: "ta",
  },
  {
    id: "173",
    question: "થ",
    options: ['tha', 'La', 'ta', 'ha'],
    correct: "tha",
  },
  {
    id: "174",
    question: "હ",
    options: ['ha', 'La', 'ta', 'tha'],
    correct: "ha",
  },
  {
    id: "175",
    question: "ળ",
    options: ['La', 'ta', 'ha', 'tha'],
    correct: "La",
  },
  {
    id: "176",
    question: "ત",
    options: ['ta', 'La', 'ha', 'tha'],
    correct: "ta",
  },
  {
    id: "177",
    question: "થ",
    options: ['tha', 'ha', 'La', 'ta'],
    correct: "tha",
  },
  {
    id: "178",
    question: "હ",
    options: ['ha', 'La', 'tha', 'ta'],
    correct: "ha",
  },
  {
    id: "179",
    question: "ળ",
    options: ['La', 'ta', 'ha', 'tha'],
    correct: "La",
  },
  {
    id: "180",
    question: "ત",
    options: ['ta', 'ha', 'La', 'tha'],
    correct: "ta",
  },
  {
    id: "181",
    question: "થ",
    options: ['tha', 'La', 'ha', 'ta'],
    correct: "tha",
  },
  {
    id: "182",
    question: "હ",
    options: ['ha', 'La', 'tha', 'ta'],
    correct: "ha",
  },
  {
    id: "183",
    question: "ળ",
    options: ['La', 'tha', 'ta', 'ha'],
    correct: "La",
  },
  {
    id: "184",
    question: "ત",
    options: ['ta', 'tha', 'ha', 'La'],
    correct: "ta",
  },
  {
    id: "185",
    question: "થ",
    options: ['tha', 'ha', 'ta', 'La'],
    correct: "tha",
  },
  {
    id: "186",
    question: "હ",
    options: ['ha', 'tha', 'La', 'ta'],
    correct: "ha",
  },
  {
    id: "187",
    question: "ળ",
    options: ['La', 'ta', 'tha', 'ha'],
    correct: "La",
  },
  {
    id: "188",
    question: "ત",
    options: ['ta', 'tha', 'La', 'ha'],
    correct: "ta",
  },
  {
    id: "189",
    question: "થ",
    options: ['tha', 'La', 'ha', 'ta'],
    correct: "tha",
  },
  {
    id: "190",
    question: "હ",
    options: ['ha', 'La', 'tha', 'ta'],
    correct: "ha",
  },
  {
    id: "191",
    question: "ળ",
    options: ['La', 'tha', 'ha', 'ta'],
    correct: "La",
  },
  {
    id: "192",
    question: "ત",
    options: ['ta', 'ha', 'La', 'tha'],
    correct: "ta",
  },
  {
    id: "193",
    question: "થ",
    options: ['tha', 'ta', 'La', 'ha'],
    correct: "tha",
  },
  {
    id: "194",
    question: "હ",
    options: ['ha', 'La', 'ta', 'tha'],
    correct: "ha",
  },
  {
    id: "195",
    question: "ળ",
    options: ['La', 'ha', 'ta', 'tha'],
    correct: "La",
  },
  {
    id: "196",
    question: "ત",
    options: ['ta', 'tha', 'La', 'ha'],
    correct: "ta",
  },
  {
    id: "197",
    question: "થ",
    options: ['tha', 'ha', 'La', 'ta'],
    correct: "tha",
  },
  {
    id: "198",
    question: "હ",
    options: ['ha', 'La', 'ta', 'tha'],
    correct: "ha",
  },
  {
    id: "199",
    question: "ળ",
    options: ['La', 'ta', 'tha', 'ha'],
    correct: "La",
  },
  {
    id: "200",
    question: "ત",
    options: ['ta', 'tha', 'ha', 'La'],
    correct: "ta",
  },
  {
    id: "201",
    question: "થ",
    options: ['tha', 'La', 'ha', 'ta'],
    correct: "tha",
  },
  {
    id: "202",
    question: "હ",
    options: ['ha', 'ta', 'tha', 'La'],
    correct: "ha",
  },
  {
    id: "203",
    question: "ળ",
    options: ['La', 'ha', 'tha', 'ta'],
    correct: "La",
  },
  {
    id: "204",
    question: "ત",
    options: ['ta', 'La', 'tha', 'ha'],
    correct: "ta",
  },
  {
    id: "205",
    question: "થ",
    options: ['tha', 'ta', 'ha', 'La'],
    correct: "tha",
  },
  {
    id: "206",
    question: "હ",
    options: ['ha', 'tha', 'La', 'ta'],
    correct: "ha",
  },
  {
    id: "207",
    question: "ળ",
    options: ['La', 'ha', 'tha', 'ta'],
    correct: "La",
  },
  {
    id: "208",
    question: "ત",
    options: ['ta', 'tha', 'La', 'ha'],
    correct: "ta",
  },
  {
    id: "209",
    question: "થ",
    options: ['tha', 'La', 'ha', 'ta'],
    correct: "tha",
  },
  {
    id: "210",
    question: "હ",
    options: ['ha', 'La', 'ta', 'tha'],
    correct: "ha",
  },
  {
    id: "211",
    question: "ળ",
    options: ['La', 'ha', 'tha', 'ta'],
    correct: "La",
  },
  {
    id: "212",
    question: "ત",
    options: ['ta', 'tha', 'ha', 'La'],
    correct: "ta",
  },
  {
    id: "213",
    question: "થ",
    options: ['tha', 'ha', 'La', 'ta'],
    correct: "tha",
  },
  {
    id: "214",
    question: "હ",
    options: ['ha', 'La', 'tha', 'ta'],
    correct: "ha",
  },
  {
    id: "215",
    question: "ળ",
    options: ['La', 'ha', 'tha', 'ta'],
    correct: "La",
  },
  {
    id: "216",
    question: "ત",
    options: ['ta', 'ha', 'La', 'tha'],
    correct: "ta",
  },
  {
    id: "217",
    question: "થ",
    options: ['tha', 'ta', 'ha', 'La'],
    correct: "tha",
  },
  {
    id: "218",
    question: "હ",
    options: ['ha', 'La', 'ta', 'tha'],
    correct: "ha",
  },
  {
    id: "219",
    question: "ળ",
    options: ['La', 'ha', 'ta', 'tha'],
    correct: "La",
  },
  {
    id: "220",
    question: "ત",
    options: ['ta', 'ha', 'La', 'tha'],
    correct: "ta",
  },
  {
    id: "221",
    question: "થ",
    options: ['tha', 'ta', 'La', 'ha'],
    correct: "tha",
  },
  {
    id: "222",
    question: "હ",
    options: ['ha', 'ta', 'tha', 'La'],
    correct: "ha",
  },
  {
    id: "223",
    question: "ળ",
    options: ['La', 'tha', 'ta', 'ha'],
    correct: "La",
  },
  {
    id: "224",
    question: "ત",
    options: ['ta', 'tha', 'ha', 'La'],
    correct: "ta",
  },
  {
    id: "225",
    question: "થ",
    options: ['tha', 'La', 'ha', 'ta'],
    correct: "tha",
  },
  {
    id: "226",
    question: "હ",
    options: ['ha', 'tha', 'ta', 'La'],
    correct: "ha",
  },
  {
    id: "227",
    question: "ળ",
    options: ['La', 'ta', 'tha', 'ha'],
    correct: "La",
  },
  {
    id: "228",
    question: "ત",
    options: ['ta', 'ha', 'tha', 'La'],
    correct: "ta",
  },
  {
    id: "229",
    question: "થ",
    options: ['tha', 'ta', 'La', 'ha'],
    correct: "tha",
  },
  {
    id: "230",
    question: "હ",
    options: ['ha', 'tha', 'ta', 'La'],
    correct: "ha",
  },
  {
    id: "231",
    question: "ળ",
    options: ['La', 'tha', 'ta', 'ha'],
    correct: "La",
  },
  {
    id: "232",
    question: "ત",
    options: ['ta', 'tha', 'La', 'ha'],
    correct: "ta",
  },
  {
    id: "233",
    question: "થ",
    options: ['tha', 'La', 'ha', 'ta'],
    correct: "tha",
  },
  {
    id: "234",
    question: "હ",
    options: ['ha', 'La', 'ta', 'tha'],
    correct: "ha",
  },
  {
    id: "235",
    question: "ળ",
    options: ['La', 'tha', 'ha', 'ta'],
    correct: "La",
  },
  {
    id: "236",
    question: "ત",
    options: ['ta', 'ha', 'La', 'tha'],
    correct: "ta",
  },
  {
    id: "237",
    question: "થ",
    options: ['tha', 'La', 'ta', 'ha'],
    correct: "tha",
  },
  {
    id: "238",
    question: "હ",
    options: ['ha', 'tha', 'La', 'ta'],
    correct: "ha",
  },
  {
    id: "239",
    question: "ળ",
    options: ['La', 'ha', 'tha', 'ta'],
    correct: "La",
  },
  {
    id: "240",
    question: "ત",
    options: ['ta', 'ha', 'tha', 'La'],
    correct: "ta",
  },
  {
    id: "241",
    question: "થ",
    options: ['tha', 'ha', 'ta', 'La'],
    correct: "tha",
  },
  {
    id: "242",
    question: "હ",
    options: ['ha', 'ta', 'tha', 'La'],
    correct: "ha",
  },
  {
    id: "243",
    question: "ળ",
    options: ['La', 'ta', 'tha', 'ha'],
    correct: "La",
  },
  {
    id: "244",
    question: "ત",
    options: ['ta', 'La', 'tha', 'ha'],
    correct: "ta",
  },
  {
    id: "245",
    question: "થ",
    options: ['tha', 'La', 'ha', 'ta'],
    correct: "tha",
  },
  {
    id: "246",
    question: "હ",
    options: ['ha', 'tha', 'ta', 'La'],
    correct: "ha",
  },
  {
    id: "247",
    question: "ળ",
    options: ['La', 'tha', 'ta', 'ha'],
    correct: "La",
  },
  {
    id: "248",
    question: "ત",
    options: ['ta', 'La', 'ha', 'tha'],
    correct: "ta",
  },
  {
    id: "249",
    question: "થ",
    options: ['tha', 'ta', 'ha', 'La'],
    correct: "tha",
  },
  {
    id: "250",
    question: "હ",
    options: ['ha', 'ta', 'La', 'tha'],
    correct: "ha",
  },
  {
    id: "251",
    question: "ળ",
    options: ['La', 'ha', 'tha', 'ta'],
    correct: "La",
  },
  {
    id: "252",
    question: "ત",
    options: ['ta', 'La', 'tha', 'ha'],
    correct: "ta",
  },
  {
    id: "253",
    question: "થ",
    options: ['tha', 'ha', 'La', 'ta'],
    correct: "tha",
  },
  {
    id: "254",
    question: "હ",
    options: ['ha', 'La', 'tha', 'ta'],
    correct: "ha",
  },
  {
    id: "255",
    question: "ળ",
    options: ['La', 'ta', 'ha', 'tha'],
    correct: "La",
  },
  {
    id: "256",
    question: "ત",
    options: ['ta', 'tha', 'ha', 'La'],
    correct: "ta",
  },
  {
    id: "257",
    question: "થ",
    options: ['tha', 'ha', 'La', 'ta'],
    correct: "tha",
  },
  {
    id: "258",
    question: "હ",
    options: ['ha', 'tha', 'ta', 'La'],
    correct: "ha",
  },
  {
    id: "259",
    question: "ળ",
    options: ['La', 'ha', 'tha', 'ta'],
    correct: "La",
  },
  {
    id: "260",
    question: "ત",
    options: ['ta', 'La', 'ha', 'tha'],
    correct: "ta",
  },
  {
    id: "261",
    question: "થ",
    options: ['tha', 'La', 'ha', 'ta'],
    correct: "tha",
  },
  {
    id: "262",
    question: "હ",
    options: ['ha', 'La', 'ta', 'tha'],
    correct: "ha",
  },
  {
    id: "263",
    question: "ળ",
    options: ['La', 'tha', 'ta', 'ha'],
    correct: "La",
  },
  {
    id: "264",
    question: "ત",
    options: ['ta', 'tha', 'ha', 'La'],
    correct: "ta",
  },
  {
    id: "265",
    question: "થ",
    options: ['tha', 'ha', 'La', 'ta'],
    correct: "tha",
  },
  {
    id: "266",
    question: "હ",
    options: ['ha', 'tha', 'La', 'ta'],
    correct: "ha",
  },
  {
    id: "267",
    question: "ળ",
    options: ['La', 'tha', 'ta', 'ha'],
    correct: "La",
  },
  {
    id: "268",
    question: "ત",
    options: ['ta', 'La', 'tha', 'ha'],
    correct: "ta",
  },
  {
    id: "269",
    question: "થ",
    options: ['tha', 'La', 'ta', 'ha'],
    correct: "tha",
  },
  {
    id: "270",
    question: "હ",
    options: ['ha', 'ta', 'La', 'tha'],
    correct: "ha",
  },
  {
    id: "271",
    question: "ળ",
    options: ['La', 'ta', 'tha', 'ha'],
    correct: "La",
  },
  {
    id: "272",
    question: "ત",
    options: ['ta', 'ha', 'tha', 'La'],
    correct: "ta",
  },
  {
    id: "273",
    question: "થ",
    options: ['tha', 'ta', 'La', 'ha'],
    correct: "tha",
  },
  {
    id: "274",
    question: "હ",
    options: ['ha', 'La', 'tha', 'ta'],
    correct: "ha",
  },
  {
    id: "275",
    question: "ળ",
    options: ['La', 'ha', 'ta', 'tha'],
    correct: "La",
  },
  {
    id: "276",
    question: "ત",
    options: ['ta', 'tha', 'La', 'ha'],
    correct: "ta",
  },
  {
    id: "277",
    question: "થ",
    options: ['tha', 'La', 'ta', 'ha'],
    correct: "tha",
  },
  {
    id: "278",
    question: "હ",
    options: ['ha', 'La', 'ta', 'tha'],
    correct: "ha",
  },
  {
    id: "279",
    question: "ળ",
    options: ['La', 'ta', 'ha', 'tha'],
    correct: "La",
  },
  {
    id: "280",
    question: "ત",
    options: ['ta', 'tha', 'ha', 'La'],
    correct: "ta",
  },
  {
    id: "281",
    question: "થ",
    options: ['tha', 'La', 'ta', 'ha'],
    correct: "tha",
  },
  {
    id: "282",
    question: "હ",
    options: ['ha', 'ta', 'tha', 'La'],
    correct: "ha",
  },
  {
    id: "283",
    question: "ળ",
    options: ['La', 'ha', 'tha', 'ta'],
    correct: "La",
  },
  {
    id: "284",
    question: "ત",
    options: ['ta', 'ha', 'tha', 'La'],
    correct: "ta",
  },
  {
    id: "285",
    question: "થ",
    options: ['tha', 'La', 'ta', 'ha'],
    correct: "tha",
  },
  {
    id: "286",
    question: "હ",
    options: ['ha', 'ta', 'La', 'tha'],
    correct: "ha",
  },
  {
    id: "287",
    question: "ળ",
    options: ['La', 'tha', 'ha', 'ta'],
    correct: "La",
  },
  {
    id: "288",
    question: "ત",
    options: ['ta', 'tha', 'ha', 'La'],
    correct: "ta",
  },
  {
    id: "289",
    question: "થ",
    options: ['tha', 'ta', 'La', 'ha'],
    correct: "tha",
  },
  {
    id: "290",
    question: "હ",
    options: ['ha', 'tha', 'La', 'ta'],
    correct: "ha",
  },
  {
    id: "291",
    question: "ળ",
    options: ['La', 'ta', 'ha', 'tha'],
    correct: "La",
  },
  {
    id: "292",
    question: "ત",
    options: ['ta', 'tha', 'La', 'ha'],
    correct: "ta",
  },
  {
    id: "293",
    question: "થ",
    options: ['tha', 'La', 'ta', 'ha'],
    correct: "tha",
  },
  {
    id: "294",
    question: "હ",
    options: ['ha', 'La', 'ta', 'tha'],
    correct: "ha",
  },
  {
    id: "295",
    question: "ળ",
    options: ['La', 'ha', 'tha', 'ta'],
    correct: "La",
  },
  {
    id: "296",
    question: "ત",
    options: ['ta', 'tha', 'ha', 'La'],
    correct: "ta",
  },
  {
    id: "297",
    question: "થ",
    options: ['tha', 'ha', 'ta', 'La'],
    correct: "tha",
  },
  {
    id: "298",
    question: "હ",
    options: ['ha', 'La', 'ta', 'tha'],
    correct: "ha",
  },
  {
    id: "299",
    question: "ળ",
    options: ['La', 'ta', 'tha', 'ha'],
    correct: "La",
  },
  {
    id: "300",
    question: "ત",
    options: ['ta', 'ha', 'tha', 'La'],
    correct: "ta",
  },
  {
    id: "301",
    question: "થ",
    options: ['tha', 'La', 'ha', 'ta'],
    correct: "tha",
  },
  {
    id: "302",
    question: "હ",
    options: ['ha', 'tha', 'La', 'ta'],
    correct: "ha",
  },
  {
    id: "303",
    question: "ળ",
    options: ['La', 'tha', 'ha', 'ta'],
    correct: "La",
  },
  {
    id: "304",
    question: "ત",
    options: ['ta', 'ha', 'tha', 'La'],
    correct: "ta",
  },
  {
    id: "305",
    question: "થ",
    options: ['tha', 'ta', 'ha', 'La'],
    correct: "tha",
  },
  {
    id: "306",
    question: "હ",
    options: ['ha', 'La', 'tha', 'ta'],
    correct: "ha",
  },
  {
    id: "307",
    question: "ળ",
    options: ['La', 'tha', 'ha', 'ta'],
    correct: "La",
  },
  {
    id: "308",
    question: "ત",
    options: ['ta', 'ha', 'tha', 'La'],
    correct: "ta",
  },
  {
    id: "309",
    question: "થ",
    options: ['tha', 'ha', 'ta', 'La'],
    correct: "tha",
  },
  {
    id: "310",
    question: "હ",
    options: ['ha', 'La', 'ta', 'tha'],
    correct: "ha",
  },
  {
    id: "311",
    question: "ળ",
    options: ['La', 'ha', 'ta', 'tha'],
    correct: "La",
  },
  {
    id: "312",
    question: "ત",
    options: ['ta', 'ha', 'La', 'tha'],
    correct: "ta",
  },
  {
    id: "313",
    question: "થ",
    options: ['tha', 'ta', 'ha', 'La'],
    correct: "tha",
  },
  {
    id: "314",
    question: "હ",
    options: ['ha', 'tha', 'La', 'ta'],
    correct: "ha",
  },
  {
    id: "315",
    question: "ળ",
    options: ['La', 'ta', 'tha', 'ha'],
    correct: "La",
  },
  {
    id: "316",
    question: "ત",
    options: ['ta', 'ha', 'tha', 'La'],
    correct: "ta",
  },
  {
    id: "317",
    question: "થ",
    options: ['tha', 'ha', 'ta', 'La'],
    correct: "tha",
  },
  {
    id: "318",
    question: "હ",
    options: ['ha', 'La', 'tha', 'ta'],
    correct: "ha",
  },
  {
    id: "319",
    question: "ળ",
    options: ['La', 'ha', 'ta', 'tha'],
    correct: "La",
  },
  {
    id: "320",
    question: "ત",
    options: ['ta', 'tha', 'La', 'ha'],
    correct: "ta",
  },
  {
    id: "321",
    question: "થ",
    options: ['tha', 'ha', 'La', 'ta'],
    correct: "tha",
  },
  {
    id: "322",
    question: "હ",
    options: ['ha', 'tha', 'La', 'ta'],
    correct: "ha",
  },
  {
    id: "323",
    question: "ળ",
    options: ['La', 'tha', 'ha', 'ta'],
    correct: "La",
  },
  {
    id: "324",
    question: "ત",
    options: ['ta', 'La', 'tha', 'ha'],
    correct: "ta",
  },
  {
    id: "325",
    question: "થ",
    options: ['tha', 'La', 'ha', 'ta'],
    correct: "tha",
  },
  {
    id: "326",
    question: "હ",
    options: ['ha', 'tha', 'ta', 'La'],
    correct: "ha",
  },
  {
    id: "327",
    question: "ળ",
    options: ['La', 'ta', 'ha', 'tha'],
    correct: "La",
  },
  {
    id: "328",
    question: "ત",
    options: ['ta', 'tha', 'La', 'ha'],
    correct: "ta",
  },
  {
    id: "329",
    question: "થ",
    options: ['tha', 'ta', 'La', 'ha'],
    correct: "tha",
  },
  {
    id: "330",
    question: "હ",
    options: ['ha', 'tha', 'ta', 'La'],
    correct: "ha",
  },
  {
    id: "331",
    question: "ળ",
    options: ['La', 'ta', 'ha', 'tha'],
    correct: "La",
  },
  {
    id: "332",
    question: "ત",
    options: ['ta', 'ha', 'tha', 'La'],
    correct: "ta",
  },
  {
    id: "333",
    question: "થ",
    options: ['tha', 'La', 'ha', 'ta'],
    correct: "tha",
  },
  {
    id: "334",
    question: "હ",
    options: ['ha', 'ta', 'La', 'tha'],
    correct: "ha",
  },
  {
    id: "335",
    question: "ળ",
    options: ['La', 'ta', 'tha', 'ha'],
    correct: "La",
  },
  {
    id: "336",
    question: "ત",
    options: ['ta', 'La', 'tha', 'ha'],
    correct: "ta",
  },
  {
    id: "337",
    question: "થ",
    options: ['tha', 'La', 'ha', 'ta'],
    correct: "tha",
  },
  {
    id: "338",
    question: "હ",
    options: ['ha', 'ta', 'tha', 'La'],
    correct: "ha",
  },
  {
    id: "339",
    question: "ળ",
    options: ['La', 'tha', 'ha', 'ta'],
    correct: "La",
  },
  {
    id: "340",
    question: "ત",
    options: ['ta', 'tha', 'ha', 'La'],
    correct: "ta",
  },
  {
    id: "341",
    question: "થ",
    options: ['tha', 'ha', 'La', 'ta'],
    correct: "tha",
  },
  {
    id: "342",
    question: "હ",
    options: ['ha', 'La', 'tha', 'ta'],
    correct: "ha",
  },
  {
    id: "343",
    question: "ળ",
    options: ['La', 'ta', 'tha', 'ha'],
    correct: "La",
  },
  {
    id: "344",
    question: "ત",
    options: ['ta', 'La', 'ha', 'tha'],
    correct: "ta",
  },
  {
    id: "345",
    question: "થ",
    options: ['tha', 'ta', 'La', 'ha'],
    correct: "tha",
  },
  {
    id: "346",
    question: "હ",
    options: ['ha', 'La', 'tha', 'ta'],
    correct: "ha",
  },
  {
    id: "347",
    question: "ળ",
    options: ['La', 'ta', 'ha', 'tha'],
    correct: "La",
  },
  {
    id: "348",
    question: "ત",
    options: ['ta', 'La', 'tha', 'ha'],
    correct: "ta",
  },
  {
    id: "349",
    question: "થ",
    options: ['tha', 'ha', 'La', 'ta'],
    correct: "tha",
  },
  {
    id: "350",
    question: "હ",
    options: ['ha', 'tha', 'La', 'ta'],
    correct: "ha",
  },
  {
    id: "351",
    question: "ળ",
    options: ['La', 'ta', 'tha', 'ha'],
    correct: "La",
  },
  {
    id: "352",
    question: "ત",
    options: ['ta', 'ha', 'La', 'tha'],
    correct: "ta",
  },
  {
    id: "353",
    question: "થ",
    options: ['tha', 'La', 'ta', 'ha'],
    correct: "tha",
  },
  {
    id: "354",
    question: "હ",
    options: ['ha', 'La', 'ta', 'tha'],
    correct: "ha",
  },
  {
    id: "355",
    question: "ળ",
    options: ['La', 'ha', 'tha', 'ta'],
    correct: "La",
  },
  {
    id: "356",
    question: "ત",
    options: ['ta', 'La', 'ha', 'tha'],
    correct: "ta",
  },
  {
    id: "357",
    question: "થ",
    options: ['tha', 'La', 'ha', 'ta'],
    correct: "tha",
  },
  {
    id: "358",
    question: "હ",
    options: ['ha', 'tha', 'La', 'ta'],
    correct: "ha",
  },
  {
    id: "359",
    question: "ળ",
    options: ['La', 'ta', 'ha', 'tha'],
    correct: "La",
  },
  {
    id: "360",
    question: "ત",
    options: ['ta', 'La', 'tha', 'ha'],
    correct: "ta",
  },
  {
    id: "361",
    question: "થ",
    options: ['tha', 'ta', 'ha', 'La'],
    correct: "tha",
  },
  {
    id: "362",
    question: "હ",
    options: ['ha', 'ta', 'La', 'tha'],
    correct: "ha",
  },
  {
    id: "363",
    question: "ળ",
    options: ['La', 'tha', 'ta', 'ha'],
    correct: "La",
  },
  {
    id: "364",
    question: "ત",
    options: ['ta', 'ha', 'tha', 'La'],
    correct: "ta",
  },
  {
    id: "365",
    question: "થ",
    options: ['tha', 'ha', 'La', 'ta'],
    correct: "tha",
  },
  {
    id: "366",
    question: "હ",
    options: ['ha', 'ta', 'tha', 'La'],
    correct: "ha",
  },
  {
    id: "367",
    question: "ળ",
    options: ['La', 'ha', 'ta', 'tha'],
    correct: "La",
  },
  {
    id: "368",
    question: "ત",
    options: ['ta', 'ha', 'tha', 'La'],
    correct: "ta",
  },
  {
    id: "369",
    question: "થ",
    options: ['tha', 'ha', 'La', 'ta'],
    correct: "tha",
  },
  {
    id: "370",
    question: "હ",
    options: ['ha', 'ta', 'tha', 'La'],
    correct: "ha",
  },
  {
    id: "371",
    question: "ળ",
    options: ['La', 'tha', 'ha', 'ta'],
    correct: "La",
  },
  {
    id: "372",
    question: "ત",
    options: ['ta', 'ha', 'La', 'tha'],
    correct: "ta",
  },
  {
    id: "373",
    question: "થ",
    options: ['tha', 'ta', 'ha', 'La'],
    correct: "tha",
  },
  {
    id: "374",
    question: "હ",
    options: ['ha', 'ta', 'La', 'tha'],
    correct: "ha",
  },
  {
    id: "375",
    question: "ળ",
    options: ['La', 'ha', 'ta', 'tha'],
    correct: "La",
  },
  {
    id: "376",
    question: "ત",
    options: ['ta', 'tha', 'ha', 'La'],
    correct: "ta",
  },
  {
    id: "377",
    question: "થ",
    options: ['tha', 'ta', 'ha', 'La'],
    correct: "tha",
  },
  {
    id: "378",
    question: "હ",
    options: ['ha', 'ta', 'tha', 'La'],
    correct: "ha",
  },
  {
    id: "379",
    question: "ળ",
    options: ['La', 'ha', 'ta', 'tha'],
    correct: "La",
  },
  {
    id: "380",
    question: "ત",
    options: ['ta', 'ha', 'tha', 'La'],
    correct: "ta",
  },
  {
    id: "381",
    question: "થ",
    options: ['tha', 'La', 'ta', 'ha'],
    correct: "tha",
  },
  {
    id: "382",
    question: "હ",
    options: ['ha', 'La', 'ta', 'tha'],
    correct: "ha",
  },
  {
    id: "383",
    question: "ળ",
    options: ['La', 'ta', 'ha', 'tha'],
    correct: "La",
  },
  {
    id: "384",
    question: "ત",
    options: ['ta', 'tha', 'ha', 'La'],
    correct: "ta",
  },
  {
    id: "385",
    question: "થ",
    options: ['tha', 'ha', 'ta', 'La'],
    correct: "tha",
  },
  {
    id: "386",
    question: "હ",
    options: ['ha', 'ta', 'La', 'tha'],
    correct: "ha",
  },
  {
    id: "387",
    question: "ળ",
    options: ['La', 'tha', 'ta', 'ha'],
    correct: "La",
  },
  {
    id: "388",
    question: "ત",
    options: ['ta', 'ha', 'tha', 'La'],
    correct: "ta",
  },
  {
    id: "389",
    question: "થ",
    options: ['tha', 'La', 'ta', 'ha'],
    correct: "tha",
  },
  {
    id: "390",
    question: "હ",
    options: ['ha', 'tha', 'ta', 'La'],
    correct: "ha",
  },
  {
    id: "391",
    question: "ળ",
    options: ['La', 'ha', 'ta', 'tha'],
    correct: "La",
  },
  {
    id: "392",
    question: "ત",
    options: ['ta', 'tha', 'La', 'ha'],
    correct: "ta",
  },
  {
    id: "393",
    question: "થ",
    options: ['tha', 'ta', 'ha', 'La'],
    correct: "tha",
  },
  {
    id: "394",
    question: "હ",
    options: ['ha', 'La', 'tha', 'ta'],
    correct: "ha",
  },
  {
    id: "395",
    question: "ળ",
    options: ['La', 'tha', 'ha', 'ta'],
    correct: "La",
  },
  {
    id: "396",
    question: "ત",
    options: ['ta', 'La', 'ha', 'tha'],
    correct: "ta",
  },
  {
    id: "397",
    question: "થ",
    options: ['tha', 'ha', 'La', 'ta'],
    correct: "tha",
  },
  {
    id: "398",
    question: "હ",
    options: ['ha', 'ta', 'tha', 'La'],
    correct: "ha",
  },
  {
    id: "399",
    question: "ળ",
    options: ['La', 'ha', 'tha', 'ta'],
    correct: "La",
  },
];
