const quizArray_level1 = [
  {
    id: "0",
    question: "અ",
    options: ['a', 'aa', 'e', 'o'],
    correct: "a",
  },
  {
    id: "1",
    question: "આ",
    options: ['aa', 'a', 'u', 'ai'],
    correct: "aa",
  },
  {
    id: "2",
    question: "ઇ",
    options: ['i', 'ai', 'aa', 'ii'],
    correct: "i",
  },
  {
    id: "3",
    question: "ઈ",
    options: ['ii', 'aa', 'u', 'a'],
    correct: "ii",
  },
  {
    id: "4",
    question: "ઉ",
    options: ['u', 'ii', 'i', 'uu'],
    correct: "u",
  },
  {
    id: "5",
    question: "ઊ",
    options: ['uu', 'ai', 'e', 'o'],
    correct: "uu",
  },
  {
    id: "6",
    question: "એ",
    options: ['e', 'uu', 'ai', 'a'],
    correct: "e",
  },
  {
    id: "7",
    question: "ઐ",
    options: ['ai', 'uu', 'u', 'ii'],
    correct: "ai",
  },
  {
    id: "8",
    question: "ઓ",
    options: ['o', 'au', 'ii', 'aa'],
    correct: "o",
  },
  {
    id: "9",
    question: "ઔ",
    options: ['au', 'i', 'uu', 'ai'],
    correct: "au",
  },
  {
    id: "10",
    question: "અ",
    options: ['a', 'u', 'uu', 'i'],
    correct: "a",
  },
  {
    id: "11",
    question: "આ",
    options: ['aa', 'ai', 'a', 'e'],
    correct: "aa",
  },
  {
    id: "12",
    question: "ઇ",
    options: ['i', 'e', 'uu', 'u'],
    correct: "i",
  },
  {
    id: "13",
    question: "ઈ",
    options: ['ii', 'au', 'uu', 'i'],
    correct: "ii",
  },
  {
    id: "14",
    question: "ઉ",
    options: ['u', 'aa', 'a', 'au'],
    correct: "u",
  },
  {
    id: "15",
    question: "ઊ",
    options: ['uu', 'au', 'ai', 'o'],
    correct: "uu",
  },
  {
    id: "16",
    question: "એ",
    options: ['e', 'i', 'a', 'u'],
    correct: "e",
  },
  {
    id: "17",
    question: "ઐ",
    options: ['ai', 'o', 'u', 'i'],
    correct: "ai",
  },
  {
    id: "18",
    question: "ઓ",
    options: ['o', 'au', 'u', 'i'],
    correct: "o",
  },
  {
    id: "19",
    question: "ઔ",
    options: ['au', 'uu', 'i', 'ii'],
    correct: "au",
  },
  {
    id: "20",
    question: "અ",
    options: ['a', 'ai', 'au', 'i'],
    correct: "a",
  },
  {
    id: "21",
    question: "આ",
    options: ['aa', 'e', 'ii', 'o'],
    correct: "aa",
  },
  {
    id: "22",
    question: "ઇ",
    options: ['i', 'au', 'uu', 'a'],
    correct: "i",
  },
  {
    id: "23",
    question: "ઈ",
    options: ['ii', 'ai', 'uu', 'e'],
    correct: "ii",
  },
  {
    id: "24",
    question: "ઉ",
    options: ['u', 'ii', 'au', 'o'],
    correct: "u",
  },
  {
    id: "25",
    question: "ઊ",
    options: ['uu', 'u', 'o', 'au'],
    correct: "uu",
  },
  {
    id: "26",
    question: "એ",
    options: ['e', 'a', 'aa', 'i'],
    correct: "e",
  },
  {
    id: "27",
    question: "ઐ",
    options: ['ai', 'e', 'uu', 'aa'],
    correct: "ai",
  },
  {
    id: "28",
    question: "ઓ",
    options: ['o', 'aa', 'uu', 'ai'],
    correct: "o",
  },
  {
    id: "29",
    question: "ઔ",
    options: ['au', 'a', 'ai', 'e'],
    correct: "au",
  },
  {
    id: "30",
    question: "અ",
    options: ['a', 'u', 'o', 'ai'],
    correct: "a",
  },
  {
    id: "31",
    question: "આ",
    options: ['aa', 'au', 'ii', 'a'],
    correct: "aa",
  },
  {
    id: "32",
    question: "ઇ",
    options: ['i', 'a', 'au', 'o'],
    correct: "i",
  },
  {
    id: "33",
    question: "ઈ",
    options: ['ii', 'uu', 'u', 'au'],
    correct: "ii",
  },
  {
    id: "34",
    question: "ઉ",
    options: ['u', 'au', 'a', 'aa'],
    correct: "u",
  },
  {
    id: "35",
    question: "ઊ",
    options: ['uu', 'a', 'e', 'ai'],
    correct: "uu",
  },
  {
    id: "36",
    question: "એ",
    options: ['e', 'uu', 'au', 'o'],
    correct: "e",
  },
  {
    id: "37",
    question: "ઐ",
    options: ['ai', 'au', 'aa', 'e'],
    correct: "ai",
  },
  {
    id: "38",
    question: "ઓ",
    options: ['o', 'uu', 'i', 'ii'],
    correct: "o",
  },
  {
    id: "39",
    question: "ઔ",
    options: ['au', 'uu', 'ii', 'u'],
    correct: "au",
  },
  {
    id: "40",
    question: "અ",
    options: ['a', 'au', 'u', 'aa'],
    correct: "a",
  },
  {
    id: "41",
    question: "આ",
    options: ['aa', 'uu', 'o', 'ai'],
    correct: "aa",
  },
  {
    id: "42",
    question: "ઇ",
    options: ['i', 'ii', 'aa', 'e'],
    correct: "i",
  },
  {
    id: "43",
    question: "ઈ",
    options: ['ii', 'uu', 'ai', 'au'],
    correct: "ii",
  },
  {
    id: "44",
    question: "ઉ",
    options: ['u', 'e', 'aa', 'uu'],
    correct: "u",
  },
  {
    id: "45",
    question: "ઊ",
    options: ['uu', 'ai', 'o', 'u'],
    correct: "uu",
  },
  {
    id: "46",
    question: "એ",
    options: ['e', 'uu', 'i', 'u'],
    correct: "e",
  },
  {
    id: "47",
    question: "ઐ",
    options: ['ai', 'a', 'uu', 'ii'],
    correct: "ai",
  },
  {
    id: "48",
    question: "ઓ",
    options: ['o', 'u', 'uu', 'ai'],
    correct: "o",
  },
  {
    id: "49",
    question: "ઔ",
    options: ['au', 'ai', 'uu', 'e'],
    correct: "au",
  },
  {
    id: "50",
    question: "અ",
    options: ['a', 'o', 'au', 'aa'],
    correct: "a",
  },
  {
    id: "51",
    question: "આ",
    options: ['aa', 'i', 'u', 'ii'],
    correct: "aa",
  },
  {
    id: "52",
    question: "ઇ",
    options: ['i', 'a', 'uu', 'o'],
    correct: "i",
  },
  {
    id: "53",
    question: "ઈ",
    options: ['ii', 'ai', 'o', 'i'],
    correct: "ii",
  },
  {
    id: "54",
    question: "ઉ",
    options: ['u', 'uu', 'ii', 'aa'],
    correct: "u",
  },
  {
    id: "55",
    question: "ઊ",
    options: ['uu', 'a', 'e', 'aa'],
    correct: "uu",
  },
  {
    id: "56",
    question: "એ",
    options: ['e', 'a', 'uu', 'i'],
    correct: "e",
  },
  {
    id: "57",
    question: "ઐ",
    options: ['ai', 'i', 'uu', 'a'],
    correct: "ai",
  },
  {
    id: "58",
    question: "ઓ",
    options: ['o', 'u', 'ii', 'uu'],
    correct: "o",
  },
  {
    id: "59",
    question: "ઔ",
    options: ['au', 'e', 'i', 'o'],
    correct: "au",
  },
  {
    id: "60",
    question: "અ",
    options: ['a', 'ai', 'i', 'au'],
    correct: "a",
  },
  {
    id: "61",
    question: "આ",
    options: ['aa', 'ii', 'u', 'uu'],
    correct: "aa",
  },
  {
    id: "62",
    question: "ઇ",
    options: ['i', 'o', 'e', 'ai'],
    correct: "i",
  },
  {
    id: "63",
    question: "ઈ",
    options: ['ii', 'a', 'uu', 'ai'],
    correct: "ii",
  },
  {
    id: "64",
    question: "ઉ",
    options: ['u', 'ii', 'aa', 'ai'],
    correct: "u",
  },
  {
    id: "65",
    question: "ઊ",
    options: ['uu', 'i', 'o', 'u'],
    correct: "uu",
  },
  {
    id: "66",
    question: "એ",
    options: ['e', 'o', 'aa', 'uu'],
    correct: "e",
  },
  {
    id: "67",
    question: "ઐ",
    options: ['ai', 'aa', 'u', 'ii'],
    correct: "ai",
  },
  {
    id: "68",
    question: "ઓ",
    options: ['o', 'ai', 'ii', 'e'],
    correct: "o",
  },
  {
    id: "69",
    question: "ઔ",
    options: ['au', 'aa', 'u', 'a'],
    correct: "au",
  },
  {
    id: "70",
    question: "અ",
    options: ['a', 'u', 'ii', 'uu'],
    correct: "a",
  },
  {
    id: "71",
    question: "આ",
    options: ['aa', 'ai', 'uu', 'u'],
    correct: "aa",
  },
  {
    id: "72",
    question: "ઇ",
    options: ['i', 'au', 'o', 'a'],
    correct: "i",
  },
  {
    id: "73",
    question: "ઈ",
    options: ['ii', 'a', 'ai', 'u'],
    correct: "ii",
  },
  {
    id: "74",
    question: "ઉ",
    options: ['u', 'au', 'e', 'i'],
    correct: "u",
  },
  {
    id: "75",
    question: "ઊ",
    options: ['uu', 'u', 'au', 'i'],
    correct: "uu",
  },
  {
    id: "76",
    question: "એ",
    options: ['e', 'o', 'a', 'uu'],
    correct: "e",
  },
  {
    id: "77",
    question: "ઐ",
    options: ['ai', 'o', 'u', 'au'],
    correct: "ai",
  },
  {
    id: "78",
    question: "ઓ",
    options: ['o', 'ii', 'i', 'ai'],
    correct: "o",
  },
  {
    id: "79",
    question: "ઔ",
    options: ['au', 'uu', 'e', 'a'],
    correct: "au",
  },
  {
    id: "80",
    question: "અ",
    options: ['a', 'e', 'uu', 'ai'],
    correct: "a",
  },
  {
    id: "81",
    question: "આ",
    options: ['aa', 'ii', 'uu', 'i'],
    correct: "aa",
  },
  {
    id: "82",
    question: "ઇ",
    options: ['i', 'uu', 'a', 'e'],
    correct: "i",
  },
  {
    id: "83",
    question: "ઈ",
    options: ['ii', 'o', 'au', 'a'],
    correct: "ii",
  },
  {
    id: "84",
    question: "ઉ",
    options: ['u', 'a', 'e', 'aa'],
    correct: "u",
  },
  {
    id: "85",
    question: "ઊ",
    options: ['uu', 'o', 'i', 'a'],
    correct: "uu",
  },
  {
    id: "86",
    question: "એ",
    options: ['e', 'aa', 'ii', 'au'],
    correct: "e",
  },
  {
    id: "87",
    question: "ઐ",
    options: ['ai', 'aa', 'u', 'i'],
    correct: "ai",
  },
  {
    id: "88",
    question: "ઓ",
    options: ['o', 'a', 'au', 'ai'],
    correct: "o",
  },
  {
    id: "89",
    question: "ઔ",
    options: ['au', 'o', 'u', 'e'],
    correct: "au",
  },
  {
    id: "90",
    question: "અ",
    options: ['a', 'aa', 'i', 'au'],
    correct: "a",
  },
  {
    id: "91",
    question: "આ",
    options: ['aa', 'u', 'au', 'e'],
    correct: "aa",
  },
  {
    id: "92",
    question: "ઇ",
    options: ['i', 'o', 'au', 'ai'],
    correct: "i",
  },
  {
    id: "93",
    question: "ઈ",
    options: ['ii', 'u', 'i', 'a'],
    correct: "ii",
  },
  {
    id: "94",
    question: "ઉ",
    options: ['u', 'uu', 'o', 'aa'],
    correct: "u",
  },
  {
    id: "95",
    question: "ઊ",
    options: ['uu', 'u', 'au', 'ai'],
    correct: "uu",
  },
  {
    id: "96",
    question: "એ",
    options: ['e', 'uu', 'au', 'a'],
    correct: "e",
  },
  {
    id: "97",
    question: "ઐ",
    options: ['ai', 'a', 'e', 'aa'],
    correct: "ai",
  },
  {
    id: "98",
    question: "ઓ",
    options: ['o', 'e', 'a', 'aa'],
    correct: "o",
  },
  {
    id: "99",
    question: "ઔ",
    options: ['au', 'ii', 'u', 'a'],
    correct: "au",
  },
  {
    id: "100",
    question: "અ",
    options: ['a', 'ii', 'u', 'e'],
    correct: "a",
  },
  {
    id: "101",
    question: "આ",
    options: ['aa', 'uu', 'au', 'o'],
    correct: "aa",
  },
  {
    id: "102",
    question: "ઇ",
    options: ['i', 'ai', 'u', 'a'],
    correct: "i",
  },
  {
    id: "103",
    question: "ઈ",
    options: ['ii', 'aa', 'e', 'o'],
    correct: "ii",
  },
  {
    id: "104",
    question: "ઉ",
    options: ['u', 'e', 'aa', 'ii'],
    correct: "u",
  },
  {
    id: "105",
    question: "ઊ",
    options: ['uu', 'au', 'ii', 'a'],
    correct: "uu",
  },
  {
    id: "106",
    question: "એ",
    options: ['e', 'uu', 'au', 'i'],
    correct: "e",
  },
  {
    id: "107",
    question: "ઐ",
    options: ['ai', 'i', 'uu', 'ii'],
    correct: "ai",
  },
  {
    id: "108",
    question: "ઓ",
    options: ['o', 'aa', 'e', 'a'],
    correct: "o",
  },
  {
    id: "109",
    question: "ઔ",
    options: ['au', 'u', 'aa', 'ii'],
    correct: "au",
  },
  {
    id: "110",
    question: "અ",
    options: ['a', 'ai', 'u', 'au'],
    correct: "a",
  },
  {
    id: "111",
    question: "આ",
    options: ['aa', 'ai', 'o', 'e'],
    correct: "aa",
  },
  {
    id: "112",
    question: "ઇ",
    options: ['i', 'uu', 'a', 'u'],
    correct: "i",
  },
  {
    id: "113",
    question: "ઈ",
    options: ['ii', 'e', 'aa', 'uu'],
    correct: "ii",
  },
  {
    id: "114",
    question: "ઉ",
    options: ['u', 'ii', 'e', 'i'],
    correct: "u",
  },
  {
    id: "115",
    question: "ઊ",
    options: ['uu', 'aa', 'i', 'u'],
    correct: "uu",
  },
  {
    id: "116",
    question: "એ",
    options: ['e', 'ii', 'aa', 'o'],
    correct: "e",
  },
  {
    id: "117",
    question: "ઐ",
    options: ['ai', 'ii', 'a', 'au'],
    correct: "ai",
  },
  {
    id: "118",
    question: "ઓ",
    options: ['o', 'i', 'aa', 'uu'],
    correct: "o",
  },
  {
    id: "119",
    question: "ઔ",
    options: ['au', 'aa', 'o', 'i'],
    correct: "au",
  },
  {
    id: "120",
    question: "અ",
    options: ['a', 'aa', 'i', 'ai'],
    correct: "a",
  },
  {
    id: "121",
    question: "આ",
    options: ['aa', 'o', 'e', 'a'],
    correct: "aa",
  },
  {
    id: "122",
    question: "ઇ",
    options: ['i', 'aa', 'u', 'au'],
    correct: "i",
  },
  {
    id: "123",
    question: "ઈ",
    options: ['ii', 'e', 'o', 'au'],
    correct: "ii",
  },
  {
    id: "124",
    question: "ઉ",
    options: ['u', 'ii', 'e', 'uu'],
    correct: "u",
  },
  {
    id: "125",
    question: "ઊ",
    options: ['uu', 'o', 'ii', 'a'],
    correct: "uu",
  },
  {
    id: "126",
    question: "એ",
    options: ['e', 'u', 'ai', 'uu'],
    correct: "e",
  },
  {
    id: "127",
    question: "ઐ",
    options: ['ai', 'au', 'e', 'ii'],
    correct: "ai",
  },
  {
    id: "128",
    question: "ઓ",
    options: ['o', 'e', 'i', 'ii'],
    correct: "o",
  },
  {
    id: "129",
    question: "ઔ",
    options: ['au', 'ai', 'a', 'i'],
    correct: "au",
  },
  {
    id: "130",
    question: "અ",
    options: ['a', 'aa', 'o', 'uu'],
    correct: "a",
  },
  {
    id: "131",
    question: "આ",
    options: ['aa', 'ii', 'i', 'au'],
    correct: "aa",
  },
  {
    id: "132",
    question: "ઇ",
    options: ['i', 'e', 'a', 'uu'],
    correct: "i",
  },
  {
    id: "133",
    question: "ઈ",
    options: ['ii', 'u', 'ai', 'i'],
    correct: "ii",
  },
  {
    id: "134",
    question: "ઉ",
    options: ['u', 'i', 'uu', 'ii'],
    correct: "u",
  },
  {
    id: "135",
    question: "ઊ",
    options: ['uu', 'a', 'ii', 'ai'],
    correct: "uu",
  },
  {
    id: "136",
    question: "એ",
    options: ['e', 'au', 'aa', 'u'],
    correct: "e",
  },
  {
    id: "137",
    question: "ઐ",
    options: ['ai', 'aa', 'i', 'uu'],
    correct: "ai",
  },
  {
    id: "138",
    question: "ઓ",
    options: ['o', 'au', 'i', 'uu'],
    correct: "o",
  },
  {
    id: "139",
    question: "ઔ",
    options: ['au', 'aa', 'u', 'a'],
    correct: "au",
  },
  {
    id: "140",
    question: "અ",
    options: ['a', 'o', 'aa', 'ii'],
    correct: "a",
  },
  {
    id: "141",
    question: "આ",
    options: ['aa', 'u', 'au', 'ai'],
    correct: "aa",
  },
  {
    id: "142",
    question: "ઇ",
    options: ['i', 'ii', 'au', 'o'],
    correct: "i",
  },
  {
    id: "143",
    question: "ઈ",
    options: ['ii', 'au', 'e', 'i'],
    correct: "ii",
  },
  {
    id: "144",
    question: "ઉ",
    options: ['u', 'uu', 'aa', 'i'],
    correct: "u",
  },
  {
    id: "145",
    question: "ઊ",
    options: ['uu', 'au', 'ii', 'e'],
    correct: "uu",
  },
  {
    id: "146",
    question: "એ",
    options: ['e', 'i', 'uu', 'ii'],
    correct: "e",
  },
  {
    id: "147",
    question: "ઐ",
    options: ['ai', 'au', 'a', 'aa'],
    correct: "ai",
  },
  {
    id: "148",
    question: "ઓ",
    options: ['o', 'ii', 'a', 'ai'],
    correct: "o",
  },
  {
    id: "149",
    question: "ઔ",
    options: ['au', 'e', 'i', 'aa'],
    correct: "au",
  },
  {
    id: "150",
    question: "અ",
    options: ['a', 'aa', 'i', 'au'],
    correct: "a",
  },
  {
    id: "151",
    question: "આ",
    options: ['aa', 'a', 'ii', 'e'],
    correct: "aa",
  },
  {
    id: "152",
    question: "ઇ",
    options: ['i', 'u', 'ai', 'o'],
    correct: "i",
  },
  {
    id: "153",
    question: "ઈ",
    options: ['ii', 'au', 'uu', 'ai'],
    correct: "ii",
  },
  {
    id: "154",
    question: "ઉ",
    options: ['u', 'o', 'uu', 'a'],
    correct: "u",
  },
  {
    id: "155",
    question: "ઊ",
    options: ['uu', 'u', 'i', 'e'],
    correct: "uu",
  },
  {
    id: "156",
    question: "એ",
    options: ['e', 'o', 'aa', 'u'],
    correct: "e",
  },
  {
    id: "157",
    question: "ઐ",
    options: ['ai', 'i', 'e', 'ii'],
    correct: "ai",
  },
  {
    id: "158",
    question: "ઓ",
    options: ['o', 'u', 'aa', 'a'],
    correct: "o",
  },
  {
    id: "159",
    question: "ઔ",
    options: ['au', 'o', 'aa', 'i'],
    correct: "au",
  },
  {
    id: "160",
    question: "અ",
    options: ['a', 'ii', 'au', 'o'],
    correct: "a",
  },
  {
    id: "161",
    question: "આ",
    options: ['aa', 'au', 'u', 'a'],
    correct: "aa",
  },
  {
    id: "162",
    question: "ઇ",
    options: ['i', 'e', 'au', 'aa'],
    correct: "i",
  },
  {
    id: "163",
    question: "ઈ",
    options: ['ii', 'e', 'au', 'a'],
    correct: "ii",
  },
  {
    id: "164",
    question: "ઉ",
    options: ['u', 'e', 'ii', 'uu'],
    correct: "u",
  },
  {
    id: "165",
    question: "ઊ",
    options: ['uu', 'i', 'aa', 'ai'],
    correct: "uu",
  },
  {
    id: "166",
    question: "એ",
    options: ['e', 'a', 'aa', 'ai'],
    correct: "e",
  },
  {
    id: "167",
    question: "ઐ",
    options: ['ai', 'au', 'a', 'aa'],
    correct: "ai",
  },
  {
    id: "168",
    question: "ઓ",
    options: ['o', 'ai', 'uu', 'i'],
    correct: "o",
  },
  {
    id: "169",
    question: "ઔ",
    options: ['au', 'aa', 'ai', 'ii'],
    correct: "au",
  },
  {
    id: "170",
    question: "અ",
    options: ['a', 'i', 'o', 'aa'],
    correct: "a",
  },
  {
    id: "171",
    question: "આ",
    options: ['aa', 'a', 'au', 'i'],
    correct: "aa",
  },
  {
    id: "172",
    question: "ઇ",
    options: ['i', 'e', 'ii', 'au'],
    correct: "i",
  },
  {
    id: "173",
    question: "ઈ",
    options: ['ii', 'i', 'ai', 'e'],
    correct: "ii",
  },
  {
    id: "174",
    question: "ઉ",
    options: ['u', 'ii', 'e', 'o'],
    correct: "u",
  },
  {
    id: "175",
    question: "ઊ",
    options: ['uu', 'ai', 'au', 'u'],
    correct: "uu",
  },
  {
    id: "176",
    question: "એ",
    options: ['e', 'ii', 'a', 'uu'],
    correct: "e",
  },
  {
    id: "177",
    question: "ઐ",
    options: ['ai', 'aa', 'a', 'au'],
    correct: "ai",
  },
  {
    id: "178",
    question: "ઓ",
    options: ['o', 'i', 'au', 'aa'],
    correct: "o",
  },
  {
    id: "179",
    question: "ઔ",
    options: ['au', 'a', 'uu', 'o'],
    correct: "au",
  },
  {
    id: "180",
    question: "અ",
    options: ['a', 'uu', 'o', 'u'],
    correct: "a",
  },
  {
    id: "181",
    question: "આ",
    options: ['aa', 'o', 'i', 'u'],
    correct: "aa",
  },
  {
    id: "182",
    question: "ઇ",
    options: ['i', 'e', 'aa', 'ai'],
    correct: "i",
  },
  {
    id: "183",
    question: "ઈ",
    options: ['ii', 'o', 'e', 'u'],
    correct: "ii",
  },
  {
    id: "184",
    question: "ઉ",
    options: ['u', 'e', 'o', 'uu'],
    correct: "u",
  },
  {
    id: "185",
    question: "ઊ",
    options: ['uu', 'aa', 'i', 'ai'],
    correct: "uu",
  },
  {
    id: "186",
    question: "એ",
    options: ['e', 'ii', 'a', 'aa'],
    correct: "e",
  },
  {
    id: "187",
    question: "ઐ",
    options: ['ai', 'o', 'au', 'uu'],
    correct: "ai",
  },
  {
    id: "188",
    question: "ઓ",
    options: ['o', 'ii', 'a', 'uu'],
    correct: "o",
  },
  {
    id: "189",
    question: "ઔ",
    options: ['au', 'i', 'aa', 'o'],
    correct: "au",
  },
  {
    id: "190",
    question: "અ",
    options: ['a', 'o', 'aa', 'u'],
    correct: "a",
  },
  {
    id: "191",
    question: "આ",
    options: ['aa', 'ii', 'i', 'e'],
    correct: "aa",
  },
  {
    id: "192",
    question: "ઇ",
    options: ['i', 'uu', 'o', 'a'],
    correct: "i",
  },
  {
    id: "193",
    question: "ઈ",
    options: ['ii', 'u', 'aa', 'e'],
    correct: "ii",
  },
  {
    id: "194",
    question: "ઉ",
    options: ['u', 'a', 'ii', 'i'],
    correct: "u",
  },
  {
    id: "195",
    question: "ઊ",
    options: ['uu', 'ii', 'e', 'aa'],
    correct: "uu",
  },
  {
    id: "196",
    question: "એ",
    options: ['e', 'i', 'o', 'u'],
    correct: "e",
  },
  {
    id: "197",
    question: "ઐ",
    options: ['ai', 'e', 'o', 'u'],
    correct: "ai",
  },
  {
    id: "198",
    question: "ઓ",
    options: ['o', 'e', 'ai', 'u'],
    correct: "o",
  },
  {
    id: "199",
    question: "ઔ",
    options: ['au', 'ai', 'ii', 'e'],
    correct: "au",
  },
  {
    id: "200",
    question: "અ",
    options: ['a', 'u', 'o', 'uu'],
    correct: "a",
  },
  {
    id: "201",
    question: "આ",
    options: ['aa', 'ai', 'a', 'ii'],
    correct: "aa",
  },
  {
    id: "202",
    question: "ઇ",
    options: ['i', 'e', 'ai', 'aa'],
    correct: "i",
  },
  {
    id: "203",
    question: "ઈ",
    options: ['ii', 'aa', 'uu', 'o'],
    correct: "ii",
  },
  {
    id: "204",
    question: "ઉ",
    options: ['u', 'ai', 'a', 'o'],
    correct: "u",
  },
  {
    id: "205",
    question: "ઊ",
    options: ['uu', 'o', 'e', 'aa'],
    correct: "uu",
  },
  {
    id: "206",
    question: "એ",
    options: ['e', 'i', 'ii', 'uu'],
    correct: "e",
  },
  {
    id: "207",
    question: "ઐ",
    options: ['ai', 'ii', 'a', 'i'],
    correct: "ai",
  },
  {
    id: "208",
    question: "ઓ",
    options: ['o', 'aa', 'i', 'ii'],
    correct: "o",
  },
  {
    id: "209",
    question: "ઔ",
    options: ['au', 'o', 'u', 'e'],
    correct: "au",
  },
  {
    id: "210",
    question: "અ",
    options: ['a', 'uu', 'au', 'ii'],
    correct: "a",
  },
  {
    id: "211",
    question: "આ",
    options: ['aa', 'o', 'au', 'uu'],
    correct: "aa",
  },
  {
    id: "212",
    question: "ઇ",
    options: ['i', 'aa', 'au', 'a'],
    correct: "i",
  },
  {
    id: "213",
    question: "ઈ",
    options: ['ii', 'aa', 'uu', 'ai'],
    correct: "ii",
  },
  {
    id: "214",
    question: "ઉ",
    options: ['u', 'uu', 'o', 'i'],
    correct: "u",
  },
  {
    id: "215",
    question: "ઊ",
    options: ['uu', 'ii', 'u', 'o'],
    correct: "uu",
  },
  {
    id: "216",
    question: "એ",
    options: ['e', 'i', 'uu', 'ii'],
    correct: "e",
  },
  {
    id: "217",
    question: "ઐ",
    options: ['ai', 'i', 'e', 'au'],
    correct: "ai",
  },
  {
    id: "218",
    question: "ઓ",
    options: ['o', 'uu', 'e', 'ii'],
    correct: "o",
  },
  {
    id: "219",
    question: "ઔ",
    options: ['au', 'e', 'aa', 'u'],
    correct: "au",
  },
  {
    id: "220",
    question: "અ",
    options: ['a', 'o', 'au', 'i'],
    correct: "a",
  },
  {
    id: "221",
    question: "આ",
    options: ['aa', 'e', 'u', 'a'],
    correct: "aa",
  },
  {
    id: "222",
    question: "ઇ",
    options: ['i', 'uu', 'aa', 'o'],
    correct: "i",
  },
  {
    id: "223",
    question: "ઈ",
    options: ['ii', 'aa', 'a', 'o'],
    correct: "ii",
  },
  {
    id: "224",
    question: "ઉ",
    options: ['u', 'i', 'au', 'e'],
    correct: "u",
  },
  {
    id: "225",
    question: "ઊ",
    options: ['uu', 'a', 'o', 'ai'],
    correct: "uu",
  },
  {
    id: "226",
    question: "એ",
    options: ['e', 'aa', 'au', 'i'],
    correct: "e",
  },
  {
    id: "227",
    question: "ઐ",
    options: ['ai', 'u', 'a', 'o'],
    correct: "ai",
  },
  {
    id: "228",
    question: "ઓ",
    options: ['o', 'uu', 'a', 'ai'],
    correct: "o",
  },
  {
    id: "229",
    question: "ઔ",
    options: ['au', 'ii', 'a', 'aa'],
    correct: "au",
  },
  {
    id: "230",
    question: "અ",
    options: ['a', 'uu', 'u', 'o'],
    correct: "a",
  },
  {
    id: "231",
    question: "આ",
    options: ['aa', 'uu', 'a', 'e'],
    correct: "aa",
  },
  {
    id: "232",
    question: "ઇ",
    options: ['i', 'au', 'a', 'aa'],
    correct: "i",
  },
  {
    id: "233",
    question: "ઈ",
    options: ['ii', 'aa', 'a', 'au'],
    correct: "ii",
  },
  {
    id: "234",
    question: "ઉ",
    options: ['u', 'e', 'i', 'ai'],
    correct: "u",
  },
  {
    id: "235",
    question: "ઊ",
    options: ['uu', 'u', 'ii', 'a'],
    correct: "uu",
  },
  {
    id: "236",
    question: "એ",
    options: ['e', 'uu', 'u', 'i'],
    correct: "e",
  },
  {
    id: "237",
    question: "ઐ",
    options: ['ai', 'au', 'e', 'i'],
    correct: "ai",
  },
  {
    id: "238",
    question: "ઓ",
    options: ['o', 'ai', 'a', 'au'],
    correct: "o",
  },
  {
    id: "239",
    question: "ઔ",
    options: ['au', 'u', 'i', 'o'],
    correct: "au",
  },
  {
    id: "240",
    question: "અ",
    options: ['a', 'au', 'uu', 'i'],
    correct: "a",
  },
  {
    id: "241",
    question: "આ",
    options: ['aa', 'au', 'uu', 'ii'],
    correct: "aa",
  },
  {
    id: "242",
    question: "ઇ",
    options: ['i', 'aa', 'ii', 'uu'],
    correct: "i",
  },
  {
    id: "243",
    question: "ઈ",
    options: ['ii', 'u', 'au', 'a'],
    correct: "ii",
  },
  {
    id: "244",
    question: "ઉ",
    options: ['u', 'ai', 'e', 'aa'],
    correct: "u",
  },
  {
    id: "245",
    question: "ઊ",
    options: ['uu', 'u', 'a', 'i'],
    correct: "uu",
  },
  {
    id: "246",
    question: "એ",
    options: ['e', 'i', 'ii', 'u'],
    correct: "e",
  },
  {
    id: "247",
    question: "ઐ",
    options: ['ai', 'o', 'e', 'ii'],
    correct: "ai",
  },
  {
    id: "248",
    question: "ઓ",
    options: ['o', 'aa', 'ai', 'ii'],
    correct: "o",
  },
  {
    id: "249",
    question: "ઔ",
    options: ['au', 'o', 'aa', 'uu'],
    correct: "au",
  },
  {
    id: "250",
    question: "અ",
    options: ['a', 'uu', 'ii', 'u'],
    correct: "a",
  },
  {
    id: "251",
    question: "આ",
    options: ['aa', 'au', 'i', 'uu'],
    correct: "aa",
  },
  {
    id: "252",
    question: "ઇ",
    options: ['i', 'o', 'uu', 'u'],
    correct: "i",
  },
  {
    id: "253",
    question: "ઈ",
    options: ['ii', 'au', 'o', 'a'],
    correct: "ii",
  },
  {
    id: "254",
    question: "ઉ",
    options: ['u', 'e', 'ai', 'uu'],
    correct: "u",
  },
  {
    id: "255",
    question: "ઊ",
    options: ['uu', 'u', 'a', 'ai'],
    correct: "uu",
  },
  {
    id: "256",
    question: "એ",
    options: ['e', 'o', 'aa', 'u'],
    correct: "e",
  },
  {
    id: "257",
    question: "ઐ",
    options: ['ai', 'au', 'ii', 'i'],
    correct: "ai",
  },
  {
    id: "258",
    question: "ઓ",
    options: ['o', 'uu', 'au', 'aa'],
    correct: "o",
  },
  {
    id: "259",
    question: "ઔ",
    options: ['au', 'ai', 'a', 'uu'],
    correct: "au",
  },
  {
    id: "260",
    question: "અ",
    options: ['a', 'ai', 'au', 'ii'],
    correct: "a",
  },
  {
    id: "261",
    question: "આ",
    options: ['aa', 'i', 'a', 'u'],
    correct: "aa",
  },
  {
    id: "262",
    question: "ઇ",
    options: ['i', 'au', 'a', 'ai'],
    correct: "i",
  },
  {
    id: "263",
    question: "ઈ",
    options: ['ii', 'uu', 'o', 'au'],
    correct: "ii",
  },
  {
    id: "264",
    question: "ઉ",
    options: ['u', 'e', 'a', 'au'],
    correct: "u",
  },
  {
    id: "265",
    question: "ઊ",
    options: ['uu', 'au', 'e', 'i'],
    correct: "uu",
  },
  {
    id: "266",
    question: "એ",
    options: ['e', 'o', 'uu', 'u'],
    correct: "e",
  },
  {
    id: "267",
    question: "ઐ",
    options: ['ai', 'au', 'aa', 'ii'],
    correct: "ai",
  },
  {
    id: "268",
    question: "ઓ",
    options: ['o', 'uu', 'ai', 'aa'],
    correct: "o",
  },
  {
    id: "269",
    question: "ઔ",
    options: ['au', 'e', 'ii', 'a'],
    correct: "au",
  },
  {
    id: "270",
    question: "અ",
    options: ['a', 'au', 'u', 'aa'],
    correct: "a",
  },
  {
    id: "271",
    question: "આ",
    options: ['aa', 'ii', 'e', 'o'],
    correct: "aa",
  },
  {
    id: "272",
    question: "ઇ",
    options: ['i', 'a', 'o', 'ii'],
    correct: "i",
  },
  {
    id: "273",
    question: "ઈ",
    options: ['ii', 'ai', 'o', 'a'],
    correct: "ii",
  },
  {
    id: "274",
    question: "ઉ",
    options: ['u', 'a', 'au', 'aa'],
    correct: "u",
  },
  {
    id: "275",
    question: "ઊ",
    options: ['uu', 'ii', 'aa', 'o'],
    correct: "uu",
  },
  {
    id: "276",
    question: "એ",
    options: ['e', 'a', 'au', 'aa'],
    correct: "e",
  },
  {
    id: "277",
    question: "ઐ",
    options: ['ai', 'u', 'ii', 'uu'],
    correct: "ai",
  },
  {
    id: "278",
    question: "ઓ",
    options: ['o', 'ii', 'uu', 'aa'],
    correct: "o",
  },
  {
    id: "279",
    question: "ઔ",
    options: ['au', 'a', 'e', 'i'],
    correct: "au",
  },
  {
    id: "280",
    question: "અ",
    options: ['a', 'ii', 'aa', 'o'],
    correct: "a",
  },
  {
    id: "281",
    question: "આ",
    options: ['aa', 'i', 'au', 'a'],
    correct: "aa",
  },
  {
    id: "282",
    question: "ઇ",
    options: ['i', 'ii', 'au', 'aa'],
    correct: "i",
  },
  {
    id: "283",
    question: "ઈ",
    options: ['ii', 'u', 'aa', 'a'],
    correct: "ii",
  },
  {
    id: "284",
    question: "ઉ",
    options: ['u', 'o', 'ai', 'a'],
    correct: "u",
  },
  {
    id: "285",
    question: "ઊ",
    options: ['uu', 'e', 'ai', 'u'],
    correct: "uu",
  },
  {
    id: "286",
    question: "એ",
    options: ['e', 'o', 'ai', 'a'],
    correct: "e",
  },
  {
    id: "287",
    question: "ઐ",
    options: ['ai', 'uu', 'aa', 'i'],
    correct: "ai",
  },
  {
    id: "288",
    question: "ઓ",
    options: ['o', 'i', 'ai', 'uu'],
    correct: "o",
  },
  {
    id: "289",
    question: "ઔ",
    options: ['au', 'ai', 'i', 'aa'],
    correct: "au",
  },
  {
    id: "290",
    question: "અ",
    options: ['a', 'u', 'uu', 'ai'],
    correct: "a",
  },
  {
    id: "291",
    question: "આ",
    options: ['aa', 'uu', 'u', 'i'],
    correct: "aa",
  },
  {
    id: "292",
    question: "ઇ",
    options: ['i', 'o', 'au', 'u'],
    correct: "i",
  },
  {
    id: "293",
    question: "ઈ",
    options: ['ii', 'aa', 'au', 'o'],
    correct: "ii",
  },
  {
    id: "294",
    question: "ઉ",
    options: ['u', 'ai', 'o', 'e'],
    correct: "u",
  },
  {
    id: "295",
    question: "ઊ",
    options: ['uu', 'u', 'i', 'e'],
    correct: "uu",
  },
  {
    id: "296",
    question: "એ",
    options: ['e', 'au', 'u', 'ii'],
    correct: "e",
  },
  {
    id: "297",
    question: "ઐ",
    options: ['ai', 'o', 'u', 'a'],
    correct: "ai",
  },
  {
    id: "298",
    question: "ઓ",
    options: ['o', 'a', 'ai', 'i'],
    correct: "o",
  },
  {
    id: "299",
    question: "ઔ",
    options: ['au', 'ii', 'aa', 'e'],
    correct: "au",
  },
  {
    id: "300",
    question: "અ",
    options: ['a', 'ai', 'o', 'aa'],
    correct: "a",
  },
  {
    id: "301",
    question: "આ",
    options: ['aa', 'u', 'uu', 'ii'],
    correct: "aa",
  },
  {
    id: "302",
    question: "ઇ",
    options: ['i', 'ai', 'o', 'ii'],
    correct: "i",
  },
  {
    id: "303",
    question: "ઈ",
    options: ['ii', 'a', 'ai', 'uu'],
    correct: "ii",
  },
  {
    id: "304",
    question: "ઉ",
    options: ['u', 'a', 'aa', 'e'],
    correct: "u",
  },
  {
    id: "305",
    question: "ઊ",
    options: ['uu', 'e', 'au', 'i'],
    correct: "uu",
  },
  {
    id: "306",
    question: "એ",
    options: ['e', 'i', 'au', 'ii'],
    correct: "e",
  },
  {
    id: "307",
    question: "ઐ",
    options: ['ai', 'ii', 'uu', 'i'],
    correct: "ai",
  },
  {
    id: "308",
    question: "ઓ",
    options: ['o', 'ai', 'u', 'a'],
    correct: "o",
  },
  {
    id: "309",
    question: "ઔ",
    options: ['au', 'i', 'aa', 'uu'],
    correct: "au",
  },
  {
    id: "310",
    question: "અ",
    options: ['a', 'au', 'e', 'o'],
    correct: "a",
  },
  {
    id: "311",
    question: "આ",
    options: ['aa', 'a', 'o', 'ai'],
    correct: "aa",
  },
  {
    id: "312",
    question: "ઇ",
    options: ['i', 'o', 'au', 'e'],
    correct: "i",
  },
  {
    id: "313",
    question: "ઈ",
    options: ['ii', 'au', 'a', 'uu'],
    correct: "ii",
  },
  {
    id: "314",
    question: "ઉ",
    options: ['u', 'aa', 'a', 'au'],
    correct: "u",
  },
  {
    id: "315",
    question: "ઊ",
    options: ['uu', 'ii', 'o', 'u'],
    correct: "uu",
  },
  {
    id: "316",
    question: "એ",
    options: ['e', 'o', 'ai', 'i'],
    correct: "e",
  },
  {
    id: "317",
    question: "ઐ",
    options: ['ai', 'aa', 'au', 'uu'],
    correct: "ai",
  },
  {
    id: "318",
    question: "ઓ",
    options: ['o', 'ai', 'uu', 'e'],
    correct: "o",
  },
  {
    id: "319",
    question: "ઔ",
    options: ['au', 'uu', 'e', 'ii'],
    correct: "au",
  },
  {
    id: "320",
    question: "અ",
    options: ['a', 'e', 'ii', 'uu'],
    correct: "a",
  },
  {
    id: "321",
    question: "આ",
    options: ['aa', 'u', 'e', 'i'],
    correct: "aa",
  },
  {
    id: "322",
    question: "ઇ",
    options: ['i', 'o', 'u', 'a'],
    correct: "i",
  },
  {
    id: "323",
    question: "ઈ",
    options: ['ii', 'au', 'uu', 'i'],
    correct: "ii",
  },
  {
    id: "324",
    question: "ઉ",
    options: ['u', 'i', 'au', 'uu'],
    correct: "u",
  },
  {
    id: "325",
    question: "ઊ",
    options: ['uu', 'ai', 'aa', 'e'],
    correct: "uu",
  },
  {
    id: "326",
    question: "એ",
    options: ['e', 'a', 'aa', 'i'],
    correct: "e",
  },
  {
    id: "327",
    question: "ઐ",
    options: ['ai', 'i', 'au', 'aa'],
    correct: "ai",
  },
  {
    id: "328",
    question: "ઓ",
    options: ['o', 'aa', 'u', 'ai'],
    correct: "o",
  },
  {
    id: "329",
    question: "ઔ",
    options: ['au', 'uu', 'a', 'aa'],
    correct: "au",
  },
  {
    id: "330",
    question: "અ",
    options: ['a', 'o', 'ai', 'uu'],
    correct: "a",
  },
  {
    id: "331",
    question: "આ",
    options: ['aa', 'o', 'a', 'e'],
    correct: "aa",
  },
  {
    id: "332",
    question: "ઇ",
    options: ['i', 'uu', 'au', 'aa'],
    correct: "i",
  },
  {
    id: "333",
    question: "ઈ",
    options: ['ii', 'a', 'ai', 'o'],
    correct: "ii",
  },
  {
    id: "334",
    question: "ઉ",
    options: ['u', 'ai', 'aa', 'au'],
    correct: "u",
  },
  {
    id: "335",
    question: "ઊ",
    options: ['uu', 'a', 'ai', 'u'],
    correct: "uu",
  },
  {
    id: "336",
    question: "એ",
    options: ['e', 'au', 'ai', 'aa'],
    correct: "e",
  },
  {
    id: "337",
    question: "ઐ",
    options: ['ai', 'uu', 'ii', 'aa'],
    correct: "ai",
  },
  {
    id: "338",
    question: "ઓ",
    options: ['o', 'i', 'u', 'au'],
    correct: "o",
  },
  {
    id: "339",
    question: "ઔ",
    options: ['au', 'uu', 'a', 'aa'],
    correct: "au",
  },
  {
    id: "340",
    question: "અ",
    options: ['a', 'o', 'i', 'u'],
    correct: "a",
  },
  {
    id: "341",
    question: "આ",
    options: ['aa', 'o', 'e', 'ai'],
    correct: "aa",
  },
  {
    id: "342",
    question: "ઇ",
    options: ['i', 'o', 'au', 'aa'],
    correct: "i",
  },
  {
    id: "343",
    question: "ઈ",
    options: ['ii', 'a', 'aa', 'o'],
    correct: "ii",
  },
  {
    id: "344",
    question: "ઉ",
    options: ['u', 'ai', 'aa', 'au'],
    correct: "u",
  },
  {
    id: "345",
    question: "ઊ",
    options: ['uu', 'u', 'aa', 'i'],
    correct: "uu",
  },
  {
    id: "346",
    question: "એ",
    options: ['e', 'u', 'aa', 'a'],
    correct: "e",
  },
  {
    id: "347",
    question: "ઐ",
    options: ['ai', 'au', 'aa', 'ii'],
    correct: "ai",
  },
  {
    id: "348",
    question: "ઓ",
    options: ['o', 'u', 'aa', 'ii'],
    correct: "o",
  },
  {
    id: "349",
    question: "ઔ",
    options: ['au', 'aa', 'a', 'u'],
    correct: "au",
  },
  {
    id: "350",
    question: "અ",
    options: ['a', 'ii', 'e', 'uu'],
    correct: "a",
  },
  {
    id: "351",
    question: "આ",
    options: ['aa', 'o', 'e', 'ii'],
    correct: "aa",
  },
  {
    id: "352",
    question: "ઇ",
    options: ['i', 'au', 'ai', 'uu'],
    correct: "i",
  },
  {
    id: "353",
    question: "ઈ",
    options: ['ii', 'e', 'i', 'a'],
    correct: "ii",
  },
  {
    id: "354",
    question: "ઉ",
    options: ['u', 'ii', 'a', 'au'],
    correct: "u",
  },
  {
    id: "355",
    question: "ઊ",
    options: ['uu', 'i', 'a', 'e'],
    correct: "uu",
  },
  {
    id: "356",
    question: "એ",
    options: ['e', 'ii', 'u', 'o'],
    correct: "e",
  },
  {
    id: "357",
    question: "ઐ",
    options: ['ai', 'ii', 'i', 'aa'],
    correct: "ai",
  },
  {
    id: "358",
    question: "ઓ",
    options: ['o', 'ai', 'au', 'aa'],
    correct: "o",
  },
  {
    id: "359",
    question: "ઔ",
    options: ['au', 'o', 'ai', 'e'],
    correct: "au",
  },
  {
    id: "360",
    question: "અ",
    options: ['a', 'aa', 'au', 'ii'],
    correct: "a",
  },
  {
    id: "361",
    question: "આ",
    options: ['aa', 'i', 'e', 'o'],
    correct: "aa",
  },
  {
    id: "362",
    question: "ઇ",
    options: ['i', 'a', 'e', 'au'],
    correct: "i",
  },
  {
    id: "363",
    question: "ઈ",
    options: ['ii', 'e', 'ai', 'aa'],
    correct: "ii",
  },
  {
    id: "364",
    question: "ઉ",
    options: ['u', 'aa', 'au', 'a'],
    correct: "u",
  },
  {
    id: "365",
    question: "ઊ",
    options: ['uu', 'o', 'a', 'e'],
    correct: "uu",
  },
  {
    id: "366",
    question: "એ",
    options: ['e', 'ai', 'u', 'aa'],
    correct: "e",
  },
  {
    id: "367",
    question: "ઐ",
    options: ['ai', 'e', 'au', 'ii'],
    correct: "ai",
  },
  {
    id: "368",
    question: "ઓ",
    options: ['o', 'a', 'uu', 'ai'],
    correct: "o",
  },
  {
    id: "369",
    question: "ઔ",
    options: ['au', 'o', 'ai', 'ii'],
    correct: "au",
  },
  {
    id: "370",
    question: "અ",
    options: ['a', 'aa', 'e', 'o'],
    correct: "a",
  },
  {
    id: "371",
    question: "આ",
    options: ['aa', 'ai', 'i', 'ii'],
    correct: "aa",
  },
  {
    id: "372",
    question: "ઇ",
    options: ['i', 'a', 'o', 'u'],
    correct: "i",
  },
  {
    id: "373",
    question: "ઈ",
    options: ['ii', 'u', 'a', 'e'],
    correct: "ii",
  },
  {
    id: "374",
    question: "ઉ",
    options: ['u', 'ii', 'i', 'o'],
    correct: "u",
  },
  {
    id: "375",
    question: "ઊ",
    options: ['uu', 'a', 'e', 'i'],
    correct: "uu",
  },
  {
    id: "376",
    question: "એ",
    options: ['e', 'aa', 'o', 'ai'],
    correct: "e",
  },
  {
    id: "377",
    question: "ઐ",
    options: ['ai', 'i', 'e', 'ii'],
    correct: "ai",
  },
  {
    id: "378",
    question: "ઓ",
    options: ['o', 'a', 'u', 'e'],
    correct: "o",
  },
  {
    id: "379",
    question: "ઔ",
    options: ['au', 'e', 'u', 'o'],
    correct: "au",
  },
  {
    id: "380",
    question: "અ",
    options: ['a', 'ai', 'i', 'e'],
    correct: "a",
  },
  {
    id: "381",
    question: "આ",
    options: ['aa', 'e', 'au', 'i'],
    correct: "aa",
  },
  {
    id: "382",
    question: "ઇ",
    options: ['i', 'a', 'aa', 'e'],
    correct: "i",
  },
  {
    id: "383",
    question: "ઈ",
    options: ['ii', 'a', 'u', 'uu'],
    correct: "ii",
  },
  {
    id: "384",
    question: "ઉ",
    options: ['u', 'a', 'uu', 'ii'],
    correct: "u",
  },
  {
    id: "385",
    question: "ઊ",
    options: ['uu', 'e', 'ai', 'o'],
    correct: "uu",
  },
  {
    id: "386",
    question: "એ",
    options: ['e', 'i', 'o', 'uu'],
    correct: "e",
  },
  {
    id: "387",
    question: "ઐ",
    options: ['ai', 'ii', 'uu', 'e'],
    correct: "ai",
  },
  {
    id: "388",
    question: "ઓ",
    options: ['o', 'i', 'u', 'e'],
    correct: "o",
  },
  {
    id: "389",
    question: "ઔ",
    options: ['au', 'ii', 'a', 'ai'],
    correct: "au",
  },
  {
    id: "390",
    question: "અ",
    options: ['a', 'i', 'u', 'uu'],
    correct: "a",
  },
  {
    id: "391",
    question: "આ",
    options: ['aa', 'au', 'ai', 'u'],
    correct: "aa",
  },
  {
    id: "392",
    question: "ઇ",
    options: ['i', 'u', 'ii', 'o'],
    correct: "i",
  },
  {
    id: "393",
    question: "ઈ",
    options: ['ii', 'o', 'au', 'ai'],
    correct: "ii",
  },
  {
    id: "394",
    question: "ઉ",
    options: ['u', 'a', 'ai', 'uu'],
    correct: "u",
  },
  {
    id: "395",
    question: "ઊ",
    options: ['uu', 'i', 'u', 'aa'],
    correct: "uu",
  },
  {
    id: "396",
    question: "એ",
    options: ['e', 'uu', 'a', 'ai'],
    correct: "e",
  },
  {
    id: "397",
    question: "ઐ",
    options: ['ai', 'i', 'u', 'aa'],
    correct: "ai",
  },
  {
    id: "398",
    question: "ઓ",
    options: ['o', 'ii', 'e', 'i'],
    correct: "o",
  },
  {
    id: "399",
    question: "ઔ",
    options: ['au', 'a', 'ai', 'o'],
    correct: "au",
  },
  {
    id: "400",
    question: "અ",
    options: ['a', 'e', 'aa', 'ii'],
    correct: "a",
  },
  {
    id: "401",
    question: "આ",
    options: ['aa', 'uu', 'u', 'ai'],
    correct: "aa",
  },
  {
    id: "402",
    question: "ઇ",
    options: ['i', 'aa', 'a', 'u'],
    correct: "i",
  },
  {
    id: "403",
    question: "ઈ",
    options: ['ii', 'e', 'o', 'aa'],
    correct: "ii",
  },
  {
    id: "404",
    question: "ઉ",
    options: ['u', 'uu', 'au', 'ai'],
    correct: "u",
  },
  {
    id: "405",
    question: "ઊ",
    options: ['uu', 'a', 'ai', 'aa'],
    correct: "uu",
  },
  {
    id: "406",
    question: "એ",
    options: ['e', 'u', 'ii', 'uu'],
    correct: "e",
  },
  {
    id: "407",
    question: "ઐ",
    options: ['ai', 'o', 'aa', 'a'],
    correct: "ai",
  },
  {
    id: "408",
    question: "ઓ",
    options: ['o', 'u', 'e', 'aa'],
    correct: "o",
  },
  {
    id: "409",
    question: "ઔ",
    options: ['au', 'a', 'uu', 'i'],
    correct: "au",
  },
  {
    id: "410",
    question: "અ",
    options: ['a', 'i', 'uu', 'ai'],
    correct: "a",
  },
  {
    id: "411",
    question: "આ",
    options: ['aa', 'u', 'uu', 'e'],
    correct: "aa",
  },
  {
    id: "412",
    question: "ઇ",
    options: ['i', 'a', 'aa', 'e'],
    correct: "i",
  },
  {
    id: "413",
    question: "ઈ",
    options: ['ii', 'au', 'ai', 'i'],
    correct: "ii",
  },
  {
    id: "414",
    question: "ઉ",
    options: ['u', 'e', 'au', 'i'],
    correct: "u",
  },
  {
    id: "415",
    question: "ઊ",
    options: ['uu', 'ai', 'aa', 'i'],
    correct: "uu",
  },
  {
    id: "416",
    question: "એ",
    options: ['e', 'au', 'i', 'a'],
    correct: "e",
  },
  {
    id: "417",
    question: "ઐ",
    options: ['ai', 'uu', 'aa', 'o'],
    correct: "ai",
  },
  {
    id: "418",
    question: "ઓ",
    options: ['o', 'u', 'au', 'ii'],
    correct: "o",
  },
  {
    id: "419",
    question: "ઔ",
    options: ['au', 'u', 'ii', 'o'],
    correct: "au",
  },
  {
    id: "420",
    question: "અ",
    options: ['a', 'o', 'u', 'uu'],
    correct: "a",
  },
  {
    id: "421",
    question: "આ",
    options: ['aa', 'i', 'ii', 'e'],
    correct: "aa",
  },
  {
    id: "422",
    question: "ઇ",
    options: ['i', 'o', 'aa', 'ai'],
    correct: "i",
  },
  {
    id: "423",
    question: "ઈ",
    options: ['ii', 'o', 'au', 'uu'],
    correct: "ii",
  },
  {
    id: "424",
    question: "ઉ",
    options: ['u', 'uu', 'a', 'au'],
    correct: "u",
  },
  {
    id: "425",
    question: "ઊ",
    options: ['uu', 'u', 'ai', 'ii'],
    correct: "uu",
  },
  {
    id: "426",
    question: "એ",
    options: ['e', 'au', 'u', 'ai'],
    correct: "e",
  },
  {
    id: "427",
    question: "ઐ",
    options: ['ai', 'uu', 'u', 'e'],
    correct: "ai",
  },
  {
    id: "428",
    question: "ઓ",
    options: ['o', 'aa', 'e', 'ii'],
    correct: "o",
  },
  {
    id: "429",
    question: "ઔ",
    options: ['au', 'e', 'aa', 'ii'],
    correct: "au",
  },
  {
    id: "430",
    question: "અ",
    options: ['a', 'au', 'i', 'u'],
    correct: "a",
  },
  {
    id: "431",
    question: "આ",
    options: ['aa', 'a', 'i', 'o'],
    correct: "aa",
  },
  {
    id: "432",
    question: "ઇ",
    options: ['i', 'aa', 'ai', 'o'],
    correct: "i",
  },
  {
    id: "433",
    question: "ઈ",
    options: ['ii', 'u', 'a', 'e'],
    correct: "ii",
  },
  {
    id: "434",
    question: "ઉ",
    options: ['u', 'o', 'e', 'i'],
    correct: "u",
  },
  {
    id: "435",
    question: "ઊ",
    options: ['uu', 'e', 'ai', 'u'],
    correct: "uu",
  },
  {
    id: "436",
    question: "એ",
    options: ['e', 'a', 'u', 'uu'],
    correct: "e",
  },
  {
    id: "437",
    question: "ઐ",
    options: ['ai', 'aa', 'u', 'ii'],
    correct: "ai",
  },
  {
    id: "438",
    question: "ઓ",
    options: ['o', 'au', 'aa', 'e'],
    correct: "o",
  },
  {
    id: "439",
    question: "ઔ",
    options: ['au', 'a', 'ai', 'uu'],
    correct: "au",
  },
  {
    id: "440",
    question: "અ",
    options: ['a', 'ai', 'i', 'au'],
    correct: "a",
  },
  {
    id: "441",
    question: "આ",
    options: ['aa', 'e', 'u', 'ai'],
    correct: "aa",
  },
  {
    id: "442",
    question: "ઇ",
    options: ['i', 'au', 'ii', 'o'],
    correct: "i",
  },
  {
    id: "443",
    question: "ઈ",
    options: ['ii', 'o', 'ai', 'a'],
    correct: "ii",
  },
  {
    id: "444",
    question: "ઉ",
    options: ['u', 'ii', 'au', 'aa'],
    correct: "u",
  },
  {
    id: "445",
    question: "ઊ",
    options: ['uu', 'a', 'ii', 'e'],
    correct: "uu",
  },
  {
    id: "446",
    question: "એ",
    options: ['e', 'ii', 'u', 'ai'],
    correct: "e",
  },
  {
    id: "447",
    question: "ઐ",
    options: ['ai', 'au', 'e', 'o'],
    correct: "ai",
  },
  {
    id: "448",
    question: "ઓ",
    options: ['o', 'u', 'ai', 'i'],
    correct: "o",
  },
  {
    id: "449",
    question: "ઔ",
    options: ['au', 'ai', 'uu', 'u'],
    correct: "au",
  },
  {
    id: "450",
    question: "અ",
    options: ['a', 'uu', 'au', 'ii'],
    correct: "a",
  },
  {
    id: "451",
    question: "આ",
    options: ['aa', 'ii', 'u', 'e'],
    correct: "aa",
  },
  {
    id: "452",
    question: "ઇ",
    options: ['i', 'aa', 'a', 'o'],
    correct: "i",
  },
  {
    id: "453",
    question: "ઈ",
    options: ['ii', 'o', 'e', 'i'],
    correct: "ii",
  },
  {
    id: "454",
    question: "ઉ",
    options: ['u', 'i', 'o', 'a'],
    correct: "u",
  },
  {
    id: "455",
    question: "ઊ",
    options: ['uu', 'ii', 'a', 'u'],
    correct: "uu",
  },
  {
    id: "456",
    question: "એ",
    options: ['e', 'o', 'au', 'i'],
    correct: "e",
  },
  {
    id: "457",
    question: "ઐ",
    options: ['ai', 'o', 'ii', 'uu'],
    correct: "ai",
  },
  {
    id: "458",
    question: "ઓ",
    options: ['o', 'ai', 'u', 'a'],
    correct: "o",
  },
  {
    id: "459",
    question: "ઔ",
    options: ['au', 'i', 'aa', 'a'],
    correct: "au",
  },
  {
    id: "460",
    question: "અ",
    options: ['a', 'ii', 'i', 'o'],
    correct: "a",
  },
  {
    id: "461",
    question: "આ",
    options: ['aa', 'i', 'au', 'u'],
    correct: "aa",
  },
  {
    id: "462",
    question: "ઇ",
    options: ['i', 'e', 'au', 'o'],
    correct: "i",
  },
  {
    id: "463",
    question: "ઈ",
    options: ['ii', 'aa', 'e', 'uu'],
    correct: "ii",
  },
  {
    id: "464",
    question: "ઉ",
    options: ['u', 'aa', 'ai', 'ii'],
    correct: "u",
  },
  {
    id: "465",
    question: "ઊ",
    options: ['uu', 'aa', 'ai', 'o'],
    correct: "uu",
  },
  {
    id: "466",
    question: "એ",
    options: ['e', 'a', 'uu', 'i'],
    correct: "e",
  },
  {
    id: "467",
    question: "ઐ",
    options: ['ai', 'ii', 'uu', 'a'],
    correct: "ai",
  },
  {
    id: "468",
    question: "ઓ",
    options: ['o', 'i', 'ii', 'au'],
    correct: "o",
  },
  {
    id: "469",
    question: "ઔ",
    options: ['au', 'uu', 'aa', 'o'],
    correct: "au",
  },
  {
    id: "470",
    question: "અ",
    options: ['a', 'ii', 'i', 'ai'],
    correct: "a",
  },
  {
    id: "471",
    question: "આ",
    options: ['aa', 'au', 'ii', 'i'],
    correct: "aa",
  },
  {
    id: "472",
    question: "ઇ",
    options: ['i', 'e', 'a', 'u'],
    correct: "i",
  },
  {
    id: "473",
    question: "ઈ",
    options: ['ii', 'a', 'aa', 'uu'],
    correct: "ii",
  },
  {
    id: "474",
    question: "ઉ",
    options: ['u', 'i', 'e', 'a'],
    correct: "u",
  },
  {
    id: "475",
    question: "ઊ",
    options: ['uu', 'au', 'i', 'ii'],
    correct: "uu",
  },
  {
    id: "476",
    question: "એ",
    options: ['e', 'uu', 'ai', 'i'],
    correct: "e",
  },
  {
    id: "477",
    question: "ઐ",
    options: ['ai', 'aa', 'u', 'a'],
    correct: "ai",
  },
  {
    id: "478",
    question: "ઓ",
    options: ['o', 'u', 'i', 'au'],
    correct: "o",
  },
  {
    id: "479",
    question: "ઔ",
    options: ['au', 'a', 'o', 'aa'],
    correct: "au",
  },
  {
    id: "480",
    question: "અ",
    options: ['a', 'ii', 'e', 'u'],
    correct: "a",
  },
  {
    id: "481",
    question: "આ",
    options: ['aa', 'a', 'au', 'ai'],
    correct: "aa",
  },
  {
    id: "482",
    question: "ઇ",
    options: ['i', 'au', 'o', 'u'],
    correct: "i",
  },
  {
    id: "483",
    question: "ઈ",
    options: ['ii', 'uu', 'u', 'ai'],
    correct: "ii",
  },
  {
    id: "484",
    question: "ઉ",
    options: ['u', 'aa', 'ai', 'i'],
    correct: "u",
  },
  {
    id: "485",
    question: "ઊ",
    options: ['uu', 'a', 'ii', 'u'],
    correct: "uu",
  },
  {
    id: "486",
    question: "એ",
    options: ['e', 'uu', 'ii', 'u'],
    correct: "e",
  },
  {
    id: "487",
    question: "ઐ",
    options: ['ai', 'u', 'e', 'o'],
    correct: "ai",
  },
  {
    id: "488",
    question: "ઓ",
    options: ['o', 'ai', 'a', 'e'],
    correct: "o",
  },
  {
    id: "489",
    question: "ઔ",
    options: ['au', 'o', 'u', 'a'],
    correct: "au",
  },
  {
    id: "490",
    question: "અ",
    options: ['a', 'e', 'ii', 'aa'],
    correct: "a",
  },
  {
    id: "491",
    question: "આ",
    options: ['aa', 'uu', 'e', 'a'],
    correct: "aa",
  },
  {
    id: "492",
    question: "ઇ",
    options: ['i', 'aa', 'au', 'e'],
    correct: "i",
  },
  {
    id: "493",
    question: "ઈ",
    options: ['ii', 'au', 'u', 'uu'],
    correct: "ii",
  },
  {
    id: "494",
    question: "ઉ",
    options: ['u', 'a', 'au', 'ai'],
    correct: "u",
  },
  {
    id: "495",
    question: "ઊ",
    options: ['uu', 'aa', 'o', 'ii'],
    correct: "uu",
  },
  {
    id: "496",
    question: "એ",
    options: ['e', 'a', 'i', 'u'],
    correct: "e",
  },
  {
    id: "497",
    question: "ઐ",
    options: ['ai', 'o', 'u', 'uu'],
    correct: "ai",
  },
  {
    id: "498",
    question: "ઓ",
    options: ['o', 'u', 'au', 'ai'],
    correct: "o",
  },
  {
    id: "499",
    question: "ઔ",
    options: ['au', 'ai', 'ii', 'o'],
    correct: "au",
  },
  {
    id: "500",
    question: "અ",
    options: ['a', 'ii', 'i', 'uu'],
    correct: "a",
  },
  {
    id: "501",
    question: "આ",
    options: ['aa', 'e', 'ai', 'o'],
    correct: "aa",
  },
  {
    id: "502",
    question: "ઇ",
    options: ['i', 'o', 'u', 'aa'],
    correct: "i",
  },
  {
    id: "503",
    question: "ઈ",
    options: ['ii', 'ai', 'uu', 'aa'],
    correct: "ii",
  },
  {
    id: "504",
    question: "ઉ",
    options: ['u', 'o', 'ii', 'a'],
    correct: "u",
  },
  {
    id: "505",
    question: "ઊ",
    options: ['uu', 'e', 'au', 'ii'],
    correct: "uu",
  },
  {
    id: "506",
    question: "એ",
    options: ['e', 'uu', 'o', 'au'],
    correct: "e",
  },
  {
    id: "507",
    question: "ઐ",
    options: ['ai', 'a', 'au', 'uu'],
    correct: "ai",
  },
  {
    id: "508",
    question: "ઓ",
    options: ['o', 'ii', 'a', 'ai'],
    correct: "o",
  },
  {
    id: "509",
    question: "ઔ",
    options: ['au', 'o', 'aa', 'ii'],
    correct: "au",
  },
  {
    id: "510",
    question: "અ",
    options: ['a', 'e', 'ai', 'ii'],
    correct: "a",
  },
  {
    id: "511",
    question: "આ",
    options: ['aa', 'uu', 'u', 'ai'],
    correct: "aa",
  },
  {
    id: "512",
    question: "ઇ",
    options: ['i', 'e', 'ii', 'aa'],
    correct: "i",
  },
  {
    id: "513",
    question: "ઈ",
    options: ['ii', 'a', 'ai', 'aa'],
    correct: "ii",
  },
  {
    id: "514",
    question: "ઉ",
    options: ['u', 'e', 'uu', 'i'],
    correct: "u",
  },
  {
    id: "515",
    question: "ઊ",
    options: ['uu', 'au', 'a', 'o'],
    correct: "uu",
  },
  {
    id: "516",
    question: "એ",
    options: ['e', 'ai', 'i', 'uu'],
    correct: "e",
  },
  {
    id: "517",
    question: "ઐ",
    options: ['ai', 'uu', 'o', 'i'],
    correct: "ai",
  },
  {
    id: "518",
    question: "ઓ",
    options: ['o', 'ai', 'ii', 'u'],
    correct: "o",
  },
  {
    id: "519",
    question: "ઔ",
    options: ['au', 'aa', 'o', 'e'],
    correct: "au",
  },
  {
    id: "520",
    question: "અ",
    options: ['a', 'e', 'o', 'i'],
    correct: "a",
  },
  {
    id: "521",
    question: "આ",
    options: ['aa', 'u', 'au', 'e'],
    correct: "aa",
  },
  {
    id: "522",
    question: "ઇ",
    options: ['i', 'ai', 'uu', 'u'],
    correct: "i",
  },
  {
    id: "523",
    question: "ઈ",
    options: ['ii', 'e', 'au', 'u'],
    correct: "ii",
  },
  {
    id: "524",
    question: "ઉ",
    options: ['u', 'ai', 'au', 'aa'],
    correct: "u",
  },
  {
    id: "525",
    question: "ઊ",
    options: ['uu', 'o', 'au', 'ii'],
    correct: "uu",
  },
  {
    id: "526",
    question: "એ",
    options: ['e', 'uu', 'i', 'a'],
    correct: "e",
  },
  {
    id: "527",
    question: "ઐ",
    options: ['ai', 'u', 'e', 'uu'],
    correct: "ai",
  },
  {
    id: "528",
    question: "ઓ",
    options: ['o', 'ai', 'e', 'ii'],
    correct: "o",
  },
  {
    id: "529",
    question: "ઔ",
    options: ['au', 'ai', 'ii', 'uu'],
    correct: "au",
  },
  {
    id: "530",
    question: "અ",
    options: ['a', 'ii', 'e', 'uu'],
    correct: "a",
  },
  {
    id: "531",
    question: "આ",
    options: ['aa', 'i', 'uu', 'ai'],
    correct: "aa",
  },
  {
    id: "532",
    question: "ઇ",
    options: ['i', 'au', 'e', 'aa'],
    correct: "i",
  },
  {
    id: "533",
    question: "ઈ",
    options: ['ii', 'e', 'i', 'au'],
    correct: "ii",
  },
  {
    id: "534",
    question: "ઉ",
    options: ['u', 'au', 'o', 'a'],
    correct: "u",
  },
  {
    id: "535",
    question: "ઊ",
    options: ['uu', 'ai', 'ii', 'u'],
    correct: "uu",
  },
  {
    id: "536",
    question: "એ",
    options: ['e', 'o', 'i', 'ai'],
    correct: "e",
  },
  {
    id: "537",
    question: "ઐ",
    options: ['ai', 'u', 'o', 'a'],
    correct: "ai",
  },
  {
    id: "538",
    question: "ઓ",
    options: ['o', 'u', 'i', 'ai'],
    correct: "o",
  },
  {
    id: "539",
    question: "ઔ",
    options: ['au', 'e', 'a', 'i'],
    correct: "au",
  },
  {
    id: "540",
    question: "અ",
    options: ['a', 'uu', 'ii', 'ai'],
    correct: "a",
  },
  {
    id: "541",
    question: "આ",
    options: ['aa', 'ii', 'u', 'e'],
    correct: "aa",
  },
  {
    id: "542",
    question: "ઇ",
    options: ['i', 'uu', 'ai', 'aa'],
    correct: "i",
  },
  {
    id: "543",
    question: "ઈ",
    options: ['ii', 'au', 'u', 'uu'],
    correct: "ii",
  },
  {
    id: "544",
    question: "ઉ",
    options: ['u', 'e', 'ai', 'i'],
    correct: "u",
  },
  {
    id: "545",
    question: "ઊ",
    options: ['uu', 'aa', 'i', 'e'],
    correct: "uu",
  },
  {
    id: "546",
    question: "એ",
    options: ['e', 'uu', 'u', 'aa'],
    correct: "e",
  },
  {
    id: "547",
    question: "ઐ",
    options: ['ai', 'aa', 'i', 'ii'],
    correct: "ai",
  },
  {
    id: "548",
    question: "ઓ",
    options: ['o', 'i', 'uu', 'aa'],
    correct: "o",
  },
  {
    id: "549",
    question: "ઔ",
    options: ['au', 'uu', 'a', 'ii'],
    correct: "au",
  },
  {
    id: "550",
    question: "અ",
    options: ['a', 'i', 'u', 'o'],
    correct: "a",
  },
  {
    id: "551",
    question: "આ",
    options: ['aa', 'u', 'e', 'i'],
    correct: "aa",
  },
  {
    id: "552",
    question: "ઇ",
    options: ['i', 'u', 'aa', 'au'],
    correct: "i",
  },
  {
    id: "553",
    question: "ઈ",
    options: ['ii', 'uu', 'aa', 'ai'],
    correct: "ii",
  },
  {
    id: "554",
    question: "ઉ",
    options: ['u', 'a', 'o', 'i'],
    correct: "u",
  },
  {
    id: "555",
    question: "ઊ",
    options: ['uu', 'i', 'aa', 'ii'],
    correct: "uu",
  },
  {
    id: "556",
    question: "એ",
    options: ['e', 'u', 'au', 'a'],
    correct: "e",
  },
  {
    id: "557",
    question: "ઐ",
    options: ['ai', 'au', 'ii', 'uu'],
    correct: "ai",
  },
  {
    id: "558",
    question: "ઓ",
    options: ['o', 'u', 'a', 'aa'],
    correct: "o",
  },
  {
    id: "559",
    question: "ઔ",
    options: ['au', 'ai', 'i', 'u'],
    correct: "au",
  },
  {
    id: "560",
    question: "અ",
    options: ['a', 'uu', 'ii', 'ai'],
    correct: "a",
  },
  {
    id: "561",
    question: "આ",
    options: ['aa', 'ai', 'au', 'a'],
    correct: "aa",
  },
  {
    id: "562",
    question: "ઇ",
    options: ['i', 'a', 'ai', 'au'],
    correct: "i",
  },
  {
    id: "563",
    question: "ઈ",
    options: ['ii', 'aa', 'o', 'uu'],
    correct: "ii",
  },
  {
    id: "564",
    question: "ઉ",
    options: ['u', 'i', 'a', 'aa'],
    correct: "u",
  },
  {
    id: "565",
    question: "ઊ",
    options: ['uu', 'au', 'a', 'aa'],
    correct: "uu",
  },
  {
    id: "566",
    question: "એ",
    options: ['e', 'u', 'a', 'ai'],
    correct: "e",
  },
  {
    id: "567",
    question: "ઐ",
    options: ['ai', 'i', 'uu', 'aa'],
    correct: "ai",
  },
  {
    id: "568",
    question: "ઓ",
    options: ['o', 'u', 'ii', 'aa'],
    correct: "o",
  },
  {
    id: "569",
    question: "ઔ",
    options: ['au', 'u', 'ai', 'o'],
    correct: "au",
  },
  {
    id: "570",
    question: "અ",
    options: ['a', 'e', 'i', 'aa'],
    correct: "a",
  },
  {
    id: "571",
    question: "આ",
    options: ['aa', 'ai', 'au', 'i'],
    correct: "aa",
  },
  {
    id: "572",
    question: "ઇ",
    options: ['i', 'e', 'u', 'o'],
    correct: "i",
  },
  {
    id: "573",
    question: "ઈ",
    options: ['ii', 'ai', 'e', 'au'],
    correct: "ii",
  },
  {
    id: "574",
    question: "ઉ",
    options: ['u', 'uu', 'ai', 'i'],
    correct: "u",
  },
  {
    id: "575",
    question: "ઊ",
    options: ['uu', 'o', 'aa', 'i'],
    correct: "uu",
  },
  {
    id: "576",
    question: "એ",
    options: ['e', 'ii', 'ai', 'i'],
    correct: "e",
  },
  {
    id: "577",
    question: "ઐ",
    options: ['ai', 'u', 'i', 'a'],
    correct: "ai",
  },
  {
    id: "578",
    question: "ઓ",
    options: ['o', 'au', 'a', 'e'],
    correct: "o",
  },
  {
    id: "579",
    question: "ઔ",
    options: ['au', 'uu', 'ii', 'aa'],
    correct: "au",
  },
  {
    id: "580",
    question: "અ",
    options: ['a', 'au', 'o', 'aa'],
    correct: "a",
  },
  {
    id: "581",
    question: "આ",
    options: ['aa', 'o', 'u', 'e'],
    correct: "aa",
  },
  {
    id: "582",
    question: "ઇ",
    options: ['i', 'ai', 'o', 'uu'],
    correct: "i",
  },
  {
    id: "583",
    question: "ઈ",
    options: ['ii', 'aa', 'u', 'e'],
    correct: "ii",
  },
  {
    id: "584",
    question: "ઉ",
    options: ['u', 'ii', 'e', 'o'],
    correct: "u",
  },
  {
    id: "585",
    question: "ઊ",
    options: ['uu', 'e', 'ii', 'aa'],
    correct: "uu",
  },
  {
    id: "586",
    question: "એ",
    options: ['e', 'au', 'uu', 'u'],
    correct: "e",
  },
  {
    id: "587",
    question: "ઐ",
    options: ['ai', 'aa', 'uu', 'ii'],
    correct: "ai",
  },
  {
    id: "588",
    question: "ઓ",
    options: ['o', 'ai', 'aa', 'a'],
    correct: "o",
  },
  {
    id: "589",
    question: "ઔ",
    options: ['au', 'uu', 'ai', 'aa'],
    correct: "au",
  },
  {
    id: "590",
    question: "અ",
    options: ['a', 'uu', 'e', 'o'],
    correct: "a",
  },
  {
    id: "591",
    question: "આ",
    options: ['aa', 'i', 'u', 'uu'],
    correct: "aa",
  },
  {
    id: "592",
    question: "ઇ",
    options: ['i', 'a', 'o', 'e'],
    correct: "i",
  },
  {
    id: "593",
    question: "ઈ",
    options: ['ii', 'aa', 'i', 'uu'],
    correct: "ii",
  },
  {
    id: "594",
    question: "ઉ",
    options: ['u', 'a', 'ai', 'e'],
    correct: "u",
  },
  {
    id: "595",
    question: "ઊ",
    options: ['uu', 'e', 'aa', 'ai'],
    correct: "uu",
  },
  {
    id: "596",
    question: "એ",
    options: ['e', 'au', 'ai', 'i'],
    correct: "e",
  },
  {
    id: "597",
    question: "ઐ",
    options: ['ai', 'ii', 'a', 'i'],
    correct: "ai",
  },
  {
    id: "598",
    question: "ઓ",
    options: ['o', 'i', 'uu', 'aa'],
    correct: "o",
  },
  {
    id: "599",
    question: "ઔ",
    options: ['au', 'a', 'ai', 'aa'],
    correct: "au",
  },
  {
    id: "600",
    question: "અ",
    options: ['a', 'au', 'e', 'uu'],
    correct: "a",
  },
  {
    id: "601",
    question: "આ",
    options: ['aa', 'ii', 'ai', 'uu'],
    correct: "aa",
  },
  {
    id: "602",
    question: "ઇ",
    options: ['i', 'ai', 'ii', 'au'],
    correct: "i",
  },
  {
    id: "603",
    question: "ઈ",
    options: ['ii', 'o', 'i', 'u'],
    correct: "ii",
  },
  {
    id: "604",
    question: "ઉ",
    options: ['u', 'i', 'e', 'ii'],
    correct: "u",
  },
  {
    id: "605",
    question: "ઊ",
    options: ['uu', 'e', 'ii', 'au'],
    correct: "uu",
  },
  {
    id: "606",
    question: "એ",
    options: ['e', 'ai', 'ii', 'a'],
    correct: "e",
  },
  {
    id: "607",
    question: "ઐ",
    options: ['ai', 'aa', 'o', 'ii'],
    correct: "ai",
  },
  {
    id: "608",
    question: "ઓ",
    options: ['o', 'uu', 'u', 'e'],
    correct: "o",
  },
  {
    id: "609",
    question: "ઔ",
    options: ['au', 'ai', 'o', 'e'],
    correct: "au",
  },
  {
    id: "610",
    question: "અ",
    options: ['a', 'i', 'o', 'ai'],
    correct: "a",
  },
  {
    id: "611",
    question: "આ",
    options: ['aa', 'e', 'i', 'ii'],
    correct: "aa",
  },
  {
    id: "612",
    question: "ઇ",
    options: ['i', 'aa', 'o', 'uu'],
    correct: "i",
  },
  {
    id: "613",
    question: "ઈ",
    options: ['ii', 'au', 'ai', 'u'],
    correct: "ii",
  },
  {
    id: "614",
    question: "ઉ",
    options: ['u', 'a', 'i', 'e'],
    correct: "u",
  },
  {
    id: "615",
    question: "ઊ",
    options: ['uu', 'o', 'e', 'i'],
    correct: "uu",
  },
  {
    id: "616",
    question: "એ",
    options: ['e', 'uu', 'ii', 'a'],
    correct: "e",
  },
  {
    id: "617",
    question: "ઐ",
    options: ['ai', 'e', 'a', 'au'],
    correct: "ai",
  },
  {
    id: "618",
    question: "ઓ",
    options: ['o', 'a', 'ii', 'i'],
    correct: "o",
  },
  {
    id: "619",
    question: "ઔ",
    options: ['au', 'a', 'i', 'e'],
    correct: "au",
  },
  {
    id: "620",
    question: "અ",
    options: ['a', 'au', 'e', 'uu'],
    correct: "a",
  },
  {
    id: "621",
    question: "આ",
    options: ['aa', 'i', 'a', 'o'],
    correct: "aa",
  },
  {
    id: "622",
    question: "ઇ",
    options: ['i', 'u', 'ai', 'au'],
    correct: "i",
  },
  {
    id: "623",
    question: "ઈ",
    options: ['ii', 'uu', 'a', 'u'],
    correct: "ii",
  },
  {
    id: "624",
    question: "ઉ",
    options: ['u', 'ai', 'a', 'au'],
    correct: "u",
  },
  {
    id: "625",
    question: "ઊ",
    options: ['uu', 'au', 'ii', 'i'],
    correct: "uu",
  },
  {
    id: "626",
    question: "એ",
    options: ['e', 'a', 'i', 'u'],
    correct: "e",
  },
  {
    id: "627",
    question: "ઐ",
    options: ['ai', 'e', 'aa', 'a'],
    correct: "ai",
  },
  {
    id: "628",
    question: "ઓ",
    options: ['o', 'u', 'aa', 'ii'],
    correct: "o",
  },
  {
    id: "629",
    question: "ઔ",
    options: ['au', 'i', 'e', 'a'],
    correct: "au",
  },
  {
    id: "630",
    question: "અ",
    options: ['a', 'u', 'e', 'au'],
    correct: "a",
  },
  {
    id: "631",
    question: "આ",
    options: ['aa', 'ai', 'uu', 'u'],
    correct: "aa",
  },
  {
    id: "632",
    question: "ઇ",
    options: ['i', 'aa', 'ii', 'u'],
    correct: "i",
  },
  {
    id: "633",
    question: "ઈ",
    options: ['ii', 'u', 'aa', 'o'],
    correct: "ii",
  },
  {
    id: "634",
    question: "ઉ",
    options: ['u', 'aa', 'ai', 'uu'],
    correct: "u",
  },
  {
    id: "635",
    question: "ઊ",
    options: ['uu', 'aa', 'au', 'i'],
    correct: "uu",
  },
  {
    id: "636",
    question: "એ",
    options: ['e', 'ii', 'aa', 'au'],
    correct: "e",
  },
  {
    id: "637",
    question: "ઐ",
    options: ['ai', 'aa', 'u', 'a'],
    correct: "ai",
  },
  {
    id: "638",
    question: "ઓ",
    options: ['o', 'i', 'ai', 'e'],
    correct: "o",
  },
  {
    id: "639",
    question: "ઔ",
    options: ['au', 'ai', 'uu', 'a'],
    correct: "au",
  },
  {
    id: "640",
    question: "અ",
    options: ['a', 'au', 'uu', 'e'],
    correct: "a",
  },
  {
    id: "641",
    question: "આ",
    options: ['aa', 'u', 'e', 'uu'],
    correct: "aa",
  },
  {
    id: "642",
    question: "ઇ",
    options: ['i', 'au', 'u', 'aa'],
    correct: "i",
  },
  {
    id: "643",
    question: "ઈ",
    options: ['ii', 'e', 'au', 'ai'],
    correct: "ii",
  },
  {
    id: "644",
    question: "ઉ",
    options: ['u', 'i', 'ai', 'aa'],
    correct: "u",
  },
  {
    id: "645",
    question: "ઊ",
    options: ['uu', 'e', 'o', 'ai'],
    correct: "uu",
  },
  {
    id: "646",
    question: "એ",
    options: ['e', 'a', 'uu', 'i'],
    correct: "e",
  },
  {
    id: "647",
    question: "ઐ",
    options: ['ai', 'u', 'ii', 'a'],
    correct: "ai",
  },
  {
    id: "648",
    question: "ઓ",
    options: ['o', 'au', 'ii', 'ai'],
    correct: "o",
  },
  {
    id: "649",
    question: "ઔ",
    options: ['au', 'uu', 'i', 'a'],
    correct: "au",
  },
  {
    id: "650",
    question: "અ",
    options: ['a', 'uu', 'e', 'aa'],
    correct: "a",
  },
  {
    id: "651",
    question: "આ",
    options: ['aa', 'ai', 'i', 'ii'],
    correct: "aa",
  },
  {
    id: "652",
    question: "ઇ",
    options: ['i', 'uu', 'ii', 'ai'],
    correct: "i",
  },
  {
    id: "653",
    question: "ઈ",
    options: ['ii', 'au', 'a', 'u'],
    correct: "ii",
  },
  {
    id: "654",
    question: "ઉ",
    options: ['u', 'i', 'ai', 'a'],
    correct: "u",
  },
  {
    id: "655",
    question: "ઊ",
    options: ['uu', 'i', 'ii', 'ai'],
    correct: "uu",
  },
  {
    id: "656",
    question: "એ",
    options: ['e', 'i', 'o', 'ii'],
    correct: "e",
  },
  {
    id: "657",
    question: "ઐ",
    options: ['ai', 'o', 'aa', 'ii'],
    correct: "ai",
  },
  {
    id: "658",
    question: "ઓ",
    options: ['o', 'uu', 'e', 'au'],
    correct: "o",
  },
  {
    id: "659",
    question: "ઔ",
    options: ['au', 'ii', 'u', 'aa'],
    correct: "au",
  },
  {
    id: "660",
    question: "અ",
    options: ['a', 'i', 'o', 'uu'],
    correct: "a",
  },
  {
    id: "661",
    question: "આ",
    options: ['aa', 'u', 'e', 'ii'],
    correct: "aa",
  },
  {
    id: "662",
    question: "ઇ",
    options: ['i', 'o', 'u', 'ii'],
    correct: "i",
  },
  {
    id: "663",
    question: "ઈ",
    options: ['ii', 'uu', 'aa', 'e'],
    correct: "ii",
  },
  {
    id: "664",
    question: "ઉ",
    options: ['u', 'i', 'o', 'ai'],
    correct: "u",
  },
  {
    id: "665",
    question: "ઊ",
    options: ['uu', 'au', 'u', 'a'],
    correct: "uu",
  },
  {
    id: "666",
    question: "એ",
    options: ['e', 'ii', 'i', 'uu'],
    correct: "e",
  },
  {
    id: "667",
    question: "ઐ",
    options: ['ai', 'a', 'u', 'ii'],
    correct: "ai",
  },
  {
    id: "668",
    question: "ઓ",
    options: ['o', 'ii', 'e', 'a'],
    correct: "o",
  },
  {
    id: "669",
    question: "ઔ",
    options: ['au', 'aa', 'a', 'e'],
    correct: "au",
  },
  {
    id: "670",
    question: "અ",
    options: ['a', 'ai', 'e', 'ii'],
    correct: "a",
  },
  {
    id: "671",
    question: "આ",
    options: ['aa', 'a', 'o', 'u'],
    correct: "aa",
  },
  {
    id: "672",
    question: "ઇ",
    options: ['i', 'ai', 'e', 'uu'],
    correct: "i",
  },
  {
    id: "673",
    question: "ઈ",
    options: ['ii', 'e', 'a', 'aa'],
    correct: "ii",
  },
  {
    id: "674",
    question: "ઉ",
    options: ['u', 'uu', 'o', 'au'],
    correct: "u",
  },
  {
    id: "675",
    question: "ઊ",
    options: ['uu', 'o', 'e', 'ai'],
    correct: "uu",
  },
  {
    id: "676",
    question: "એ",
    options: ['e', 'i', 'a', 'o'],
    correct: "e",
  },
  {
    id: "677",
    question: "ઐ",
    options: ['ai', 'o', 'ii', 'uu'],
    correct: "ai",
  },
  {
    id: "678",
    question: "ઓ",
    options: ['o', 'ai', 'i', 'a'],
    correct: "o",
  },
  {
    id: "679",
    question: "ઔ",
    options: ['au', 'ai', 'a', 'i'],
    correct: "au",
  },
  {
    id: "680",
    question: "અ",
    options: ['a', 'ai', 'ii', 'uu'],
    correct: "a",
  },
  {
    id: "681",
    question: "આ",
    options: ['aa', 'ai', 'ii', 'e'],
    correct: "aa",
  },
  {
    id: "682",
    question: "ઇ",
    options: ['i', 'u', 'aa', 'ai'],
    correct: "i",
  },
  {
    id: "683",
    question: "ઈ",
    options: ['ii', 'u', 'o', 'ai'],
    correct: "ii",
  },
  {
    id: "684",
    question: "ઉ",
    options: ['u', 'a', 'aa', 'i'],
    correct: "u",
  },
  {
    id: "685",
    question: "ઊ",
    options: ['uu', 'u', 'ai', 'a'],
    correct: "uu",
  },
  {
    id: "686",
    question: "એ",
    options: ['e', 'aa', 'uu', 'au'],
    correct: "e",
  },
  {
    id: "687",
    question: "ઐ",
    options: ['ai', 'a', 'au', 'uu'],
    correct: "ai",
  },
  {
    id: "688",
    question: "ઓ",
    options: ['o', 'aa', 'e', 'a'],
    correct: "o",
  },
  {
    id: "689",
    question: "ઔ",
    options: ['au', 'ai', 'i', 'e'],
    correct: "au",
  },
  {
    id: "690",
    question: "અ",
    options: ['a', 'ai', 'o', 'e'],
    correct: "a",
  },
  {
    id: "691",
    question: "આ",
    options: ['aa', 'o', 'e', 'ii'],
    correct: "aa",
  },
  {
    id: "692",
    question: "ઇ",
    options: ['i', 'aa', 'ii', 'u'],
    correct: "i",
  },
  {
    id: "693",
    question: "ઈ",
    options: ['ii', 'aa', 'e', 'a'],
    correct: "ii",
  },
  {
    id: "694",
    question: "ઉ",
    options: ['u', 'o', 'au', 'i'],
    correct: "u",
  },
  {
    id: "695",
    question: "ઊ",
    options: ['uu', 'ai', 'au', 'e'],
    correct: "uu",
  },
  {
    id: "696",
    question: "એ",
    options: ['e', 'a', 'i', 'u'],
    correct: "e",
  },
  {
    id: "697",
    question: "ઐ",
    options: ['ai', 'a', 'uu', 'ii'],
    correct: "ai",
  },
  {
    id: "698",
    question: "ઓ",
    options: ['o', 'au', 'aa', 'ii'],
    correct: "o",
  },
  {
    id: "699",
    question: "ઔ",
    options: ['au', 'ii', 'aa', 'e'],
    correct: "au",
  },
  {
    id: "700",
    question: "અ",
    options: ['a', 'au', 'u', 'aa'],
    correct: "a",
  },
  {
    id: "701",
    question: "આ",
    options: ['aa', 'o', 'e', 'ii'],
    correct: "aa",
  },
  {
    id: "702",
    question: "ઇ",
    options: ['i', 'ai', 'aa', 'o'],
    correct: "i",
  },
  {
    id: "703",
    question: "ઈ",
    options: ['ii', 'aa', 'ai', 'a'],
    correct: "ii",
  },
  {
    id: "704",
    question: "ઉ",
    options: ['u', 'ai', 'i', 'a'],
    correct: "u",
  },
  {
    id: "705",
    question: "ઊ",
    options: ['uu', 'i', 'o', 'u'],
    correct: "uu",
  },
  {
    id: "706",
    question: "એ",
    options: ['e', 'aa', 'ai', 'o'],
    correct: "e",
  },
  {
    id: "707",
    question: "ઐ",
    options: ['ai', 'u', 'uu', 'a'],
    correct: "ai",
  },
  {
    id: "708",
    question: "ઓ",
    options: ['o', 'u', 'ai', 'ii'],
    correct: "o",
  },
  {
    id: "709",
    question: "ઔ",
    options: ['au', 'o', 'a', 'ai'],
    correct: "au",
  },
  {
    id: "710",
    question: "અ",
    options: ['a', 'au', 'ai', 'uu'],
    correct: "a",
  },
  {
    id: "711",
    question: "આ",
    options: ['aa', 'au', 'uu', 'u'],
    correct: "aa",
  },
  {
    id: "712",
    question: "ઇ",
    options: ['i', 'u', 'uu', 'au'],
    correct: "i",
  },
  {
    id: "713",
    question: "ઈ",
    options: ['ii', 'i', 'ai', 'e'],
    correct: "ii",
  },
  {
    id: "714",
    question: "ઉ",
    options: ['u', 'o', 'a', 'ii'],
    correct: "u",
  },
  {
    id: "715",
    question: "ઊ",
    options: ['uu', 'i', 'u', 'e'],
    correct: "uu",
  },
  {
    id: "716",
    question: "એ",
    options: ['e', 'o', 'i', 'au'],
    correct: "e",
  },
  {
    id: "717",
    question: "ઐ",
    options: ['ai', 'o', 'aa', 'u'],
    correct: "ai",
  },
  {
    id: "718",
    question: "ઓ",
    options: ['o', 'aa', 'i', 'au'],
    correct: "o",
  },
  {
    id: "719",
    question: "ઔ",
    options: ['au', 'i', 'ii', 'a'],
    correct: "au",
  },
  {
    id: "720",
    question: "અ",
    options: ['a', 'i', 'u', 'ai'],
    correct: "a",
  },
  {
    id: "721",
    question: "આ",
    options: ['aa', 'au', 'e', 'uu'],
    correct: "aa",
  },
  {
    id: "722",
    question: "ઇ",
    options: ['i', 'aa', 'uu', 'a'],
    correct: "i",
  },
  {
    id: "723",
    question: "ઈ",
    options: ['ii', 'ai', 'u', 'a'],
    correct: "ii",
  },
  {
    id: "724",
    question: "ઉ",
    options: ['u', 'o', 'e', 'au'],
    correct: "u",
  },
  {
    id: "725",
    question: "ઊ",
    options: ['uu', 'aa', 'au', 'e'],
    correct: "uu",
  },
  {
    id: "726",
    question: "એ",
    options: ['e', 'o', 'uu', 'ai'],
    correct: "e",
  },
  {
    id: "727",
    question: "ઐ",
    options: ['ai', 'e', 'aa', 'o'],
    correct: "ai",
  },
  {
    id: "728",
    question: "ઓ",
    options: ['o', 'ii', 'aa', 'a'],
    correct: "o",
  },
  {
    id: "729",
    question: "ઔ",
    options: ['au', 'u', 'a', 'i'],
    correct: "au",
  },
  {
    id: "730",
    question: "અ",
    options: ['a', 'o', 'ii', 'ai'],
    correct: "a",
  },
  {
    id: "731",
    question: "આ",
    options: ['aa', 'i', 'ii', 'uu'],
    correct: "aa",
  },
  {
    id: "732",
    question: "ઇ",
    options: ['i', 'u', 'au', 'uu'],
    correct: "i",
  },
  {
    id: "733",
    question: "ઈ",
    options: ['ii', 'i', 'uu', 'ai'],
    correct: "ii",
  },
  {
    id: "734",
    question: "ઉ",
    options: ['u', 'a', 'uu', 'au'],
    correct: "u",
  },
  {
    id: "735",
    question: "ઊ",
    options: ['uu', 'e', 'aa', 'u'],
    correct: "uu",
  },
  {
    id: "736",
    question: "એ",
    options: ['e', 'aa', 'ai', 'a'],
    correct: "e",
  },
  {
    id: "737",
    question: "ઐ",
    options: ['ai', 'o', 'a', 'e'],
    correct: "ai",
  },
  {
    id: "738",
    question: "ઓ",
    options: ['o', 'i', 'ii', 'ai'],
    correct: "o",
  },
  {
    id: "739",
    question: "ઔ",
    options: ['au', 'aa', 'uu', 'i'],
    correct: "au",
  },
  {
    id: "740",
    question: "અ",
    options: ['a', 'uu', 'u', 'i'],
    correct: "a",
  },
  {
    id: "741",
    question: "આ",
    options: ['aa', 'au', 'ai', 'a'],
    correct: "aa",
  },
  {
    id: "742",
    question: "ઇ",
    options: ['i', 'ai', 'e', 'uu'],
    correct: "i",
  },
  {
    id: "743",
    question: "ઈ",
    options: ['ii', 'o', 'aa', 'ai'],
    correct: "ii",
  },
  {
    id: "744",
    question: "ઉ",
    options: ['u', 'o', 'uu', 'ai'],
    correct: "u",
  },
  {
    id: "745",
    question: "ઊ",
    options: ['uu', 'u', 'e', 'au'],
    correct: "uu",
  },
  {
    id: "746",
    question: "એ",
    options: ['e', 'i', 'a', 'ai'],
    correct: "e",
  },
  {
    id: "747",
    question: "ઐ",
    options: ['ai', 'ii', 'au', 'o'],
    correct: "ai",
  },
  {
    id: "748",
    question: "ઓ",
    options: ['o', 'ii', 'a', 'e'],
    correct: "o",
  },
  {
    id: "749",
    question: "ઔ",
    options: ['au', 'i', 'aa', 'uu'],
    correct: "au",
  },
  {
    id: "750",
    question: "અ",
    options: ['a', 'i', 'au', 'u'],
    correct: "a",
  },
  {
    id: "751",
    question: "આ",
    options: ['aa', 'uu', 'ii', 'ai'],
    correct: "aa",
  },
  {
    id: "752",
    question: "ઇ",
    options: ['i', 'a', 'u', 'e'],
    correct: "i",
  },
  {
    id: "753",
    question: "ઈ",
    options: ['ii', 'a', 'uu', 'aa'],
    correct: "ii",
  },
  {
    id: "754",
    question: "ઉ",
    options: ['u', 'uu', 'o', 'aa'],
    correct: "u",
  },
  {
    id: "755",
    question: "ઊ",
    options: ['uu', 'ai', 'e', 'i'],
    correct: "uu",
  },
  {
    id: "756",
    question: "એ",
    options: ['e', 'uu', 'au', 'a'],
    correct: "e",
  },
  {
    id: "757",
    question: "ઐ",
    options: ['ai', 'a', 'i', 'ii'],
    correct: "ai",
  },
  {
    id: "758",
    question: "ઓ",
    options: ['o', 'uu', 'a', 'ai'],
    correct: "o",
  },
  {
    id: "759",
    question: "ઔ",
    options: ['au', 'ii', 'aa', 'e'],
    correct: "au",
  },
  {
    id: "760",
    question: "અ",
    options: ['a', 'au', 'e', 'o'],
    correct: "a",
  },
  {
    id: "761",
    question: "આ",
    options: ['aa', 'i', 'o', 'a'],
    correct: "aa",
  },
  {
    id: "762",
    question: "ઇ",
    options: ['i', 'ai', 'uu', 'ii'],
    correct: "i",
  },
  {
    id: "763",
    question: "ઈ",
    options: ['ii', 'e', 'ai', 'uu'],
    correct: "ii",
  },
  {
    id: "764",
    question: "ઉ",
    options: ['u', 'o', 'au', 'aa'],
    correct: "u",
  },
  {
    id: "765",
    question: "ઊ",
    options: ['uu', 'ai', 'ii', 'au'],
    correct: "uu",
  },
  {
    id: "766",
    question: "એ",
    options: ['e', 'ii', 'uu', 'o'],
    correct: "e",
  },
  {
    id: "767",
    question: "ઐ",
    options: ['ai', 'u', 'o', 'ii'],
    correct: "ai",
  },
  {
    id: "768",
    question: "ઓ",
    options: ['o', 'u', 'e', 'ii'],
    correct: "o",
  },
  {
    id: "769",
    question: "ઔ",
    options: ['au', 'a', 'ai', 'i'],
    correct: "au",
  },
  {
    id: "770",
    question: "અ",
    options: ['a', 'i', 'ai', 'au'],
    correct: "a",
  },
  {
    id: "771",
    question: "આ",
    options: ['aa', 'ii', 'u', 'i'],
    correct: "aa",
  },
  {
    id: "772",
    question: "ઇ",
    options: ['i', 'au', 'uu', 'a'],
    correct: "i",
  },
  {
    id: "773",
    question: "ઈ",
    options: ['ii', 'ai', 'e', 'i'],
    correct: "ii",
  },
  {
    id: "774",
    question: "ઉ",
    options: ['u', 'e', 'o', 'ii'],
    correct: "u",
  },
  {
    id: "775",
    question: "ઊ",
    options: ['uu', 'i', 'ii', 'e'],
    correct: "uu",
  },
  {
    id: "776",
    question: "એ",
    options: ['e', 'ii', 'au', 'ai'],
    correct: "e",
  },
  {
    id: "777",
    question: "ઐ",
    options: ['ai', 'i', 'aa', 'e'],
    correct: "ai",
  },
  {
    id: "778",
    question: "ઓ",
    options: ['o', 'i', 'aa', 'au'],
    correct: "o",
  },
  {
    id: "779",
    question: "ઔ",
    options: ['au', 'o', 'e', 'uu'],
    correct: "au",
  },
  {
    id: "780",
    question: "અ",
    options: ['a', 'aa', 'ai', 'o'],
    correct: "a",
  },
  {
    id: "781",
    question: "આ",
    options: ['aa', 'e', 'o', 'ai'],
    correct: "aa",
  },
  {
    id: "782",
    question: "ઇ",
    options: ['i', 'ai', 'ii', 'uu'],
    correct: "i",
  },
  {
    id: "783",
    question: "ઈ",
    options: ['ii', 'i', 'a', 'o'],
    correct: "ii",
  },
  {
    id: "784",
    question: "ઉ",
    options: ['u', 'ai', 'uu', 'o'],
    correct: "u",
  },
  {
    id: "785",
    question: "ઊ",
    options: ['uu', 'o', 'a', 'u'],
    correct: "uu",
  },
  {
    id: "786",
    question: "એ",
    options: ['e', 'ai', 'a', 'o'],
    correct: "e",
  },
  {
    id: "787",
    question: "ઐ",
    options: ['ai', 'u', 'a', 'i'],
    correct: "ai",
  },
  {
    id: "788",
    question: "ઓ",
    options: ['o', 'ii', 'e', 'au'],
    correct: "o",
  },
  {
    id: "789",
    question: "ઔ",
    options: ['au', 'ai', 'e', 'u'],
    correct: "au",
  },
  {
    id: "790",
    question: "અ",
    options: ['a', 'i', 'uu', 'ii'],
    correct: "a",
  },
  {
    id: "791",
    question: "આ",
    options: ['aa', 'ai', 'u', 'au'],
    correct: "aa",
  },
  {
    id: "792",
    question: "ઇ",
    options: ['i', 'au', 'aa', 'u'],
    correct: "i",
  },
  {
    id: "793",
    question: "ઈ",
    options: ['ii', 'uu', 'au', 'ai'],
    correct: "ii",
  },
  {
    id: "794",
    question: "ઉ",
    options: ['u', 'ai', 'aa', 'a'],
    correct: "u",
  },
  {
    id: "795",
    question: "ઊ",
    options: ['uu', 'a', 'ai', 'u'],
    correct: "uu",
  },
  {
    id: "796",
    question: "એ",
    options: ['e', 'uu', 'ii', 'au'],
    correct: "e",
  },
  {
    id: "797",
    question: "ઐ",
    options: ['ai', 'i', 'uu', 'ii'],
    correct: "ai",
  },
  {
    id: "798",
    question: "ઓ",
    options: ['o', 'a', 'uu', 'au'],
    correct: "o",
  },
  {
    id: "799",
    question: "ઔ",
    options: ['au', 'a', 'ai', 'aa'],
    correct: "au",
  },
  {
    id: "800",
    question: "અ",
    options: ['a', 'aa', 'au', 'ai'],
    correct: "a",
  },
  {
    id: "801",
    question: "આ",
    options: ['aa', 'u', 'uu', 'au'],
    correct: "aa",
  },
  {
    id: "802",
    question: "ઇ",
    options: ['i', 'o', 'aa', 'ii'],
    correct: "i",
  },
  {
    id: "803",
    question: "ઈ",
    options: ['ii', 'i', 'uu', 'aa'],
    correct: "ii",
  },
  {
    id: "804",
    question: "ઉ",
    options: ['u', 'a', 'o', 'au'],
    correct: "u",
  },
  {
    id: "805",
    question: "ઊ",
    options: ['uu', 'e', 'o', 'ai'],
    correct: "uu",
  },
  {
    id: "806",
    question: "એ",
    options: ['e', 'a', 'ii', 'aa'],
    correct: "e",
  },
  {
    id: "807",
    question: "ઐ",
    options: ['ai', 'i', 'a', 'e'],
    correct: "ai",
  },
  {
    id: "808",
    question: "ઓ",
    options: ['o', 'ai', 'uu', 'ii'],
    correct: "o",
  },
  {
    id: "809",
    question: "ઔ",
    options: ['au', 'ii', 'o', 'e'],
    correct: "au",
  },
  {
    id: "810",
    question: "અ",
    options: ['a', 'o', 'uu', 'aa'],
    correct: "a",
  },
  {
    id: "811",
    question: "આ",
    options: ['aa', 'i', 'a', 'uu'],
    correct: "aa",
  },
  {
    id: "812",
    question: "ઇ",
    options: ['i', 'u', 'aa', 'ai'],
    correct: "i",
  },
  {
    id: "813",
    question: "ઈ",
    options: ['ii', 'uu', 'i', 'a'],
    correct: "ii",
  },
  {
    id: "814",
    question: "ઉ",
    options: ['u', 'au', 'aa', 'a'],
    correct: "u",
  },
  {
    id: "815",
    question: "ઊ",
    options: ['uu', 'a', 'u', 'ai'],
    correct: "uu",
  },
  {
    id: "816",
    question: "એ",
    options: ['e', 'u', 'ii', 'ai'],
    correct: "e",
  },
  {
    id: "817",
    question: "ઐ",
    options: ['ai', 'uu', 'aa', 'u'],
    correct: "ai",
  },
  {
    id: "818",
    question: "ઓ",
    options: ['o', 'ii', 'ai', 'i'],
    correct: "o",
  },
  {
    id: "819",
    question: "ઔ",
    options: ['au', 'a', 'aa', 'u'],
    correct: "au",
  },
  {
    id: "820",
    question: "અ",
    options: ['a', 'aa', 'ai', 'o'],
    correct: "a",
  },
  {
    id: "821",
    question: "આ",
    options: ['aa', 'o', 'a', 'ai'],
    correct: "aa",
  },
  {
    id: "822",
    question: "ઇ",
    options: ['i', 'uu', 'ai', 'u'],
    correct: "i",
  },
  {
    id: "823",
    question: "ઈ",
    options: ['ii', 'u', 'a', 'uu'],
    correct: "ii",
  },
  {
    id: "824",
    question: "ઉ",
    options: ['u', 'aa', 'i', 'o'],
    correct: "u",
  },
  {
    id: "825",
    question: "ઊ",
    options: ['uu', 'a', 'au', 'i'],
    correct: "uu",
  },
  {
    id: "826",
    question: "એ",
    options: ['e', 'i', 'aa', 'u'],
    correct: "e",
  },
  {
    id: "827",
    question: "ઐ",
    options: ['ai', 'e', 'ii', 'u'],
    correct: "ai",
  },
  {
    id: "828",
    question: "ઓ",
    options: ['o', 'a', 'u', 'au'],
    correct: "o",
  },
  {
    id: "829",
    question: "ઔ",
    options: ['au', 'ai', 'e', 'uu'],
    correct: "au",
  },
  {
    id: "830",
    question: "અ",
    options: ['a', 'u', 'o', 'i'],
    correct: "a",
  },
  {
    id: "831",
    question: "આ",
    options: ['aa', 'uu', 'ii', 'au'],
    correct: "aa",
  },
  {
    id: "832",
    question: "ઇ",
    options: ['i', 'au', 'o', 'ai'],
    correct: "i",
  },
  {
    id: "833",
    question: "ઈ",
    options: ['ii', 'aa', 'u', 'a'],
    correct: "ii",
  },
  {
    id: "834",
    question: "ઉ",
    options: ['u', 'ai', 'o', 'uu'],
    correct: "u",
  },
  {
    id: "835",
    question: "ઊ",
    options: ['uu', 'u', 'ii', 'ai'],
    correct: "uu",
  },
  {
    id: "836",
    question: "એ",
    options: ['e', 'a', 'ai', 'o'],
    correct: "e",
  },
  {
    id: "837",
    question: "ઐ",
    options: ['ai', 'au', 'ii', 'u'],
    correct: "ai",
  },
  {
    id: "838",
    question: "ઓ",
    options: ['o', 'uu', 'au', 'aa'],
    correct: "o",
  },
  {
    id: "839",
    question: "ઔ",
    options: ['au', 'e', 'a', 'i'],
    correct: "au",
  },
  {
    id: "840",
    question: "અ",
    options: ['a', 'u', 'uu', 'i'],
    correct: "a",
  },
  {
    id: "841",
    question: "આ",
    options: ['aa', 'au', 'ai', 'u'],
    correct: "aa",
  },
  {
    id: "842",
    question: "ઇ",
    options: ['i', 'uu', 'u', 'a'],
    correct: "i",
  },
  {
    id: "843",
    question: "ઈ",
    options: ['ii', 'o', 'i', 'u'],
    correct: "ii",
  },
  {
    id: "844",
    question: "ઉ",
    options: ['u', 'ai', 'o', 'aa'],
    correct: "u",
  },
  {
    id: "845",
    question: "ઊ",
    options: ['uu', 'o', 'u', 'aa'],
    correct: "uu",
  },
  {
    id: "846",
    question: "એ",
    options: ['e', 'ii', 'ai', 'uu'],
    correct: "e",
  },
  {
    id: "847",
    question: "ઐ",
    options: ['ai', 'e', 'i', 'o'],
    correct: "ai",
  },
  {
    id: "848",
    question: "ઓ",
    options: ['o', 'i', 'aa', 'ii'],
    correct: "o",
  },
  {
    id: "849",
    question: "ઔ",
    options: ['au', 'i', 'o', 'uu'],
    correct: "au",
  },
  {
    id: "850",
    question: "અ",
    options: ['a', 'o', 'u', 'au'],
    correct: "a",
  },
  {
    id: "851",
    question: "આ",
    options: ['aa', 'uu', 'ii', 'i'],
    correct: "aa",
  },
  {
    id: "852",
    question: "ઇ",
    options: ['i', 'o', 'u', 'uu'],
    correct: "i",
  },
  {
    id: "853",
    question: "ઈ",
    options: ['ii', 'e', 'o', 'ai'],
    correct: "ii",
  },
  {
    id: "854",
    question: "ઉ",
    options: ['u', 'a', 'au', 'o'],
    correct: "u",
  },
  {
    id: "855",
    question: "ઊ",
    options: ['uu', 'u', 'ai', 'e'],
    correct: "uu",
  },
  {
    id: "856",
    question: "એ",
    options: ['e', 'ai', 'aa', 'ii'],
    correct: "e",
  },
  {
    id: "857",
    question: "ઐ",
    options: ['ai', 'i', 'a', 'aa'],
    correct: "ai",
  },
  {
    id: "858",
    question: "ઓ",
    options: ['o', 'a', 'aa', 'e'],
    correct: "o",
  },
  {
    id: "859",
    question: "ઔ",
    options: ['au', 'ai', 'a', 'o'],
    correct: "au",
  },
  {
    id: "860",
    question: "અ",
    options: ['a', 'i', 'ai', 'e'],
    correct: "a",
  },
  {
    id: "861",
    question: "આ",
    options: ['aa', 'o', 'i', 'u'],
    correct: "aa",
  },
  {
    id: "862",
    question: "ઇ",
    options: ['i', 'uu', 'u', 'e'],
    correct: "i",
  },
  {
    id: "863",
    question: "ઈ",
    options: ['ii', 'aa', 'uu', 'ai'],
    correct: "ii",
  },
  {
    id: "864",
    question: "ઉ",
    options: ['u', 'ai', 'aa', 'a'],
    correct: "u",
  },
  {
    id: "865",
    question: "ઊ",
    options: ['uu', 'o', 'au', 'e'],
    correct: "uu",
  },
  {
    id: "866",
    question: "એ",
    options: ['e', 'a', 'i', 'au'],
    correct: "e",
  },
  {
    id: "867",
    question: "ઐ",
    options: ['ai', 'i', 'ii', 'uu'],
    correct: "ai",
  },
  {
    id: "868",
    question: "ઓ",
    options: ['o', 'uu', 'ai', 'u'],
    correct: "o",
  },
  {
    id: "869",
    question: "ઔ",
    options: ['au', 'a', 'e', 'aa'],
    correct: "au",
  },
  {
    id: "870",
    question: "અ",
    options: ['a', 'e', 'i', 'u'],
    correct: "a",
  },
  {
    id: "871",
    question: "આ",
    options: ['aa', 'ii', 'e', 'i'],
    correct: "aa",
  },
  {
    id: "872",
    question: "ઇ",
    options: ['i', 'aa', 'ai', 'e'],
    correct: "i",
  },
  {
    id: "873",
    question: "ઈ",
    options: ['ii', 'ai', 'u', 'au'],
    correct: "ii",
  },
  {
    id: "874",
    question: "ઉ",
    options: ['u', 'aa', 'e', 'ai'],
    correct: "u",
  },
  {
    id: "875",
    question: "ઊ",
    options: ['uu', 'i', 'ii', 'a'],
    correct: "uu",
  },
  {
    id: "876",
    question: "એ",
    options: ['e', 'aa', 'au', 'o'],
    correct: "e",
  },
  {
    id: "877",
    question: "ઐ",
    options: ['ai', 'i', 'au', 'u'],
    correct: "ai",
  },
  {
    id: "878",
    question: "ઓ",
    options: ['o', 'ii', 'aa', 'i'],
    correct: "o",
  },
  {
    id: "879",
    question: "ઔ",
    options: ['au', 'u', 'aa', 'e'],
    correct: "au",
  },
  {
    id: "880",
    question: "અ",
    options: ['a', 'ii', 'uu', 'ai'],
    correct: "a",
  },
  {
    id: "881",
    question: "આ",
    options: ['aa', 'u', 'ii', 'au'],
    correct: "aa",
  },
  {
    id: "882",
    question: "ઇ",
    options: ['i', 'aa', 'ai', 'o'],
    correct: "i",
  },
  {
    id: "883",
    question: "ઈ",
    options: ['ii', 'i', 'uu', 'e'],
    correct: "ii",
  },
  {
    id: "884",
    question: "ઉ",
    options: ['u', 'e', 'o', 'aa'],
    correct: "u",
  },
  {
    id: "885",
    question: "ઊ",
    options: ['uu', 'o', 'aa', 'ai'],
    correct: "uu",
  },
  {
    id: "886",
    question: "એ",
    options: ['e', 'ai', 'i', 'a'],
    correct: "e",
  },
  {
    id: "887",
    question: "ઐ",
    options: ['ai', 'au', 'u', 'ii'],
    correct: "ai",
  },
  {
    id: "888",
    question: "ઓ",
    options: ['o', 'e', 'ii', 'i'],
    correct: "o",
  },
  {
    id: "889",
    question: "ઔ",
    options: ['au', 'ai', 'u', 'a'],
    correct: "au",
  },
  {
    id: "890",
    question: "અ",
    options: ['a', 'ii', 'e', 'u'],
    correct: "a",
  },
  {
    id: "891",
    question: "આ",
    options: ['aa', 'o', 'ai', 'ii'],
    correct: "aa",
  },
  {
    id: "892",
    question: "ઇ",
    options: ['i', 'ai', 'e', 'ii'],
    correct: "i",
  },
  {
    id: "893",
    question: "ઈ",
    options: ['ii', 'e', 'a', 'i'],
    correct: "ii",
  },
  {
    id: "894",
    question: "ઉ",
    options: ['u', 'aa', 'uu', 'a'],
    correct: "u",
  },
  {
    id: "895",
    question: "ઊ",
    options: ['uu', 'a', 'au', 'ii'],
    correct: "uu",
  },
  {
    id: "896",
    question: "એ",
    options: ['e', 'uu', 'aa', 'au'],
    correct: "e",
  },
  {
    id: "897",
    question: "ઐ",
    options: ['ai', 'i', 'aa', 'o'],
    correct: "ai",
  },
  {
    id: "898",
    question: "ઓ",
    options: ['o', 'uu', 'ai', 'ii'],
    correct: "o",
  },
  {
    id: "899",
    question: "ઔ",
    options: ['au', 'e', 'uu', 'ai'],
    correct: "au",
  },
  {
    id: "900",
    question: "અ",
    options: ['a', 'aa', 'uu', 'au'],
    correct: "a",
  },
  {
    id: "901",
    question: "આ",
    options: ['aa', 'u', 'o', 'ii'],
    correct: "aa",
  },
  {
    id: "902",
    question: "ઇ",
    options: ['i', 'uu', 'a', 'aa'],
    correct: "i",
  },
  {
    id: "903",
    question: "ઈ",
    options: ['ii', 'au', 'a', 'e'],
    correct: "ii",
  },
  {
    id: "904",
    question: "ઉ",
    options: ['u', 'o', 'e', 'uu'],
    correct: "u",
  },
  {
    id: "905",
    question: "ઊ",
    options: ['uu', 'aa', 'au', 'a'],
    correct: "uu",
  },
  {
    id: "906",
    question: "એ",
    options: ['e', 'a', 'u', 'i'],
    correct: "e",
  },
  {
    id: "907",
    question: "ઐ",
    options: ['ai', 'uu', 'aa', 'u'],
    correct: "ai",
  },
  {
    id: "908",
    question: "ઓ",
    options: ['o', 'uu', 'ai', 'a'],
    correct: "o",
  },
  {
    id: "909",
    question: "ઔ",
    options: ['au', 'e', 'uu', 'i'],
    correct: "au",
  },
  {
    id: "910",
    question: "અ",
    options: ['a', 'ii', 'au', 'aa'],
    correct: "a",
  },
  {
    id: "911",
    question: "આ",
    options: ['aa', 'au', 'o', 'a'],
    correct: "aa",
  },
  {
    id: "912",
    question: "ઇ",
    options: ['i', 'o', 'e', 'u'],
    correct: "i",
  },
  {
    id: "913",
    question: "ઈ",
    options: ['ii', 'u', 'ai', 'aa'],
    correct: "ii",
  },
  {
    id: "914",
    question: "ઉ",
    options: ['u', 'uu', 'e', 'ii'],
    correct: "u",
  },
  {
    id: "915",
    question: "ઊ",
    options: ['uu', 'aa', 'u', 'ii'],
    correct: "uu",
  },
  {
    id: "916",
    question: "એ",
    options: ['e', 'au', 'u', 'aa'],
    correct: "e",
  },
  {
    id: "917",
    question: "ઐ",
    options: ['ai', 'i', 'u', 'uu'],
    correct: "ai",
  },
  {
    id: "918",
    question: "ઓ",
    options: ['o', 'uu', 'ai', 'e'],
    correct: "o",
  },
  {
    id: "919",
    question: "ઔ",
    options: ['au', 'uu', 'o', 'aa'],
    correct: "au",
  },
  {
    id: "920",
    question: "અ",
    options: ['a', 'uu', 'ai', 'aa'],
    correct: "a",
  },
  {
    id: "921",
    question: "આ",
    options: ['aa', 'au', 'a', 'e'],
    correct: "aa",
  },
  {
    id: "922",
    question: "ઇ",
    options: ['i', 'u', 'ai', 'a'],
    correct: "i",
  },
  {
    id: "923",
    question: "ઈ",
    options: ['ii', 'ai', 'o', 'aa'],
    correct: "ii",
  },
  {
    id: "924",
    question: "ઉ",
    options: ['u', 'e', 'au', 'o'],
    correct: "u",
  },
  {
    id: "925",
    question: "ઊ",
    options: ['uu', 'au', 'aa', 'o'],
    correct: "uu",
  },
  {
    id: "926",
    question: "એ",
    options: ['e', 'aa', 'au', 'u'],
    correct: "e",
  },
  {
    id: "927",
    question: "ઐ",
    options: ['ai', 'aa', 'ii', 'uu'],
    correct: "ai",
  },
  {
    id: "928",
    question: "ઓ",
    options: ['o', 'ii', 'u', 'a'],
    correct: "o",
  },
  {
    id: "929",
    question: "ઔ",
    options: ['au', 'o', 'ai', 'u'],
    correct: "au",
  },
  {
    id: "930",
    question: "અ",
    options: ['a', 'ii', 'uu', 'i'],
    correct: "a",
  },
  {
    id: "931",
    question: "આ",
    options: ['aa', 'uu', 'au', 'o'],
    correct: "aa",
  },
  {
    id: "932",
    question: "ઇ",
    options: ['i', 'ii', 'au', 'e'],
    correct: "i",
  },
  {
    id: "933",
    question: "ઈ",
    options: ['ii', 'a', 'ai', 'aa'],
    correct: "ii",
  },
  {
    id: "934",
    question: "ઉ",
    options: ['u', 'uu', 'o', 'ii'],
    correct: "u",
  },
  {
    id: "935",
    question: "ઊ",
    options: ['uu', 'ii', 'ai', 'i'],
    correct: "uu",
  },
  {
    id: "936",
    question: "એ",
    options: ['e', 'o', 'uu', 'aa'],
    correct: "e",
  },
  {
    id: "937",
    question: "ઐ",
    options: ['ai', 'a', 'ii', 'o'],
    correct: "ai",
  },
  {
    id: "938",
    question: "ઓ",
    options: ['o', 'ai', 'ii', 'uu'],
    correct: "o",
  },
  {
    id: "939",
    question: "ઔ",
    options: ['au', 'u', 'aa', 'uu'],
    correct: "au",
  },
  {
    id: "940",
    question: "અ",
    options: ['a', 'e', 'aa', 'ai'],
    correct: "a",
  },
  {
    id: "941",
    question: "આ",
    options: ['aa', 'ii', 'uu', 'i'],
    correct: "aa",
  },
  {
    id: "942",
    question: "ઇ",
    options: ['i', 'au', 'u', 'o'],
    correct: "i",
  },
  {
    id: "943",
    question: "ઈ",
    options: ['ii', 'i', 'ai', 'a'],
    correct: "ii",
  },
  {
    id: "944",
    question: "ઉ",
    options: ['u', 'o', 'ii', 'aa'],
    correct: "u",
  },
  {
    id: "945",
    question: "ઊ",
    options: ['uu', 'aa', 'ai', 'a'],
    correct: "uu",
  },
  {
    id: "946",
    question: "એ",
    options: ['e', 'ai', 'au', 'a'],
    correct: "e",
  },
  {
    id: "947",
    question: "ઐ",
    options: ['ai', 'o', 'au', 'e'],
    correct: "ai",
  },
  {
    id: "948",
    question: "ઓ",
    options: ['o', 'uu', 'a', 'e'],
    correct: "o",
  },
  {
    id: "949",
    question: "ઔ",
    options: ['au', 'e', 'u', 'o'],
    correct: "au",
  },
  {
    id: "950",
    question: "અ",
    options: ['a', 'e', 'aa', 'u'],
    correct: "a",
  },
  {
    id: "951",
    question: "આ",
    options: ['aa', 'a', 'o', 'uu'],
    correct: "aa",
  },
  {
    id: "952",
    question: "ઇ",
    options: ['i', 'a', 'au', 'ii'],
    correct: "i",
  },
  {
    id: "953",
    question: "ઈ",
    options: ['ii', 'uu', 'ai', 'i'],
    correct: "ii",
  },
  {
    id: "954",
    question: "ઉ",
    options: ['u', 'a', 'au', 'ii'],
    correct: "u",
  },
  {
    id: "955",
    question: "ઊ",
    options: ['uu', 'ii', 'u', 'e'],
    correct: "uu",
  },
  {
    id: "956",
    question: "એ",
    options: ['e', 'u', 'i', 'uu'],
    correct: "e",
  },
  {
    id: "957",
    question: "ઐ",
    options: ['ai', 'e', 'aa', 'au'],
    correct: "ai",
  },
  {
    id: "958",
    question: "ઓ",
    options: ['o', 'i', 'au', 'a'],
    correct: "o",
  },
  {
    id: "959",
    question: "ઔ",
    options: ['au', 'u', 'aa', 'o'],
    correct: "au",
  },
  {
    id: "960",
    question: "અ",
    options: ['a', 'i', 'uu', 'ii'],
    correct: "a",
  },
  {
    id: "961",
    question: "આ",
    options: ['aa', 'i', 'ai', 'au'],
    correct: "aa",
  },
  {
    id: "962",
    question: "ઇ",
    options: ['i', 'u', 'au', 'aa'],
    correct: "i",
  },
  {
    id: "963",
    question: "ઈ",
    options: ['ii', 'e', 'ai', 'o'],
    correct: "ii",
  },
  {
    id: "964",
    question: "ઉ",
    options: ['u', 'i', 'uu', 'aa'],
    correct: "u",
  },
  {
    id: "965",
    question: "ઊ",
    options: ['uu', 'o', 'e', 'i'],
    correct: "uu",
  },
  {
    id: "966",
    question: "એ",
    options: ['e', 'ai', 'u', 'o'],
    correct: "e",
  },
  {
    id: "967",
    question: "ઐ",
    options: ['ai', 'ii', 'a', 'au'],
    correct: "ai",
  },
  {
    id: "968",
    question: "ઓ",
    options: ['o', 'e', 'au', 'aa'],
    correct: "o",
  },
  {
    id: "969",
    question: "ઔ",
    options: ['au', 'aa', 'uu', 'a'],
    correct: "au",
  },
  {
    id: "970",
    question: "અ",
    options: ['a', 'e', 'ii', 'aa'],
    correct: "a",
  },
  {
    id: "971",
    question: "આ",
    options: ['aa', 'e', 'o', 'uu'],
    correct: "aa",
  },
  {
    id: "972",
    question: "ઇ",
    options: ['i', 'aa', 'u', 'ii'],
    correct: "i",
  },
  {
    id: "973",
    question: "ઈ",
    options: ['ii', 'au', 'i', 'uu'],
    correct: "ii",
  },
  {
    id: "974",
    question: "ઉ",
    options: ['u', 'aa', 'uu', 'au'],
    correct: "u",
  },
  {
    id: "975",
    question: "ઊ",
    options: ['uu', 'ii', 'au', 'i'],
    correct: "uu",
  },
  {
    id: "976",
    question: "એ",
    options: ['e', 'ii', 'u', 'au'],
    correct: "e",
  },
  {
    id: "977",
    question: "ઐ",
    options: ['ai', 'i', 'uu', 'o'],
    correct: "ai",
  },
  {
    id: "978",
    question: "ઓ",
    options: ['o', 'ai', 'e', 'a'],
    correct: "o",
  },
  {
    id: "979",
    question: "ઔ",
    options: ['au', 'ii', 'aa', 'ai'],
    correct: "au",
  },
  {
    id: "980",
    question: "અ",
    options: ['a', 'uu', 'u', 'i'],
    correct: "a",
  },
  {
    id: "981",
    question: "આ",
    options: ['aa', 'ii', 'o', 'u'],
    correct: "aa",
  },
  {
    id: "982",
    question: "ઇ",
    options: ['i', 'o', 'uu', 'aa'],
    correct: "i",
  },
  {
    id: "983",
    question: "ઈ",
    options: ['ii', 'a', 'u', 'au'],
    correct: "ii",
  },
  {
    id: "984",
    question: "ઉ",
    options: ['u', 'aa', 'a', 'ii'],
    correct: "u",
  },
  {
    id: "985",
    question: "ઊ",
    options: ['uu', 'a', 'au', 'ai'],
    correct: "uu",
  },
  {
    id: "986",
    question: "એ",
    options: ['e', 'u', 'i', 'ai'],
    correct: "e",
  },
  {
    id: "987",
    question: "ઐ",
    options: ['ai', 'u', 'uu', 'i'],
    correct: "ai",
  },
  {
    id: "988",
    question: "ઓ",
    options: ['o', 'ai', 'au', 'aa'],
    correct: "o",
  },
  {
    id: "989",
    question: "ઔ",
    options: ['au', 'u', 'aa', 'ai'],
    correct: "au",
  },
  {
    id: "990",
    question: "અ",
    options: ['a', 'u', 'o', 'au'],
    correct: "a",
  },
  {
    id: "991",
    question: "આ",
    options: ['aa', 'i', 'o', 'ii'],
    correct: "aa",
  },
  {
    id: "992",
    question: "ઇ",
    options: ['i', 'uu', 'o', 'ai'],
    correct: "i",
  },
  {
    id: "993",
    question: "ઈ",
    options: ['ii', 'au', 'a', 'i'],
    correct: "ii",
  },
  {
    id: "994",
    question: "ઉ",
    options: ['u', 'o', 'ii', 'i'],
    correct: "u",
  },
  {
    id: "995",
    question: "ઊ",
    options: ['uu', 'e', 'aa', 'a'],
    correct: "uu",
  },
  {
    id: "996",
    question: "એ",
    options: ['e', 'uu', 'i', 'u'],
    correct: "e",
  },
  {
    id: "997",
    question: "ઐ",
    options: ['ai', 'uu', 'a', 'u'],
    correct: "ai",
  },
  {
    id: "998",
    question: "ઓ",
    options: ['o', 'ai', 'ii', 'e'],
    correct: "o",
  },
  {
    id: "999",
    question: "ઔ",
    options: ['au', 'o', 'aa', 'a'],
    correct: "au",
  },
];
