const quizArray_level3 = [
  {
    id: "0",
    question: "ચ",
    options: ['cha', 'Na', 'Cha', 'jha'],
    correct: "cha",
  },
  {
    id: "1",
    question: "છ",
    options: ['Cha', 'cha', 'na', 'ja'],
    correct: "Cha",
  },
  {
    id: "2",
    question: "જ",
    options: ['ja', 'jha', 'cha', 'na'],
    correct: "ja",
  },
  {
    id: "3",
    question: "ઝ",
    options: ['jha', 'Cha', 'ja', 'na'],
    correct: "jha",
  },
  {
    id: "4",
    question: "ણ",
    options: ['Na', 'Cha', 'cha', 'jha'],
    correct: "Na",
  },
  {
    id: "5",
    question: "ન",
    options: ['na', 'jha', 'cha', 'ja'],
    correct: "na",
  },
  {
    id: "6",
    question: "ચ",
    options: ['cha', 'ja', 'Cha', 'na'],
    correct: "cha",
  },
  {
    id: "7",
    question: "છ",
    options: ['Cha', 'ja', 'cha', 'Na'],
    correct: "Cha",
  },
  {
    id: "8",
    question: "જ",
    options: ['ja', 'Na', 'Cha', 'jha'],
    correct: "ja",
  },
  {
    id: "9",
    question: "ઝ",
    options: ['jha', 'ja', 'cha', 'Na'],
    correct: "jha",
  },
  {
    id: "10",
    question: "ણ",
    options: ['Na', 'na', 'ja', 'jha'],
    correct: "Na",
  },
  {
    id: "11",
    question: "ન",
    options: ['na', 'Cha', 'Na', 'jha'],
    correct: "na",
  },
  {
    id: "12",
    question: "ચ",
    options: ['cha', 'jha', 'Na', 'Cha'],
    correct: "cha",
  },
  {
    id: "13",
    question: "છ",
    options: ['Cha', 'ja', 'Na', 'jha'],
    correct: "Cha",
  },
  {
    id: "14",
    question: "જ",
    options: ['ja', 'jha', 'Cha', 'na'],
    correct: "ja",
  },
  {
    id: "15",
    question: "ઝ",
    options: ['jha', 'ja', 'cha', 'na'],
    correct: "jha",
  },
  {
    id: "16",
    question: "ણ",
    options: ['Na', 'Cha', 'cha', 'jha'],
    correct: "Na",
  },
  {
    id: "17",
    question: "ન",
    options: ['na', 'cha', 'Cha', 'Na'],
    correct: "na",
  },
  {
    id: "18",
    question: "ચ",
    options: ['cha', 'ja', 'Na', 'Cha'],
    correct: "cha",
  },
  {
    id: "19",
    question: "છ",
    options: ['Cha', 'na', 'Na', 'ja'],
    correct: "Cha",
  },
  {
    id: "20",
    question: "જ",
    options: ['ja', 'cha', 'Na', 'na'],
    correct: "ja",
  },
  {
    id: "21",
    question: "ઝ",
    options: ['jha', 'Na', 'Cha', 'cha'],
    correct: "jha",
  },
  {
    id: "22",
    question: "ણ",
    options: ['Na', 'Cha', 'cha', 'na'],
    correct: "Na",
  },
  {
    id: "23",
    question: "ન",
    options: ['na', 'cha', 'ja', 'Cha'],
    correct: "na",
  },
  {
    id: "24",
    question: "ચ",
    options: ['cha', 'Na', 'jha', 'Cha'],
    correct: "cha",
  },
  {
    id: "25",
    question: "છ",
    options: ['Cha', 'jha', 'cha', 'Na'],
    correct: "Cha",
  },
  {
    id: "26",
    question: "જ",
    options: ['ja', 'na', 'Cha', 'jha'],
    correct: "ja",
  },
  {
    id: "27",
    question: "ઝ",
    options: ['jha', 'na', 'ja', 'cha'],
    correct: "jha",
  },
  {
    id: "28",
    question: "ણ",
    options: ['Na', 'na', 'ja', 'Cha'],
    correct: "Na",
  },
  {
    id: "29",
    question: "ન",
    options: ['na', 'jha', 'ja', 'Na'],
    correct: "na",
  },
  {
    id: "30",
    question: "ચ",
    options: ['cha', 'jha', 'Cha', 'ja'],
    correct: "cha",
  },
  {
    id: "31",
    question: "છ",
    options: ['Cha', 'jha', 'na', 'Na'],
    correct: "Cha",
  },
  {
    id: "32",
    question: "જ",
    options: ['ja', 'na', 'cha', 'Cha'],
    correct: "ja",
  },
  {
    id: "33",
    question: "ઝ",
    options: ['jha', 'ja', 'Na', 'cha'],
    correct: "jha",
  },
  {
    id: "34",
    question: "ણ",
    options: ['Na', 'Cha', 'na', 'jha'],
    correct: "Na",
  },
  {
    id: "35",
    question: "ન",
    options: ['na', 'ja', 'Na', 'Cha'],
    correct: "na",
  },
  {
    id: "36",
    question: "ચ",
    options: ['cha', 'Cha', 'Na', 'jha'],
    correct: "cha",
  },
  {
    id: "37",
    question: "છ",
    options: ['Cha', 'ja', 'cha', 'Na'],
    correct: "Cha",
  },
  {
    id: "38",
    question: "જ",
    options: ['ja', 'Na', 'jha', 'Cha'],
    correct: "ja",
  },
  {
    id: "39",
    question: "ઝ",
    options: ['jha', 'cha', 'Na', 'Cha'],
    correct: "jha",
  },
  {
    id: "40",
    question: "ણ",
    options: ['Na', 'na', 'Cha', 'ja'],
    correct: "Na",
  },
  {
    id: "41",
    question: "ન",
    options: ['na', 'cha', 'Cha', 'ja'],
    correct: "na",
  },
  {
    id: "42",
    question: "ચ",
    options: ['cha', 'Cha', 'na', 'ja'],
    correct: "cha",
  },
  {
    id: "43",
    question: "છ",
    options: ['Cha', 'cha', 'jha', 'ja'],
    correct: "Cha",
  },
  {
    id: "44",
    question: "જ",
    options: ['ja', 'jha', 'na', 'cha'],
    correct: "ja",
  },
  {
    id: "45",
    question: "ઝ",
    options: ['jha', 'Na', 'Cha', 'ja'],
    correct: "jha",
  },
  {
    id: "46",
    question: "ણ",
    options: ['Na', 'na', 'Cha', 'ja'],
    correct: "Na",
  },
  {
    id: "47",
    question: "ન",
    options: ['na', 'cha', 'Na', 'Cha'],
    correct: "na",
  },
  {
    id: "48",
    question: "ચ",
    options: ['cha', 'Na', 'jha', 'Cha'],
    correct: "cha",
  },
  {
    id: "49",
    question: "છ",
    options: ['Cha', 'ja', 'na', 'Na'],
    correct: "Cha",
  },
  {
    id: "50",
    question: "જ",
    options: ['ja', 'Cha', 'Na', 'jha'],
    correct: "ja",
  },
  {
    id: "51",
    question: "ઝ",
    options: ['jha', 'Cha', 'na', 'cha'],
    correct: "jha",
  },
  {
    id: "52",
    question: "ણ",
    options: ['Na', 'ja', 'jha', 'Cha'],
    correct: "Na",
  },
  {
    id: "53",
    question: "ન",
    options: ['na', 'cha', 'jha', 'ja'],
    correct: "na",
  },
  {
    id: "54",
    question: "ચ",
    options: ['cha', 'Na', 'Cha', 'ja'],
    correct: "cha",
  },
  {
    id: "55",
    question: "છ",
    options: ['Cha', 'cha', 'ja', 'jha'],
    correct: "Cha",
  },
  {
    id: "56",
    question: "જ",
    options: ['ja', 'Na', 'jha', 'Cha'],
    correct: "ja",
  },
  {
    id: "57",
    question: "ઝ",
    options: ['jha', 'Na', 'na', 'ja'],
    correct: "jha",
  },
  {
    id: "58",
    question: "ણ",
    options: ['Na', 'na', 'ja', 'Cha'],
    correct: "Na",
  },
  {
    id: "59",
    question: "ન",
    options: ['na', 'cha', 'Cha', 'Na'],
    correct: "na",
  },
  {
    id: "60",
    question: "ચ",
    options: ['cha', 'Cha', 'jha', 'ja'],
    correct: "cha",
  },
  {
    id: "61",
    question: "છ",
    options: ['Cha', 'Na', 'na', 'cha'],
    correct: "Cha",
  },
  {
    id: "62",
    question: "જ",
    options: ['ja', 'na', 'Cha', 'jha'],
    correct: "ja",
  },
  {
    id: "63",
    question: "ઝ",
    options: ['jha', 'na', 'ja', 'Cha'],
    correct: "jha",
  },
  {
    id: "64",
    question: "ણ",
    options: ['Na', 'cha', 'Cha', 'jha'],
    correct: "Na",
  },
  {
    id: "65",
    question: "ન",
    options: ['na', 'cha', 'Na', 'ja'],
    correct: "na",
  },
  {
    id: "66",
    question: "ચ",
    options: ['cha', 'Na', 'na', 'ja'],
    correct: "cha",
  },
  {
    id: "67",
    question: "છ",
    options: ['Cha', 'ja', 'jha', 'na'],
    correct: "Cha",
  },
  {
    id: "68",
    question: "જ",
    options: ['ja', 'Cha', 'na', 'jha'],
    correct: "ja",
  },
  {
    id: "69",
    question: "ઝ",
    options: ['jha', 'ja', 'Na', 'cha'],
    correct: "jha",
  },
  {
    id: "70",
    question: "ણ",
    options: ['Na', 'cha', 'na', 'Cha'],
    correct: "Na",
  },
  {
    id: "71",
    question: "ન",
    options: ['na', 'Na', 'jha', 'ja'],
    correct: "na",
  },
  {
    id: "72",
    question: "ચ",
    options: ['cha', 'na', 'ja', 'jha'],
    correct: "cha",
  },
  {
    id: "73",
    question: "છ",
    options: ['Cha', 'Na', 'na', 'jha'],
    correct: "Cha",
  },
  {
    id: "74",
    question: "જ",
    options: ['ja', 'Cha', 'jha', 'cha'],
    correct: "ja",
  },
  {
    id: "75",
    question: "ઝ",
    options: ['jha', 'cha', 'Cha', 'Na'],
    correct: "jha",
  },
  {
    id: "76",
    question: "ણ",
    options: ['Na', 'cha', 'na', 'jha'],
    correct: "Na",
  },
  {
    id: "77",
    question: "ન",
    options: ['na', 'Cha', 'ja', 'Na'],
    correct: "na",
  },
  {
    id: "78",
    question: "ચ",
    options: ['cha', 'jha', 'ja', 'na'],
    correct: "cha",
  },
  {
    id: "79",
    question: "છ",
    options: ['Cha', 'cha', 'ja', 'Na'],
    correct: "Cha",
  },
  {
    id: "80",
    question: "જ",
    options: ['ja', 'jha', 'Na', 'cha'],
    correct: "ja",
  },
  {
    id: "81",
    question: "ઝ",
    options: ['jha', 'Na', 'Cha', 'na'],
    correct: "jha",
  },
  {
    id: "82",
    question: "ણ",
    options: ['Na', 'ja', 'na', 'jha'],
    correct: "Na",
  },
  {
    id: "83",
    question: "ન",
    options: ['na', 'Cha', 'Na', 'ja'],
    correct: "na",
  },
  {
    id: "84",
    question: "ચ",
    options: ['cha', 'na', 'ja', 'jha'],
    correct: "cha",
  },
  {
    id: "85",
    question: "છ",
    options: ['Cha', 'ja', 'na', 'Na'],
    correct: "Cha",
  },
  {
    id: "86",
    question: "જ",
    options: ['ja', 'jha', 'cha', 'Cha'],
    correct: "ja",
  },
  {
    id: "87",
    question: "ઝ",
    options: ['jha', 'Cha', 'Na', 'na'],
    correct: "jha",
  },
  {
    id: "88",
    question: "ણ",
    options: ['Na', 'na', 'jha', 'ja'],
    correct: "Na",
  },
  {
    id: "89",
    question: "ન",
    options: ['na', 'Cha', 'jha', 'cha'],
    correct: "na",
  },
  {
    id: "90",
    question: "ચ",
    options: ['cha', 'Na', 'na', 'ja'],
    correct: "cha",
  },
  {
    id: "91",
    question: "છ",
    options: ['Cha', 'ja', 'na', 'Na'],
    correct: "Cha",
  },
  {
    id: "92",
    question: "જ",
    options: ['ja', 'cha', 'Na', 'jha'],
    correct: "ja",
  },
  {
    id: "93",
    question: "ઝ",
    options: ['jha', 'cha', 'Na', 'na'],
    correct: "jha",
  },
  {
    id: "94",
    question: "ણ",
    options: ['Na', 'na', 'cha', 'jha'],
    correct: "Na",
  },
  {
    id: "95",
    question: "ન",
    options: ['na', 'Na', 'jha', 'ja'],
    correct: "na",
  },
  {
    id: "96",
    question: "ચ",
    options: ['cha', 'Cha', 'ja', 'jha'],
    correct: "cha",
  },
  {
    id: "97",
    question: "છ",
    options: ['Cha', 'jha', 'ja', 'na'],
    correct: "Cha",
  },
  {
    id: "98",
    question: "જ",
    options: ['ja', 'na', 'Na', 'Cha'],
    correct: "ja",
  },
  {
    id: "99",
    question: "ઝ",
    options: ['jha', 'Cha', 'Na', 'cha'],
    correct: "jha",
  },
  {
    id: "100",
    question: "ણ",
    options: ['Na', 'cha', 'jha', 'na'],
    correct: "Na",
  },
  {
    id: "101",
    question: "ન",
    options: ['na', 'Cha', 'cha', 'Na'],
    correct: "na",
  },
  {
    id: "102",
    question: "ચ",
    options: ['cha', 'ja', 'na', 'jha'],
    correct: "cha",
  },
  {
    id: "103",
    question: "છ",
    options: ['Cha', 'na', 'jha', 'cha'],
    correct: "Cha",
  },
  {
    id: "104",
    question: "જ",
    options: ['ja', 'jha', 'na', 'cha'],
    correct: "ja",
  },
  {
    id: "105",
    question: "ઝ",
    options: ['jha', 'ja', 'Na', 'cha'],
    correct: "jha",
  },
  {
    id: "106",
    question: "ણ",
    options: ['Na', 'Cha', 'cha', 'jha'],
    correct: "Na",
  },
  {
    id: "107",
    question: "ન",
    options: ['na', 'jha', 'cha', 'ja'],
    correct: "na",
  },
  {
    id: "108",
    question: "ચ",
    options: ['cha', 'jha', 'Na', 'ja'],
    correct: "cha",
  },
  {
    id: "109",
    question: "છ",
    options: ['Cha', 'jha', 'Na', 'cha'],
    correct: "Cha",
  },
  {
    id: "110",
    question: "જ",
    options: ['ja', 'na', 'Cha', 'jha'],
    correct: "ja",
  },
  {
    id: "111",
    question: "ઝ",
    options: ['jha', 'Na', 'Cha', 'na'],
    correct: "jha",
  },
  {
    id: "112",
    question: "ણ",
    options: ['Na', 'Cha', 'ja', 'na'],
    correct: "Na",
  },
  {
    id: "113",
    question: "ન",
    options: ['na', 'jha', 'Cha', 'cha'],
    correct: "na",
  },
  {
    id: "114",
    question: "ચ",
    options: ['cha', 'na', 'Cha', 'Na'],
    correct: "cha",
  },
  {
    id: "115",
    question: "છ",
    options: ['Cha', 'cha', 'ja', 'jha'],
    correct: "Cha",
  },
  {
    id: "116",
    question: "જ",
    options: ['ja', 'jha', 'Na', 'Cha'],
    correct: "ja",
  },
  {
    id: "117",
    question: "ઝ",
    options: ['jha', 'Na', 'ja', 'cha'],
    correct: "jha",
  },
  {
    id: "118",
    question: "ણ",
    options: ['Na', 'na', 'jha', 'cha'],
    correct: "Na",
  },
  {
    id: "119",
    question: "ન",
    options: ['na', 'jha', 'ja', 'Cha'],
    correct: "na",
  },
  {
    id: "120",
    question: "ચ",
    options: ['cha', 'jha', 'na', 'ja'],
    correct: "cha",
  },
  {
    id: "121",
    question: "છ",
    options: ['Cha', 'jha', 'na', 'Na'],
    correct: "Cha",
  },
  {
    id: "122",
    question: "જ",
    options: ['ja', 'cha', 'jha', 'Na'],
    correct: "ja",
  },
  {
    id: "123",
    question: "ઝ",
    options: ['jha', 'Na', 'Cha', 'cha'],
    correct: "jha",
  },
  {
    id: "124",
    question: "ણ",
    options: ['Na', 'na', 'jha', 'Cha'],
    correct: "Na",
  },
  {
    id: "125",
    question: "ન",
    options: ['na', 'Cha', 'cha', 'ja'],
    correct: "na",
  },
  {
    id: "126",
    question: "ચ",
    options: ['cha', 'ja', 'jha', 'Cha'],
    correct: "cha",
  },
  {
    id: "127",
    question: "છ",
    options: ['Cha', 'na', 'cha', 'jha'],
    correct: "Cha",
  },
  {
    id: "128",
    question: "જ",
    options: ['ja', 'jha', 'cha', 'Cha'],
    correct: "ja",
  },
  {
    id: "129",
    question: "ઝ",
    options: ['jha', 'cha', 'ja', 'Cha'],
    correct: "jha",
  },
  {
    id: "130",
    question: "ણ",
    options: ['Na', 'na', 'jha', 'ja'],
    correct: "Na",
  },
  {
    id: "131",
    question: "ન",
    options: ['na', 'Na', 'jha', 'ja'],
    correct: "na",
  },
  {
    id: "132",
    question: "ચ",
    options: ['cha', 'Na', 'jha', 'ja'],
    correct: "cha",
  },
  {
    id: "133",
    question: "છ",
    options: ['Cha', 'jha', 'cha', 'na'],
    correct: "Cha",
  },
  {
    id: "134",
    question: "જ",
    options: ['ja', 'Na', 'na', 'jha'],
    correct: "ja",
  },
  {
    id: "135",
    question: "ઝ",
    options: ['jha', 'cha', 'Cha', 'Na'],
    correct: "jha",
  },
  {
    id: "136",
    question: "ણ",
    options: ['Na', 'Cha', 'ja', 'jha'],
    correct: "Na",
  },
  {
    id: "137",
    question: "ન",
    options: ['na', 'cha', 'ja', 'jha'],
    correct: "na",
  },
  {
    id: "138",
    question: "ચ",
    options: ['cha', 'na', 'Cha', 'ja'],
    correct: "cha",
  },
  {
    id: "139",
    question: "છ",
    options: ['Cha', 'na', 'jha', 'Na'],
    correct: "Cha",
  },
  {
    id: "140",
    question: "જ",
    options: ['ja', 'Cha', 'jha', 'Na'],
    correct: "ja",
  },
  {
    id: "141",
    question: "ઝ",
    options: ['jha', 'Cha', 'na', 'cha'],
    correct: "jha",
  },
  {
    id: "142",
    question: "ણ",
    options: ['Na', 'na', 'Cha', 'cha'],
    correct: "Na",
  },
  {
    id: "143",
    question: "ન",
    options: ['na', 'cha', 'ja', 'Cha'],
    correct: "na",
  },
  {
    id: "144",
    question: "ચ",
    options: ['cha', 'Cha', 'ja', 'na'],
    correct: "cha",
  },
  {
    id: "145",
    question: "છ",
    options: ['Cha', 'na', 'cha', 'ja'],
    correct: "Cha",
  },
  {
    id: "146",
    question: "જ",
    options: ['ja', 'Na', 'cha', 'jha'],
    correct: "ja",
  },
  {
    id: "147",
    question: "ઝ",
    options: ['jha', 'cha', 'Na', 'Cha'],
    correct: "jha",
  },
  {
    id: "148",
    question: "ણ",
    options: ['Na', 'Cha', 'ja', 'cha'],
    correct: "Na",
  },
  {
    id: "149",
    question: "ન",
    options: ['na', 'Cha', 'ja', 'cha'],
    correct: "na",
  },
  {
    id: "150",
    question: "ચ",
    options: ['cha', 'Cha', 'ja', 'Na'],
    correct: "cha",
  },
  {
    id: "151",
    question: "છ",
    options: ['Cha', 'na', 'Na', 'jha'],
    correct: "Cha",
  },
  {
    id: "152",
    question: "જ",
    options: ['ja', 'cha', 'Na', 'Cha'],
    correct: "ja",
  },
  {
    id: "153",
    question: "ઝ",
    options: ['jha', 'Na', 'cha', 'na'],
    correct: "jha",
  },
  {
    id: "154",
    question: "ણ",
    options: ['Na', 'na', 'jha', 'cha'],
    correct: "Na",
  },
  {
    id: "155",
    question: "ન",
    options: ['na', 'Na', 'cha', 'Cha'],
    correct: "na",
  },
  {
    id: "156",
    question: "ચ",
    options: ['cha', 'ja', 'jha', 'na'],
    correct: "cha",
  },
  {
    id: "157",
    question: "છ",
    options: ['Cha', 'Na', 'na', 'cha'],
    correct: "Cha",
  },
  {
    id: "158",
    question: "જ",
    options: ['ja', 'cha', 'na', 'jha'],
    correct: "ja",
  },
  {
    id: "159",
    question: "ઝ",
    options: ['jha', 'ja', 'Na', 'na'],
    correct: "jha",
  },
  {
    id: "160",
    question: "ણ",
    options: ['Na', 'ja', 'Cha', 'cha'],
    correct: "Na",
  },
  {
    id: "161",
    question: "ન",
    options: ['na', 'Cha', 'jha', 'Na'],
    correct: "na",
  },
  {
    id: "162",
    question: "ચ",
    options: ['cha', 'ja', 'Na', 'na'],
    correct: "cha",
  },
  {
    id: "163",
    question: "છ",
    options: ['Cha', 'Na', 'na', 'jha'],
    correct: "Cha",
  },
  {
    id: "164",
    question: "જ",
    options: ['ja', 'Na', 'cha', 'jha'],
    correct: "ja",
  },
  {
    id: "165",
    question: "ઝ",
    options: ['jha', 'ja', 'Cha', 'na'],
    correct: "jha",
  },
  {
    id: "166",
    question: "ણ",
    options: ['Na', 'jha', 'Cha', 'cha'],
    correct: "Na",
  },
  {
    id: "167",
    question: "ન",
    options: ['na', 'Cha', 'jha', 'ja'],
    correct: "na",
  },
  {
    id: "168",
    question: "ચ",
    options: ['cha', 'Na', 'jha', 'na'],
    correct: "cha",
  },
  {
    id: "169",
    question: "છ",
    options: ['Cha', 'cha', 'jha', 'Na'],
    correct: "Cha",
  },
  {
    id: "170",
    question: "જ",
    options: ['ja', 'Na', 'Cha', 'cha'],
    correct: "ja",
  },
  {
    id: "171",
    question: "ઝ",
    options: ['jha', 'ja', 'na', 'cha'],
    correct: "jha",
  },
  {
    id: "172",
    question: "ણ",
    options: ['Na', 'Cha', 'jha', 'ja'],
    correct: "Na",
  },
  {
    id: "173",
    question: "ન",
    options: ['na', 'jha', 'ja', 'Na'],
    correct: "na",
  },
  {
    id: "174",
    question: "ચ",
    options: ['cha', 'Cha', 'na', 'ja'],
    correct: "cha",
  },
  {
    id: "175",
    question: "છ",
    options: ['Cha', 'ja', 'na', 'jha'],
    correct: "Cha",
  },
  {
    id: "176",
    question: "જ",
    options: ['ja', 'na', 'Cha', 'jha'],
    correct: "ja",
  },
  {
    id: "177",
    question: "ઝ",
    options: ['jha', 'ja', 'Cha', 'Na'],
    correct: "jha",
  },
  {
    id: "178",
    question: "ણ",
    options: ['Na', 'jha', 'Cha', 'na'],
    correct: "Na",
  },
  {
    id: "179",
    question: "ન",
    options: ['na', 'Na', 'cha', 'jha'],
    correct: "na",
  },
  {
    id: "180",
    question: "ચ",
    options: ['cha', 'ja', 'jha', 'na'],
    correct: "cha",
  },
  {
    id: "181",
    question: "છ",
    options: ['Cha', 'na', 'jha', 'cha'],
    correct: "Cha",
  },
  {
    id: "182",
    question: "જ",
    options: ['ja', 'Na', 'na', 'cha'],
    correct: "ja",
  },
  {
    id: "183",
    question: "ઝ",
    options: ['jha', 'cha', 'ja', 'Na'],
    correct: "jha",
  },
  {
    id: "184",
    question: "ણ",
    options: ['Na', 'ja', 'na', 'cha'],
    correct: "Na",
  },
  {
    id: "185",
    question: "ન",
    options: ['na', 'ja', 'Na', 'jha'],
    correct: "na",
  },
  {
    id: "186",
    question: "ચ",
    options: ['cha', 'jha', 'ja', 'Na'],
    correct: "cha",
  },
  {
    id: "187",
    question: "છ",
    options: ['Cha', 'ja', 'jha', 'Na'],
    correct: "Cha",
  },
  {
    id: "188",
    question: "જ",
    options: ['ja', 'Cha', 'cha', 'na'],
    correct: "ja",
  },
  {
    id: "189",
    question: "ઝ",
    options: ['jha', 'Cha', 'ja', 'na'],
    correct: "jha",
  },
  {
    id: "190",
    question: "ણ",
    options: ['Na', 'ja', 'jha', 'na'],
    correct: "Na",
  },
  {
    id: "191",
    question: "ન",
    options: ['na', 'ja', 'cha', 'jha'],
    correct: "na",
  },
  {
    id: "192",
    question: "ચ",
    options: ['cha', 'Na', 'ja', 'jha'],
    correct: "cha",
  },
  {
    id: "193",
    question: "છ",
    options: ['Cha', 'na', 'ja', 'jha'],
    correct: "Cha",
  },
  {
    id: "194",
    question: "જ",
    options: ['ja', 'na', 'cha', 'Cha'],
    correct: "ja",
  },
  {
    id: "195",
    question: "ઝ",
    options: ['jha', 'cha', 'na', 'ja'],
    correct: "jha",
  },
  {
    id: "196",
    question: "ણ",
    options: ['Na', 'na', 'jha', 'Cha'],
    correct: "Na",
  },
  {
    id: "197",
    question: "ન",
    options: ['na', 'Cha', 'Na', 'cha'],
    correct: "na",
  },
  {
    id: "198",
    question: "ચ",
    options: ['cha', 'Na', 'ja', 'Cha'],
    correct: "cha",
  },
  {
    id: "199",
    question: "છ",
    options: ['Cha', 'na', 'cha', 'Na'],
    correct: "Cha",
  },
  {
    id: "200",
    question: "જ",
    options: ['ja', 'na', 'Cha', 'cha'],
    correct: "ja",
  },
  {
    id: "201",
    question: "ઝ",
    options: ['jha', 'ja', 'cha', 'na'],
    correct: "jha",
  },
  {
    id: "202",
    question: "ણ",
    options: ['Na', 'cha', 'jha', 'na'],
    correct: "Na",
  },
  {
    id: "203",
    question: "ન",
    options: ['na', 'Cha', 'ja', 'cha'],
    correct: "na",
  },
  {
    id: "204",
    question: "ચ",
    options: ['cha', 'ja', 'Cha', 'Na'],
    correct: "cha",
  },
  {
    id: "205",
    question: "છ",
    options: ['Cha', 'cha', 'Na', 'na'],
    correct: "Cha",
  },
  {
    id: "206",
    question: "જ",
    options: ['ja', 'na', 'cha', 'Cha'],
    correct: "ja",
  },
  {
    id: "207",
    question: "ઝ",
    options: ['jha', 'Cha', 'na', 'cha'],
    correct: "jha",
  },
  {
    id: "208",
    question: "ણ",
    options: ['Na', 'Cha', 'cha', 'ja'],
    correct: "Na",
  },
  {
    id: "209",
    question: "ન",
    options: ['na', 'Cha', 'ja', 'cha'],
    correct: "na",
  },
  {
    id: "210",
    question: "ચ",
    options: ['cha', 'ja', 'Cha', 'na'],
    correct: "cha",
  },
  {
    id: "211",
    question: "છ",
    options: ['Cha', 'na', 'jha', 'cha'],
    correct: "Cha",
  },
  {
    id: "212",
    question: "જ",
    options: ['ja', 'na', 'jha', 'Cha'],
    correct: "ja",
  },
  {
    id: "213",
    question: "ઝ",
    options: ['jha', 'ja', 'Na', 'Cha'],
    correct: "jha",
  },
  {
    id: "214",
    question: "ણ",
    options: ['Na', 'na', 'jha', 'cha'],
    correct: "Na",
  },
  {
    id: "215",
    question: "ન",
    options: ['na', 'ja', 'Cha', 'jha'],
    correct: "na",
  },
  {
    id: "216",
    question: "ચ",
    options: ['cha', 'ja', 'Na', 'Cha'],
    correct: "cha",
  },
  {
    id: "217",
    question: "છ",
    options: ['Cha', 'jha', 'na', 'cha'],
    correct: "Cha",
  },
  {
    id: "218",
    question: "જ",
    options: ['ja', 'Na', 'Cha', 'jha'],
    correct: "ja",
  },
  {
    id: "219",
    question: "ઝ",
    options: ['jha', 'Cha', 'cha', 'na'],
    correct: "jha",
  },
  {
    id: "220",
    question: "ણ",
    options: ['Na', 'cha', 'Cha', 'na'],
    correct: "Na",
  },
  {
    id: "221",
    question: "ન",
    options: ['na', 'Na', 'ja', 'Cha'],
    correct: "na",
  },
  {
    id: "222",
    question: "ચ",
    options: ['cha', 'Na', 'Cha', 'na'],
    correct: "cha",
  },
  {
    id: "223",
    question: "છ",
    options: ['Cha', 'ja', 'na', 'cha'],
    correct: "Cha",
  },
  {
    id: "224",
    question: "જ",
    options: ['ja', 'Na', 'na', 'cha'],
    correct: "ja",
  },
  {
    id: "225",
    question: "ઝ",
    options: ['jha', 'Cha', 'Na', 'ja'],
    correct: "jha",
  },
  {
    id: "226",
    question: "ણ",
    options: ['Na', 'jha', 'ja', 'cha'],
    correct: "Na",
  },
  {
    id: "227",
    question: "ન",
    options: ['na', 'Cha', 'jha', 'ja'],
    correct: "na",
  },
  {
    id: "228",
    question: "ચ",
    options: ['cha', 'Na', 'jha', 'Cha'],
    correct: "cha",
  },
  {
    id: "229",
    question: "છ",
    options: ['Cha', 'Na', 'na', 'ja'],
    correct: "Cha",
  },
  {
    id: "230",
    question: "જ",
    options: ['ja', 'na', 'jha', 'Cha'],
    correct: "ja",
  },
  {
    id: "231",
    question: "ઝ",
    options: ['jha', 'Na', 'cha', 'Cha'],
    correct: "jha",
  },
  {
    id: "232",
    question: "ણ",
    options: ['Na', 'cha', 'na', 'jha'],
    correct: "Na",
  },
  {
    id: "233",
    question: "ન",
    options: ['na', 'jha', 'ja', 'Na'],
    correct: "na",
  },
  {
    id: "234",
    question: "ચ",
    options: ['cha', 'Na', 'ja', 'Cha'],
    correct: "cha",
  },
  {
    id: "235",
    question: "છ",
    options: ['Cha', 'jha', 'cha', 'Na'],
    correct: "Cha",
  },
  {
    id: "236",
    question: "જ",
    options: ['ja', 'cha', 'na', 'Na'],
    correct: "ja",
  },
  {
    id: "237",
    question: "ઝ",
    options: ['jha', 'Na', 'ja', 'Cha'],
    correct: "jha",
  },
  {
    id: "238",
    question: "ણ",
    options: ['Na', 'jha', 'na', 'cha'],
    correct: "Na",
  },
  {
    id: "239",
    question: "ન",
    options: ['na', 'Cha', 'Na', 'jha'],
    correct: "na",
  },
  {
    id: "240",
    question: "ચ",
    options: ['cha', 'Na', 'Cha', 'jha'],
    correct: "cha",
  },
  {
    id: "241",
    question: "છ",
    options: ['Cha', 'jha', 'Na', 'na'],
    correct: "Cha",
  },
  {
    id: "242",
    question: "જ",
    options: ['ja', 'cha', 'Na', 'jha'],
    correct: "ja",
  },
  {
    id: "243",
    question: "ઝ",
    options: ['jha', 'ja', 'cha', 'Cha'],
    correct: "jha",
  },
  {
    id: "244",
    question: "ણ",
    options: ['Na', 'na', 'Cha', 'cha'],
    correct: "Na",
  },
  {
    id: "245",
    question: "ન",
    options: ['na', 'ja', 'cha', 'Na'],
    correct: "na",
  },
  {
    id: "246",
    question: "ચ",
    options: ['cha', 'ja', 'Na', 'na'],
    correct: "cha",
  },
  {
    id: "247",
    question: "છ",
    options: ['Cha', 'jha', 'Na', 'cha'],
    correct: "Cha",
  },
  {
    id: "248",
    question: "જ",
    options: ['ja', 'jha', 'cha', 'Cha'],
    correct: "ja",
  },
  {
    id: "249",
    question: "ઝ",
    options: ['jha', 'Cha', 'cha', 'Na'],
    correct: "jha",
  },
  {
    id: "250",
    question: "ણ",
    options: ['Na', 'Cha', 'jha', 'na'],
    correct: "Na",
  },
  {
    id: "251",
    question: "ન",
    options: ['na', 'jha', 'Cha', 'ja'],
    correct: "na",
  },
  {
    id: "252",
    question: "ચ",
    options: ['cha', 'jha', 'na', 'Na'],
    correct: "cha",
  },
  {
    id: "253",
    question: "છ",
    options: ['Cha', 'Na', 'na', 'jha'],
    correct: "Cha",
  },
  {
    id: "254",
    question: "જ",
    options: ['ja', 'Na', 'cha', 'Cha'],
    correct: "ja",
  },
  {
    id: "255",
    question: "ઝ",
    options: ['jha', 'Cha', 'na', 'ja'],
    correct: "jha",
  },
  {
    id: "256",
    question: "ણ",
    options: ['Na', 'Cha', 'jha', 'ja'],
    correct: "Na",
  },
  {
    id: "257",
    question: "ન",
    options: ['na', 'ja', 'Na', 'Cha'],
    correct: "na",
  },
  {
    id: "258",
    question: "ચ",
    options: ['cha', 'Cha', 'na', 'ja'],
    correct: "cha",
  },
  {
    id: "259",
    question: "છ",
    options: ['Cha', 'ja', 'jha', 'Na'],
    correct: "Cha",
  },
  {
    id: "260",
    question: "જ",
    options: ['ja', 'cha', 'jha', 'na'],
    correct: "ja",
  },
  {
    id: "261",
    question: "ઝ",
    options: ['jha', 'cha', 'Na', 'na'],
    correct: "jha",
  },
  {
    id: "262",
    question: "ણ",
    options: ['Na', 'jha', 'Cha', 'ja'],
    correct: "Na",
  },
  {
    id: "263",
    question: "ન",
    options: ['na', 'Na', 'cha', 'ja'],
    correct: "na",
  },
  {
    id: "264",
    question: "ચ",
    options: ['cha', 'Na', 'jha', 'na'],
    correct: "cha",
  },
  {
    id: "265",
    question: "છ",
    options: ['Cha', 'cha', 'jha', 'na'],
    correct: "Cha",
  },
  {
    id: "266",
    question: "જ",
    options: ['ja', 'cha', 'na', 'Na'],
    correct: "ja",
  },
  {
    id: "267",
    question: "ઝ",
    options: ['jha', 'cha', 'Na', 'na'],
    correct: "jha",
  },
  {
    id: "268",
    question: "ણ",
    options: ['Na', 'jha', 'ja', 'na'],
    correct: "Na",
  },
  {
    id: "269",
    question: "ન",
    options: ['na', 'cha', 'Na', 'jha'],
    correct: "na",
  },
  {
    id: "270",
    question: "ચ",
    options: ['cha', 'ja', 'na', 'Cha'],
    correct: "cha",
  },
  {
    id: "271",
    question: "છ",
    options: ['Cha', 'cha', 'na', 'Na'],
    correct: "Cha",
  },
  {
    id: "272",
    question: "જ",
    options: ['ja', 'cha', 'Cha', 'na'],
    correct: "ja",
  },
  {
    id: "273",
    question: "ઝ",
    options: ['jha', 'na', 'cha', 'Cha'],
    correct: "jha",
  },
  {
    id: "274",
    question: "ણ",
    options: ['Na', 'cha', 'ja', 'jha'],
    correct: "Na",
  },
  {
    id: "275",
    question: "ન",
    options: ['na', 'cha', 'Na', 'ja'],
    correct: "na",
  },
  {
    id: "276",
    question: "ચ",
    options: ['cha', 'na', 'Na', 'ja'],
    correct: "cha",
  },
  {
    id: "277",
    question: "છ",
    options: ['Cha', 'Na', 'ja', 'cha'],
    correct: "Cha",
  },
  {
    id: "278",
    question: "જ",
    options: ['ja', 'jha', 'Cha', 'cha'],
    correct: "ja",
  },
  {
    id: "279",
    question: "ઝ",
    options: ['jha', 'cha', 'na', 'ja'],
    correct: "jha",
  },
  {
    id: "280",
    question: "ણ",
    options: ['Na', 'na', 'cha', 'Cha'],
    correct: "Na",
  },
  {
    id: "281",
    question: "ન",
    options: ['na', 'jha', 'ja', 'Cha'],
    correct: "na",
  },
  {
    id: "282",
    question: "ચ",
    options: ['cha', 'jha', 'Na', 'na'],
    correct: "cha",
  },
  {
    id: "283",
    question: "છ",
    options: ['Cha', 'ja', 'na', 'cha'],
    correct: "Cha",
  },
  {
    id: "284",
    question: "જ",
    options: ['ja', 'Na', 'cha', 'jha'],
    correct: "ja",
  },
  {
    id: "285",
    question: "ઝ",
    options: ['jha', 'ja', 'cha', 'Na'],
    correct: "jha",
  },
  {
    id: "286",
    question: "ણ",
    options: ['Na', 'ja', 'na', 'jha'],
    correct: "Na",
  },
  {
    id: "287",
    question: "ન",
    options: ['na', 'jha', 'Na', 'Cha'],
    correct: "na",
  },
  {
    id: "288",
    question: "ચ",
    options: ['cha', 'Na', 'Cha', 'na'],
    correct: "cha",
  },
  {
    id: "289",
    question: "છ",
    options: ['Cha', 'ja', 'Na', 'na'],
    correct: "Cha",
  },
  {
    id: "290",
    question: "જ",
    options: ['ja', 'Na', 'cha', 'jha'],
    correct: "ja",
  },
  {
    id: "291",
    question: "ઝ",
    options: ['jha', 'ja', 'na', 'cha'],
    correct: "jha",
  },
  {
    id: "292",
    question: "ણ",
    options: ['Na', 'cha', 'Cha', 'na'],
    correct: "Na",
  },
  {
    id: "293",
    question: "ન",
    options: ['na', 'cha', 'Cha', 'ja'],
    correct: "na",
  },
  {
    id: "294",
    question: "ચ",
    options: ['cha', 'Cha', 'ja', 'na'],
    correct: "cha",
  },
  {
    id: "295",
    question: "છ",
    options: ['Cha', 'na', 'Na', 'ja'],
    correct: "Cha",
  },
  {
    id: "296",
    question: "જ",
    options: ['ja', 'Na', 'jha', 'cha'],
    correct: "ja",
  },
  {
    id: "297",
    question: "ઝ",
    options: ['jha', 'Na', 'cha', 'na'],
    correct: "jha",
  },
  {
    id: "298",
    question: "ણ",
    options: ['Na', 'jha', 'Cha', 'cha'],
    correct: "Na",
  },
  {
    id: "299",
    question: "ન",
    options: ['na', 'cha', 'Cha', 'Na'],
    correct: "na",
  },
  {
    id: "300",
    question: "ચ",
    options: ['cha', 'jha', 'Na', 'Cha'],
    correct: "cha",
  },
  {
    id: "301",
    question: "છ",
    options: ['Cha', 'ja', 'na', 'Na'],
    correct: "Cha",
  },
  {
    id: "302",
    question: "જ",
    options: ['ja', 'na', 'jha', 'cha'],
    correct: "ja",
  },
  {
    id: "303",
    question: "ઝ",
    options: ['jha', 'na', 'Na', 'Cha'],
    correct: "jha",
  },
  {
    id: "304",
    question: "ણ",
    options: ['Na', 'jha', 'Cha', 'cha'],
    correct: "Na",
  },
  {
    id: "305",
    question: "ન",
    options: ['na', 'jha', 'Na', 'cha'],
    correct: "na",
  },
  {
    id: "306",
    question: "ચ",
    options: ['cha', 'ja', 'Na', 'Cha'],
    correct: "cha",
  },
  {
    id: "307",
    question: "છ",
    options: ['Cha', 'jha', 'ja', 'cha'],
    correct: "Cha",
  },
  {
    id: "308",
    question: "જ",
    options: ['ja', 'na', 'Cha', 'Na'],
    correct: "ja",
  },
  {
    id: "309",
    question: "ઝ",
    options: ['jha', 'cha', 'Na', 'ja'],
    correct: "jha",
  },
  {
    id: "310",
    question: "ણ",
    options: ['Na', 'cha', 'jha', 'ja'],
    correct: "Na",
  },
  {
    id: "311",
    question: "ન",
    options: ['na', 'ja', 'Na', 'cha'],
    correct: "na",
  },
  {
    id: "312",
    question: "ચ",
    options: ['cha', 'Na', 'jha', 'Cha'],
    correct: "cha",
  },
  {
    id: "313",
    question: "છ",
    options: ['Cha', 'Na', 'ja', 'jha'],
    correct: "Cha",
  },
  {
    id: "314",
    question: "જ",
    options: ['ja', 'Cha', 'cha', 'na'],
    correct: "ja",
  },
  {
    id: "315",
    question: "ઝ",
    options: ['jha', 'Cha', 'na', 'Na'],
    correct: "jha",
  },
  {
    id: "316",
    question: "ણ",
    options: ['Na', 'jha', 'cha', 'Cha'],
    correct: "Na",
  },
  {
    id: "317",
    question: "ન",
    options: ['na', 'cha', 'Cha', 'Na'],
    correct: "na",
  },
  {
    id: "318",
    question: "ચ",
    options: ['cha', 'Na', 'ja', 'Cha'],
    correct: "cha",
  },
  {
    id: "319",
    question: "છ",
    options: ['Cha', 'na', 'cha', 'jha'],
    correct: "Cha",
  },
  {
    id: "320",
    question: "જ",
    options: ['ja', 'jha', 'cha', 'na'],
    correct: "ja",
  },
  {
    id: "321",
    question: "ઝ",
    options: ['jha', 'na', 'Na', 'cha'],
    correct: "jha",
  },
  {
    id: "322",
    question: "ણ",
    options: ['Na', 'cha', 'na', 'jha'],
    correct: "Na",
  },
  {
    id: "323",
    question: "ન",
    options: ['na', 'cha', 'ja', 'Cha'],
    correct: "na",
  },
  {
    id: "324",
    question: "ચ",
    options: ['cha', 'jha', 'na', 'Na'],
    correct: "cha",
  },
  {
    id: "325",
    question: "છ",
    options: ['Cha', 'ja', 'Na', 'jha'],
    correct: "Cha",
  },
  {
    id: "326",
    question: "જ",
    options: ['ja', 'Na', 'Cha', 'cha'],
    correct: "ja",
  },
  {
    id: "327",
    question: "ઝ",
    options: ['jha', 'Cha', 'cha', 'Na'],
    correct: "jha",
  },
  {
    id: "328",
    question: "ણ",
    options: ['Na', 'na', 'ja', 'cha'],
    correct: "Na",
  },
  {
    id: "329",
    question: "ન",
    options: ['na', 'Na', 'Cha', 'jha'],
    correct: "na",
  },
  {
    id: "330",
    question: "ચ",
    options: ['cha', 'jha', 'Na', 'ja'],
    correct: "cha",
  },
  {
    id: "331",
    question: "છ",
    options: ['Cha', 'Na', 'na', 'jha'],
    correct: "Cha",
  },
  {
    id: "332",
    question: "જ",
    options: ['ja', 'jha', 'Na', 'cha'],
    correct: "ja",
  },
  {
    id: "333",
    question: "ઝ",
    options: ['jha', 'na', 'ja', 'cha'],
    correct: "jha",
  },
  {
    id: "334",
    question: "ણ",
    options: ['Na', 'Cha', 'na', 'jha'],
    correct: "Na",
  },
  {
    id: "335",
    question: "ન",
    options: ['na', 'Cha', 'Na', 'cha'],
    correct: "na",
  },
  {
    id: "336",
    question: "ચ",
    options: ['cha', 'jha', 'Cha', 'ja'],
    correct: "cha",
  },
  {
    id: "337",
    question: "છ",
    options: ['Cha', 'Na', 'jha', 'ja'],
    correct: "Cha",
  },
  {
    id: "338",
    question: "જ",
    options: ['ja', 'Na', 'cha', 'jha'],
    correct: "ja",
  },
  {
    id: "339",
    question: "ઝ",
    options: ['jha', 'Na', 'ja', 'na'],
    correct: "jha",
  },
  {
    id: "340",
    question: "ણ",
    options: ['Na', 'Cha', 'ja', 'cha'],
    correct: "Na",
  },
  {
    id: "341",
    question: "ન",
    options: ['na', 'jha', 'Cha', 'cha'],
    correct: "na",
  },
  {
    id: "342",
    question: "ચ",
    options: ['cha', 'Cha', 'jha', 'Na'],
    correct: "cha",
  },
  {
    id: "343",
    question: "છ",
    options: ['Cha', 'na', 'ja', 'jha'],
    correct: "Cha",
  },
  {
    id: "344",
    question: "જ",
    options: ['ja', 'na', 'Na', 'jha'],
    correct: "ja",
  },
  {
    id: "345",
    question: "ઝ",
    options: ['jha', 'ja', 'Cha', 'cha'],
    correct: "jha",
  },
  {
    id: "346",
    question: "ણ",
    options: ['Na', 'Cha', 'ja', 'cha'],
    correct: "Na",
  },
  {
    id: "347",
    question: "ન",
    options: ['na', 'ja', 'jha', 'cha'],
    correct: "na",
  },
  {
    id: "348",
    question: "ચ",
    options: ['cha', 'na', 'jha', 'Cha'],
    correct: "cha",
  },
  {
    id: "349",
    question: "છ",
    options: ['Cha', 'Na', 'jha', 'cha'],
    correct: "Cha",
  },
  {
    id: "350",
    question: "જ",
    options: ['ja', 'na', 'Cha', 'Na'],
    correct: "ja",
  },
  {
    id: "351",
    question: "ઝ",
    options: ['jha', 'Na', 'cha', 'na'],
    correct: "jha",
  },
  {
    id: "352",
    question: "ણ",
    options: ['Na', 'jha', 'cha', 'Cha'],
    correct: "Na",
  },
  {
    id: "353",
    question: "ન",
    options: ['na', 'Cha', 'jha', 'Na'],
    correct: "na",
  },
  {
    id: "354",
    question: "ચ",
    options: ['cha', 'Cha', 'Na', 'ja'],
    correct: "cha",
  },
  {
    id: "355",
    question: "છ",
    options: ['Cha', 'ja', 'na', 'jha'],
    correct: "Cha",
  },
  {
    id: "356",
    question: "જ",
    options: ['ja', 'Cha', 'jha', 'cha'],
    correct: "ja",
  },
  {
    id: "357",
    question: "ઝ",
    options: ['jha', 'cha', 'Na', 'ja'],
    correct: "jha",
  },
  {
    id: "358",
    question: "ણ",
    options: ['Na', 'jha', 'cha', 'Cha'],
    correct: "Na",
  },
  {
    id: "359",
    question: "ન",
    options: ['na', 'Cha', 'ja', 'cha'],
    correct: "na",
  },
  {
    id: "360",
    question: "ચ",
    options: ['cha', 'Na', 'Cha', 'jha'],
    correct: "cha",
  },
  {
    id: "361",
    question: "છ",
    options: ['Cha', 'na', 'ja', 'Na'],
    correct: "Cha",
  },
  {
    id: "362",
    question: "જ",
    options: ['ja', 'Cha', 'na', 'jha'],
    correct: "ja",
  },
  {
    id: "363",
    question: "ઝ",
    options: ['jha', 'Na', 'ja', 'na'],
    correct: "jha",
  },
  {
    id: "364",
    question: "ણ",
    options: ['Na', 'cha', 'ja', 'Cha'],
    correct: "Na",
  },
  {
    id: "365",
    question: "ન",
    options: ['na', 'Cha', 'Na', 'cha'],
    correct: "na",
  },
  {
    id: "366",
    question: "ચ",
    options: ['cha', 'ja', 'na', 'Cha'],
    correct: "cha",
  },
  {
    id: "367",
    question: "છ",
    options: ['Cha', 'ja', 'cha', 'Na'],
    correct: "Cha",
  },
  {
    id: "368",
    question: "જ",
    options: ['ja', 'cha', 'jha', 'Na'],
    correct: "ja",
  },
  {
    id: "369",
    question: "ઝ",
    options: ['jha', 'Na', 'Cha', 'ja'],
    correct: "jha",
  },
  {
    id: "370",
    question: "ણ",
    options: ['Na', 'jha', 'Cha', 'cha'],
    correct: "Na",
  },
  {
    id: "371",
    question: "ન",
    options: ['na', 'cha', 'jha', 'Na'],
    correct: "na",
  },
  {
    id: "372",
    question: "ચ",
    options: ['cha', 'na', 'jha', 'ja'],
    correct: "cha",
  },
  {
    id: "373",
    question: "છ",
    options: ['Cha', 'na', 'jha', 'Na'],
    correct: "Cha",
  },
  {
    id: "374",
    question: "જ",
    options: ['ja', 'Cha', 'Na', 'na'],
    correct: "ja",
  },
  {
    id: "375",
    question: "ઝ",
    options: ['jha', 'na', 'Na', 'ja'],
    correct: "jha",
  },
  {
    id: "376",
    question: "ણ",
    options: ['Na', 'cha', 'na', 'ja'],
    correct: "Na",
  },
  {
    id: "377",
    question: "ન",
    options: ['na', 'Cha', 'jha', 'cha'],
    correct: "na",
  },
  {
    id: "378",
    question: "ચ",
    options: ['cha', 'jha', 'Cha', 'ja'],
    correct: "cha",
  },
  {
    id: "379",
    question: "છ",
    options: ['Cha', 'Na', 'jha', 'na'],
    correct: "Cha",
  },
  {
    id: "380",
    question: "જ",
    options: ['ja', 'na', 'jha', 'Cha'],
    correct: "ja",
  },
  {
    id: "381",
    question: "ઝ",
    options: ['jha', 'Na', 'cha', 'na'],
    correct: "jha",
  },
  {
    id: "382",
    question: "ણ",
    options: ['Na', 'jha', 'na', 'Cha'],
    correct: "Na",
  },
  {
    id: "383",
    question: "ન",
    options: ['na', 'ja', 'Na', 'Cha'],
    correct: "na",
  },
  {
    id: "384",
    question: "ચ",
    options: ['cha', 'jha', 'Cha', 'na'],
    correct: "cha",
  },
  {
    id: "385",
    question: "છ",
    options: ['Cha', 'ja', 'jha', 'na'],
    correct: "Cha",
  },
  {
    id: "386",
    question: "જ",
    options: ['ja', 'cha', 'Cha', 'na'],
    correct: "ja",
  },
  {
    id: "387",
    question: "ઝ",
    options: ['jha', 'cha', 'na', 'Na'],
    correct: "jha",
  },
  {
    id: "388",
    question: "ણ",
    options: ['Na', 'Cha', 'cha', 'ja'],
    correct: "Na",
  },
  {
    id: "389",
    question: "ન",
    options: ['na', 'cha', 'ja', 'Cha'],
    correct: "na",
  },
  {
    id: "390",
    question: "ચ",
    options: ['cha', 'Cha', 'na', 'ja'],
    correct: "cha",
  },
  {
    id: "391",
    question: "છ",
    options: ['Cha', 'na', 'ja', 'jha'],
    correct: "Cha",
  },
  {
    id: "392",
    question: "જ",
    options: ['ja', 'Cha', 'na', 'Na'],
    correct: "ja",
  },
  {
    id: "393",
    question: "ઝ",
    options: ['jha', 'ja', 'na', 'cha'],
    correct: "jha",
  },
  {
    id: "394",
    question: "ણ",
    options: ['Na', 'cha', 'jha', 'na'],
    correct: "Na",
  },
  {
    id: "395",
    question: "ન",
    options: ['na', 'ja', 'Na', 'cha'],
    correct: "na",
  },
  {
    id: "396",
    question: "ચ",
    options: ['cha', 'Na', 'ja', 'na'],
    correct: "cha",
  },
  {
    id: "397",
    question: "છ",
    options: ['Cha', 'jha', 'cha', 'ja'],
    correct: "Cha",
  },
  {
    id: "398",
    question: "જ",
    options: ['ja', 'Na', 'jha', 'na'],
    correct: "ja",
  },
  {
    id: "399",
    question: "ઝ",
    options: ['jha', 'na', 'Na', 'Cha'],
    correct: "jha",
  },
  {
    id: "400",
    question: "ણ",
    options: ['Na', 'ja', 'Cha', 'na'],
    correct: "Na",
  },
  {
    id: "401",
    question: "ન",
    options: ['na', 'cha', 'Cha', 'Na'],
    correct: "na",
  },
  {
    id: "402",
    question: "ચ",
    options: ['cha', 'jha', 'Na', 'ja'],
    correct: "cha",
  },
  {
    id: "403",
    question: "છ",
    options: ['Cha', 'cha', 'ja', 'Na'],
    correct: "Cha",
  },
  {
    id: "404",
    question: "જ",
    options: ['ja', 'jha', 'Cha', 'na'],
    correct: "ja",
  },
  {
    id: "405",
    question: "ઝ",
    options: ['jha', 'cha', 'ja', 'na'],
    correct: "jha",
  },
  {
    id: "406",
    question: "ણ",
    options: ['Na', 'Cha', 'cha', 'na'],
    correct: "Na",
  },
  {
    id: "407",
    question: "ન",
    options: ['na', 'Cha', 'jha', 'cha'],
    correct: "na",
  },
  {
    id: "408",
    question: "ચ",
    options: ['cha', 'na', 'jha', 'Na'],
    correct: "cha",
  },
  {
    id: "409",
    question: "છ",
    options: ['Cha', 'ja', 'jha', 'Na'],
    correct: "Cha",
  },
  {
    id: "410",
    question: "જ",
    options: ['ja', 'cha', 'jha', 'Na'],
    correct: "ja",
  },
  {
    id: "411",
    question: "ઝ",
    options: ['jha', 'ja', 'na', 'cha'],
    correct: "jha",
  },
  {
    id: "412",
    question: "ણ",
    options: ['Na', 'Cha', 'jha', 'cha'],
    correct: "Na",
  },
  {
    id: "413",
    question: "ન",
    options: ['na', 'cha', 'jha', 'ja'],
    correct: "na",
  },
  {
    id: "414",
    question: "ચ",
    options: ['cha', 'jha', 'na', 'Na'],
    correct: "cha",
  },
  {
    id: "415",
    question: "છ",
    options: ['Cha', 'na', 'ja', 'jha'],
    correct: "Cha",
  },
  {
    id: "416",
    question: "જ",
    options: ['ja', 'jha', 'Na', 'na'],
    correct: "ja",
  },
  {
    id: "417",
    question: "ઝ",
    options: ['jha', 'cha', 'na', 'ja'],
    correct: "jha",
  },
  {
    id: "418",
    question: "ણ",
    options: ['Na', 'jha', 'ja', 'na'],
    correct: "Na",
  },
  {
    id: "419",
    question: "ન",
    options: ['na', 'ja', 'jha', 'cha'],
    correct: "na",
  },
  {
    id: "420",
    question: "ચ",
    options: ['cha', 'Na', 'na', 'jha'],
    correct: "cha",
  },
  {
    id: "421",
    question: "છ",
    options: ['Cha', 'cha', 'Na', 'ja'],
    correct: "Cha",
  },
  {
    id: "422",
    question: "જ",
    options: ['ja', 'cha', 'Cha', 'jha'],
    correct: "ja",
  },
  {
    id: "423",
    question: "ઝ",
    options: ['jha', 'na', 'cha', 'ja'],
    correct: "jha",
  },
  {
    id: "424",
    question: "ણ",
    options: ['Na', 'cha', 'jha', 'na'],
    correct: "Na",
  },
  {
    id: "425",
    question: "ન",
    options: ['na', 'Na', 'Cha', 'jha'],
    correct: "na",
  },
  {
    id: "426",
    question: "ચ",
    options: ['cha', 'ja', 'Na', 'Cha'],
    correct: "cha",
  },
  {
    id: "427",
    question: "છ",
    options: ['Cha', 'jha', 'Na', 'ja'],
    correct: "Cha",
  },
  {
    id: "428",
    question: "જ",
    options: ['ja', 'jha', 'na', 'cha'],
    correct: "ja",
  },
  {
    id: "429",
    question: "ઝ",
    options: ['jha', 'cha', 'na', 'Cha'],
    correct: "jha",
  },
  {
    id: "430",
    question: "ણ",
    options: ['Na', 'na', 'cha', 'jha'],
    correct: "Na",
  },
  {
    id: "431",
    question: "ન",
    options: ['na', 'jha', 'cha', 'Cha'],
    correct: "na",
  },
  {
    id: "432",
    question: "ચ",
    options: ['cha', 'Na', 'jha', 'ja'],
    correct: "cha",
  },
  {
    id: "433",
    question: "છ",
    options: ['Cha', 'cha', 'ja', 'Na'],
    correct: "Cha",
  },
  {
    id: "434",
    question: "જ",
    options: ['ja', 'Na', 'na', 'cha'],
    correct: "ja",
  },
  {
    id: "435",
    question: "ઝ",
    options: ['jha', 'Cha', 'ja', 'cha'],
    correct: "jha",
  },
  {
    id: "436",
    question: "ણ",
    options: ['Na', 'jha', 'ja', 'cha'],
    correct: "Na",
  },
  {
    id: "437",
    question: "ન",
    options: ['na', 'Na', 'jha', 'Cha'],
    correct: "na",
  },
  {
    id: "438",
    question: "ચ",
    options: ['cha', 'Na', 'jha', 'na'],
    correct: "cha",
  },
  {
    id: "439",
    question: "છ",
    options: ['Cha', 'cha', 'Na', 'na'],
    correct: "Cha",
  },
  {
    id: "440",
    question: "જ",
    options: ['ja', 'Cha', 'na', 'jha'],
    correct: "ja",
  },
  {
    id: "441",
    question: "ઝ",
    options: ['jha', 'ja', 'na', 'Na'],
    correct: "jha",
  },
  {
    id: "442",
    question: "ણ",
    options: ['Na', 'jha', 'na', 'ja'],
    correct: "Na",
  },
  {
    id: "443",
    question: "ન",
    options: ['na', 'ja', 'jha', 'Cha'],
    correct: "na",
  },
  {
    id: "444",
    question: "ચ",
    options: ['cha', 'Na', 'Cha', 'jha'],
    correct: "cha",
  },
  {
    id: "445",
    question: "છ",
    options: ['Cha', 'cha', 'na', 'jha'],
    correct: "Cha",
  },
  {
    id: "446",
    question: "જ",
    options: ['ja', 'na', 'jha', 'cha'],
    correct: "ja",
  },
  {
    id: "447",
    question: "ઝ",
    options: ['jha', 'Cha', 'Na', 'cha'],
    correct: "jha",
  },
  {
    id: "448",
    question: "ણ",
    options: ['Na', 'ja', 'cha', 'na'],
    correct: "Na",
  },
  {
    id: "449",
    question: "ન",
    options: ['na', 'Cha', 'Na', 'ja'],
    correct: "na",
  },
  {
    id: "450",
    question: "ચ",
    options: ['cha', 'Na', 'Cha', 'ja'],
    correct: "cha",
  },
  {
    id: "451",
    question: "છ",
    options: ['Cha', 'na', 'cha', 'Na'],
    correct: "Cha",
  },
  {
    id: "452",
    question: "જ",
    options: ['ja', 'jha', 'Na', 'na'],
    correct: "ja",
  },
  {
    id: "453",
    question: "ઝ",
    options: ['jha', 'Cha', 'cha', 'ja'],
    correct: "jha",
  },
  {
    id: "454",
    question: "ણ",
    options: ['Na', 'Cha', 'jha', 'ja'],
    correct: "Na",
  },
  {
    id: "455",
    question: "ન",
    options: ['na', 'ja', 'Na', 'jha'],
    correct: "na",
  },
  {
    id: "456",
    question: "ચ",
    options: ['cha', 'ja', 'na', 'Na'],
    correct: "cha",
  },
  {
    id: "457",
    question: "છ",
    options: ['Cha', 'ja', 'cha', 'jha'],
    correct: "Cha",
  },
  {
    id: "458",
    question: "જ",
    options: ['ja', 'Na', 'jha', 'cha'],
    correct: "ja",
  },
  {
    id: "459",
    question: "ઝ",
    options: ['jha', 'Na', 'ja', 'Cha'],
    correct: "jha",
  },
  {
    id: "460",
    question: "ણ",
    options: ['Na', 'cha', 'Cha', 'ja'],
    correct: "Na",
  },
  {
    id: "461",
    question: "ન",
    options: ['na', 'Cha', 'Na', 'ja'],
    correct: "na",
  },
  {
    id: "462",
    question: "ચ",
    options: ['cha', 'Cha', 'ja', 'Na'],
    correct: "cha",
  },
  {
    id: "463",
    question: "છ",
    options: ['Cha', 'ja', 'jha', 'Na'],
    correct: "Cha",
  },
  {
    id: "464",
    question: "જ",
    options: ['ja', 'Cha', 'Na', 'na'],
    correct: "ja",
  },
  {
    id: "465",
    question: "ઝ",
    options: ['jha', 'Cha', 'Na', 'cha'],
    correct: "jha",
  },
  {
    id: "466",
    question: "ણ",
    options: ['Na', 'ja', 'jha', 'na'],
    correct: "Na",
  },
  {
    id: "467",
    question: "ન",
    options: ['na', 'Cha', 'ja', 'jha'],
    correct: "na",
  },
  {
    id: "468",
    question: "ચ",
    options: ['cha', 'jha', 'Cha', 'na'],
    correct: "cha",
  },
  {
    id: "469",
    question: "છ",
    options: ['Cha', 'ja', 'Na', 'jha'],
    correct: "Cha",
  },
  {
    id: "470",
    question: "જ",
    options: ['ja', 'na', 'Na', 'cha'],
    correct: "ja",
  },
  {
    id: "471",
    question: "ઝ",
    options: ['jha', 'Na', 'ja', 'na'],
    correct: "jha",
  },
  {
    id: "472",
    question: "ણ",
    options: ['Na', 'ja', 'cha', 'na'],
    correct: "Na",
  },
  {
    id: "473",
    question: "ન",
    options: ['na', 'jha', 'Na', 'cha'],
    correct: "na",
  },
  {
    id: "474",
    question: "ચ",
    options: ['cha', 'Cha', 'jha', 'Na'],
    correct: "cha",
  },
  {
    id: "475",
    question: "છ",
    options: ['Cha', 'cha', 'jha', 'Na'],
    correct: "Cha",
  },
  {
    id: "476",
    question: "જ",
    options: ['ja', 'jha', 'Na', 'Cha'],
    correct: "ja",
  },
  {
    id: "477",
    question: "ઝ",
    options: ['jha', 'na', 'Cha', 'cha'],
    correct: "jha",
  },
  {
    id: "478",
    question: "ણ",
    options: ['Na', 'jha', 'Cha', 'cha'],
    correct: "Na",
  },
  {
    id: "479",
    question: "ન",
    options: ['na', 'ja', 'jha', 'Cha'],
    correct: "na",
  },
  {
    id: "480",
    question: "ચ",
    options: ['cha', 'Cha', 'Na', 'na'],
    correct: "cha",
  },
  {
    id: "481",
    question: "છ",
    options: ['Cha', 'Na', 'na', 'cha'],
    correct: "Cha",
  },
  {
    id: "482",
    question: "જ",
    options: ['ja', 'na', 'cha', 'Cha'],
    correct: "ja",
  },
  {
    id: "483",
    question: "ઝ",
    options: ['jha', 'ja', 'cha', 'Na'],
    correct: "jha",
  },
  {
    id: "484",
    question: "ણ",
    options: ['Na', 'ja', 'jha', 'na'],
    correct: "Na",
  },
  {
    id: "485",
    question: "ન",
    options: ['na', 'Cha', 'jha', 'Na'],
    correct: "na",
  },
  {
    id: "486",
    question: "ચ",
    options: ['cha', 'Na', 'Cha', 'na'],
    correct: "cha",
  },
  {
    id: "487",
    question: "છ",
    options: ['Cha', 'jha', 'Na', 'cha'],
    correct: "Cha",
  },
  {
    id: "488",
    question: "જ",
    options: ['ja', 'na', 'jha', 'cha'],
    correct: "ja",
  },
  {
    id: "489",
    question: "ઝ",
    options: ['jha', 'Na', 'ja', 'cha'],
    correct: "jha",
  },
  {
    id: "490",
    question: "ણ",
    options: ['Na', 'na', 'jha', 'Cha'],
    correct: "Na",
  },
  {
    id: "491",
    question: "ન",
    options: ['na', 'Cha', 'cha', 'jha'],
    correct: "na",
  },
  {
    id: "492",
    question: "ચ",
    options: ['cha', 'jha', 'na', 'ja'],
    correct: "cha",
  },
  {
    id: "493",
    question: "છ",
    options: ['Cha', 'ja', 'cha', 'na'],
    correct: "Cha",
  },
  {
    id: "494",
    question: "જ",
    options: ['ja', 'jha', 'na', 'cha'],
    correct: "ja",
  },
  {
    id: "495",
    question: "ઝ",
    options: ['jha', 'Cha', 'ja', 'Na'],
    correct: "jha",
  },
  {
    id: "496",
    question: "ણ",
    options: ['Na', 'Cha', 'ja', 'na'],
    correct: "Na",
  },
  {
    id: "497",
    question: "ન",
    options: ['na', 'Cha', 'ja', 'Na'],
    correct: "na",
  },
  {
    id: "498",
    question: "ચ",
    options: ['cha', 'Cha', 'na', 'jha'],
    correct: "cha",
  },
  {
    id: "499",
    question: "છ",
    options: ['Cha', 'na', 'ja', 'jha'],
    correct: "Cha",
  },
  {
    id: "500",
    question: "જ",
    options: ['ja', 'cha', 'Na', 'jha'],
    correct: "ja",
  },
  {
    id: "501",
    question: "ઝ",
    options: ['jha', 'Cha', 'na', 'cha'],
    correct: "jha",
  },
  {
    id: "502",
    question: "ણ",
    options: ['Na', 'ja', 'cha', 'jha'],
    correct: "Na",
  },
  {
    id: "503",
    question: "ન",
    options: ['na', 'Na', 'ja', 'cha'],
    correct: "na",
  },
  {
    id: "504",
    question: "ચ",
    options: ['cha', 'ja', 'Cha', 'jha'],
    correct: "cha",
  },
  {
    id: "505",
    question: "છ",
    options: ['Cha', 'cha', 'ja', 'jha'],
    correct: "Cha",
  },
  {
    id: "506",
    question: "જ",
    options: ['ja', 'na', 'jha', 'cha'],
    correct: "ja",
  },
  {
    id: "507",
    question: "ઝ",
    options: ['jha', 'Cha', 'cha', 'na'],
    correct: "jha",
  },
  {
    id: "508",
    question: "ણ",
    options: ['Na', 'Cha', 'cha', 'ja'],
    correct: "Na",
  },
  {
    id: "509",
    question: "ન",
    options: ['na', 'Na', 'Cha', 'ja'],
    correct: "na",
  },
  {
    id: "510",
    question: "ચ",
    options: ['cha', 'na', 'ja', 'jha'],
    correct: "cha",
  },
  {
    id: "511",
    question: "છ",
    options: ['Cha', 'cha', 'na', 'Na'],
    correct: "Cha",
  },
  {
    id: "512",
    question: "જ",
    options: ['ja', 'Na', 'jha', 'Cha'],
    correct: "ja",
  },
  {
    id: "513",
    question: "ઝ",
    options: ['jha', 'Cha', 'na', 'ja'],
    correct: "jha",
  },
  {
    id: "514",
    question: "ણ",
    options: ['Na', 'Cha', 'na', 'jha'],
    correct: "Na",
  },
  {
    id: "515",
    question: "ન",
    options: ['na', 'cha', 'jha', 'Cha'],
    correct: "na",
  },
  {
    id: "516",
    question: "ચ",
    options: ['cha', 'ja', 'Na', 'na'],
    correct: "cha",
  },
  {
    id: "517",
    question: "છ",
    options: ['Cha', 'na', 'Na', 'ja'],
    correct: "Cha",
  },
  {
    id: "518",
    question: "જ",
    options: ['ja', 'Cha', 'na', 'Na'],
    correct: "ja",
  },
  {
    id: "519",
    question: "ઝ",
    options: ['jha', 'Na', 'na', 'Cha'],
    correct: "jha",
  },
  {
    id: "520",
    question: "ણ",
    options: ['Na', 'na', 'Cha', 'jha'],
    correct: "Na",
  },
  {
    id: "521",
    question: "ન",
    options: ['na', 'Cha', 'cha', 'ja'],
    correct: "na",
  },
  {
    id: "522",
    question: "ચ",
    options: ['cha', 'Na', 'na', 'ja'],
    correct: "cha",
  },
  {
    id: "523",
    question: "છ",
    options: ['Cha', 'Na', 'na', 'cha'],
    correct: "Cha",
  },
  {
    id: "524",
    question: "જ",
    options: ['ja', 'na', 'cha', 'Cha'],
    correct: "ja",
  },
  {
    id: "525",
    question: "ઝ",
    options: ['jha', 'ja', 'Na', 'Cha'],
    correct: "jha",
  },
  {
    id: "526",
    question: "ણ",
    options: ['Na', 'cha', 'jha', 'ja'],
    correct: "Na",
  },
  {
    id: "527",
    question: "ન",
    options: ['na', 'Na', 'Cha', 'jha'],
    correct: "na",
  },
  {
    id: "528",
    question: "ચ",
    options: ['cha', 'jha', 'Cha', 'ja'],
    correct: "cha",
  },
  {
    id: "529",
    question: "છ",
    options: ['Cha', 'jha', 'Na', 'cha'],
    correct: "Cha",
  },
  {
    id: "530",
    question: "જ",
    options: ['ja', 'na', 'jha', 'Na'],
    correct: "ja",
  },
  {
    id: "531",
    question: "ઝ",
    options: ['jha', 'cha', 'ja', 'Na'],
    correct: "jha",
  },
  {
    id: "532",
    question: "ણ",
    options: ['Na', 'ja', 'Cha', 'jha'],
    correct: "Na",
  },
  {
    id: "533",
    question: "ન",
    options: ['na', 'ja', 'cha', 'Cha'],
    correct: "na",
  },
  {
    id: "534",
    question: "ચ",
    options: ['cha', 'jha', 'ja', 'Na'],
    correct: "cha",
  },
  {
    id: "535",
    question: "છ",
    options: ['Cha', 'ja', 'cha', 'na'],
    correct: "Cha",
  },
  {
    id: "536",
    question: "જ",
    options: ['ja', 'jha', 'Na', 'cha'],
    correct: "ja",
  },
  {
    id: "537",
    question: "ઝ",
    options: ['jha', 'ja', 'cha', 'Cha'],
    correct: "jha",
  },
  {
    id: "538",
    question: "ણ",
    options: ['Na', 'ja', 'jha', 'cha'],
    correct: "Na",
  },
  {
    id: "539",
    question: "ન",
    options: ['na', 'Cha', 'ja', 'Na'],
    correct: "na",
  },
  {
    id: "540",
    question: "ચ",
    options: ['cha', 'na', 'Cha', 'Na'],
    correct: "cha",
  },
  {
    id: "541",
    question: "છ",
    options: ['Cha', 'cha', 'jha', 'ja'],
    correct: "Cha",
  },
  {
    id: "542",
    question: "જ",
    options: ['ja', 'Cha', 'jha', 'cha'],
    correct: "ja",
  },
  {
    id: "543",
    question: "ઝ",
    options: ['jha', 'Na', 'Cha', 'cha'],
    correct: "jha",
  },
  {
    id: "544",
    question: "ણ",
    options: ['Na', 'cha', 'ja', 'jha'],
    correct: "Na",
  },
  {
    id: "545",
    question: "ન",
    options: ['na', 'jha', 'cha', 'ja'],
    correct: "na",
  },
  {
    id: "546",
    question: "ચ",
    options: ['cha', 'Na', 'jha', 'ja'],
    correct: "cha",
  },
  {
    id: "547",
    question: "છ",
    options: ['Cha', 'cha', 'ja', 'Na'],
    correct: "Cha",
  },
  {
    id: "548",
    question: "જ",
    options: ['ja', 'cha', 'jha', 'Cha'],
    correct: "ja",
  },
  {
    id: "549",
    question: "ઝ",
    options: ['jha', 'cha', 'ja', 'na'],
    correct: "jha",
  },
  {
    id: "550",
    question: "ણ",
    options: ['Na', 'Cha', 'jha', 'ja'],
    correct: "Na",
  },
  {
    id: "551",
    question: "ન",
    options: ['na', 'Cha', 'jha', 'Na'],
    correct: "na",
  },
  {
    id: "552",
    question: "ચ",
    options: ['cha', 'jha', 'Na', 'Cha'],
    correct: "cha",
  },
  {
    id: "553",
    question: "છ",
    options: ['Cha', 'jha', 'Na', 'ja'],
    correct: "Cha",
  },
  {
    id: "554",
    question: "જ",
    options: ['ja', 'cha', 'Na', 'Cha'],
    correct: "ja",
  },
  {
    id: "555",
    question: "ઝ",
    options: ['jha', 'Na', 'na', 'cha'],
    correct: "jha",
  },
  {
    id: "556",
    question: "ણ",
    options: ['Na', 'jha', 'cha', 'na'],
    correct: "Na",
  },
  {
    id: "557",
    question: "ન",
    options: ['na', 'Na', 'Cha', 'ja'],
    correct: "na",
  },
  {
    id: "558",
    question: "ચ",
    options: ['cha', 'ja', 'Na', 'jha'],
    correct: "cha",
  },
  {
    id: "559",
    question: "છ",
    options: ['Cha', 'na', 'Na', 'ja'],
    correct: "Cha",
  },
  {
    id: "560",
    question: "જ",
    options: ['ja', 'Na', 'Cha', 'cha'],
    correct: "ja",
  },
  {
    id: "561",
    question: "ઝ",
    options: ['jha', 'Na', 'na', 'ja'],
    correct: "jha",
  },
  {
    id: "562",
    question: "ણ",
    options: ['Na', 'jha', 'cha', 'na'],
    correct: "Na",
  },
  {
    id: "563",
    question: "ન",
    options: ['na', 'jha', 'ja', 'Na'],
    correct: "na",
  },
  {
    id: "564",
    question: "ચ",
    options: ['cha', 'ja', 'Cha', 'na'],
    correct: "cha",
  },
  {
    id: "565",
    question: "છ",
    options: ['Cha', 'ja', 'Na', 'jha'],
    correct: "Cha",
  },
  {
    id: "566",
    question: "જ",
    options: ['ja', 'na', 'Na', 'jha'],
    correct: "ja",
  },
  {
    id: "567",
    question: "ઝ",
    options: ['jha', 'Na', 'ja', 'cha'],
    correct: "jha",
  },
  {
    id: "568",
    question: "ણ",
    options: ['Na', 'cha', 'na', 'Cha'],
    correct: "Na",
  },
  {
    id: "569",
    question: "ન",
    options: ['na', 'ja', 'jha', 'cha'],
    correct: "na",
  },
  {
    id: "570",
    question: "ચ",
    options: ['cha', 'ja', 'Cha', 'Na'],
    correct: "cha",
  },
  {
    id: "571",
    question: "છ",
    options: ['Cha', 'cha', 'Na', 'na'],
    correct: "Cha",
  },
  {
    id: "572",
    question: "જ",
    options: ['ja', 'Cha', 'Na', 'cha'],
    correct: "ja",
  },
  {
    id: "573",
    question: "ઝ",
    options: ['jha', 'cha', 'ja', 'na'],
    correct: "jha",
  },
  {
    id: "574",
    question: "ણ",
    options: ['Na', 'cha', 'Cha', 'jha'],
    correct: "Na",
  },
  {
    id: "575",
    question: "ન",
    options: ['na', 'jha', 'ja', 'Cha'],
    correct: "na",
  },
  {
    id: "576",
    question: "ચ",
    options: ['cha', 'na', 'Cha', 'jha'],
    correct: "cha",
  },
  {
    id: "577",
    question: "છ",
    options: ['Cha', 'Na', 'cha', 'ja'],
    correct: "Cha",
  },
  {
    id: "578",
    question: "જ",
    options: ['ja', 'na', 'Na', 'Cha'],
    correct: "ja",
  },
  {
    id: "579",
    question: "ઝ",
    options: ['jha', 'na', 'Na', 'cha'],
    correct: "jha",
  },
  {
    id: "580",
    question: "ણ",
    options: ['Na', 'ja', 'jha', 'na'],
    correct: "Na",
  },
  {
    id: "581",
    question: "ન",
    options: ['na', 'cha', 'Na', 'Cha'],
    correct: "na",
  },
  {
    id: "582",
    question: "ચ",
    options: ['cha', 'ja', 'jha', 'Na'],
    correct: "cha",
  },
  {
    id: "583",
    question: "છ",
    options: ['Cha', 'na', 'Na', 'jha'],
    correct: "Cha",
  },
  {
    id: "584",
    question: "જ",
    options: ['ja', 'jha', 'Cha', 'na'],
    correct: "ja",
  },
  {
    id: "585",
    question: "ઝ",
    options: ['jha', 'ja', 'cha', 'Cha'],
    correct: "jha",
  },
  {
    id: "586",
    question: "ણ",
    options: ['Na', 'cha', 'ja', 'jha'],
    correct: "Na",
  },
  {
    id: "587",
    question: "ન",
    options: ['na', 'Cha', 'Na', 'jha'],
    correct: "na",
  },
  {
    id: "588",
    question: "ચ",
    options: ['cha', 'ja', 'na', 'Cha'],
    correct: "cha",
  },
  {
    id: "589",
    question: "છ",
    options: ['Cha', 'na', 'jha', 'cha'],
    correct: "Cha",
  },
  {
    id: "590",
    question: "જ",
    options: ['ja', 'Cha', 'na', 'Na'],
    correct: "ja",
  },
  {
    id: "591",
    question: "ઝ",
    options: ['jha', 'na', 'cha', 'Cha'],
    correct: "jha",
  },
  {
    id: "592",
    question: "ણ",
    options: ['Na', 'cha', 'jha', 'na'],
    correct: "Na",
  },
  {
    id: "593",
    question: "ન",
    options: ['na', 'Na', 'cha', 'ja'],
    correct: "na",
  },
  {
    id: "594",
    question: "ચ",
    options: ['cha', 'na', 'Cha', 'Na'],
    correct: "cha",
  },
  {
    id: "595",
    question: "છ",
    options: ['Cha', 'na', 'Na', 'cha'],
    correct: "Cha",
  },
  {
    id: "596",
    question: "જ",
    options: ['ja', 'Na', 'jha', 'Cha'],
    correct: "ja",
  },
  {
    id: "597",
    question: "ઝ",
    options: ['jha', 'cha', 'Cha', 'ja'],
    correct: "jha",
  },
  {
    id: "598",
    question: "ણ",
    options: ['Na', 'jha', 'na', 'Cha'],
    correct: "Na",
  },
  {
    id: "599",
    question: "ન",
    options: ['na', 'jha', 'Na', 'cha'],
    correct: "na",
  },
];
